### ISSUE TITLE
Glance needs fully qulaified URL in Mitaka including proto

### ISSUE THREAD

**Issue by phalmos** [rcbops/rpc-openstack#1393] opened 2016-09-07 15:17 UTC
##### What type of issue is this? Please tick the appropriate box.
- [X] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is actually happening?
Glance "api_servers" in glance.conf needs fully qualified URL.  Error in logs:

2016-08-26 13:09:02.458 25410 WARNING nova.image.glance [req-53cebf11-78c2-47f2-b52d-c4ab9ae16d74 fadcdf6450234e65be9f7aa9d109ad48 a364d3abbadf4fe7a9b53dfa504291a4 - - -] No protocol specified in for api_server 'http://172.26.148.10:9292', please update [glance] api_servers with fully qualified url including scheme (http / https)

##### How can we reproduce this issue?
Upgrade from Liberty to Mitaka

##### How can we verify your issue is addressed?
Glance works and the correct URL is in glance.conf

##### What is your evaluation on the importance of this issue, and why?
Very important as Glance does not work after an upgrade

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [x] master https://github.com/rcbops/rpc-openstack/pull/1411
- [ ] mitaka-13.0

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [x] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [x] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [x] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [x] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by sigmavirus24** [comment] 2016-09-07 16:17
@phalmos don't you mean this needs to be updated in Nova conf? Nova needs the list of Glance API servers. Glance doesn't need to know this about itself

**Comment by phalmos** [comment] 2016-09-07 16:19
Ummm... Yes.  Sorry, Nova.conf.

**Comment by claco** [comment] 2016-09-07 16:20
Can you update the bug with:

**On which version(s) do you encounter this issue?**

Please provide the output to 'git describe --all' for all deployments where you have confirmed it occurs.

**Comment by sigmavirus24** [comment] 2016-09-07 16:21
@phalmos can you share the `[glance]` sectino of your nova conf?

**Comment by phalmos** [comment] 2016-09-07 16:41
@claco root@cn523:/opt/rpc-openstack# git describe --all
r13.0.0rc1

@sigmavirus24 
This is the "fixed" section from nova.conf
# Glance
[glance]
api_servers = http://172.26.148.10:9292

I worked around the issue by defining the override in user_variables.yml:

glance_api_servers: "http://172.26.148.10:9292"

**Comment by sigmavirus24** [comment] 2016-09-07 16:42
@phalmos right, I was hoping to see the section before fixing it.

**Comment by sigmavirus24** [comment] 2016-09-07 16:55
@git-harry found https://bugs.launchpad.net/openstack-ansible/+bug/1596084 which seems related

**Comment by sigmavirus24** [comment] 2016-09-07 17:24
So I've backported the fixes from that bug:

- https://review.openstack.org/366879
- https://review.openstack.org/366881

Those need to be reviewed and merged and then we would need a new SHA bump.

@git-harry with that in mind, and given that this appears to only be a warning (not broken functionality) should we put this off until r13.0.1? I don't think this is actually blocking anything otherwise we wouldn't have been able to boot instances from images.

**Comment by git-harry** [comment] 2016-09-07 17:41
@sigmavirus24 yes, on the assumption it doesn't break nova/glance we can leave it till a patch release. We should confirm that thought because the description includes the line 'Very important as Glance does not work after an upgrade'.

**Comment by sigmavirus24** [comment] 2016-09-07 18:03
@phalmos can you describe exactly what breaks when you say:

> Very important as Glance does not work after an upgrade

Also, this seems to be second issue related to upgrading to `r13.0.0rc1` from Liberty.

**Comment by sigmavirus24** [comment] 2016-09-07 18:32
From IRC:

> We were not able to build instances unless the image was cached on the compute node.  If nova had to get the image, it would fail.

I wonder how r13.0.0rc{1,2} tempest runs are able to boot images then with this same configuration default. Also unclear how anyone else is using OSA stable/mitaka but I'll defer to @jacobwagner and @jpmontez to see if they can reproduce this and let me see the environment.

**Comment by phalmos** [comment] 2016-09-07 18:48
This was an upgrade _not_ a greenfield deploy.  Not sure if QE has even tested upgrades.

**Comment by sigmavirus24** [comment] 2016-09-07 19:07
@phalmos right, the thing is that r13.0.* (including release candidates) are not meant for upgrades as has been the convention of this project for quite a while. r13.1.* will be the version people should upgrade to. Clearly you've already upgraded to this so we need to determine what the cause is, but if this is an upgrade problem, it should instead be targeted to r13.1.* as that's where all upgrades will be heading towards.

**Comment by git-harry** [comment] 2016-09-12 11:13
https://review.openstack.org/#/c/366879/ - merged
https://review.openstack.org/#/c/366881/ - needs review

**Comment by evrardjp** [comment] 2016-09-13 08:53
On it.

**Comment by git-harry** [comment] 2016-09-13 10:17
Both now merged in stable/mitaka

**Comment by evrardjp** [comment] 2016-09-13 10:44
@git-harry can't we directly move that into waiting for sha bump column?

**Comment by sigmavirus24** [comment] 2016-09-21 15:44
The SHA bump merged this morning was tracking the latest stable/mitaka commit which should contain this. I'm moving this to done.

**Closed by sigmavirus24** 2016-09-21 15:44 UTC
Labels: impacts-mitaka, prio-2, status-pending-sha-update, swimlane-enhancements, type-bug
