### ISSUE TITLE
Heat solutions timeout before completion

### ISSUE THREAD

**Issue by Rydor** [rcbops/rpc-openstack#1146] opened 2016-06-10 18:23 UTC
##### What version (commit) do you encounter this issue on?
12.2.0rc3

##### What type of issue is this (bug, feature, documentation, regression)?
bug

##### What is the expected behavior?
When you create a heat solution via the Solution tab it should complete successfully within 1 hour. 

##### What is actually happening?
The stack is failing to create after 1 hour due to the built in timeout. It times out on the task, "Stack Resource ID, deploy-salt-master, OS::Heat::SoftwareDeployment". The stack fails but the task status is "In_progress". Since the task isn't failing we aren't getting a stack trace of what is hanging. 
This Gist has an example of how the stack is failing with a task still in progress. 
https://gist.github.com/Rydor/3a0bede0b6b38bb0447dbf21d119ddb0 

These are only symptoms of a root problem. Why the task to deploy-salt-master isn't completing is the real defect.

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
I was testing the horizon solution tab. I selected to create a MangoDB solution. After waiting 1 hour i noticed the stack failed. I have attempted an ELK stack, Magento stack, MangoDB stack, and Drupal stack all with the same results.

##### How can we reproduce this issue?
Log into horizion for qe-iad3-lab03 and attempt to create any of the solutions on the Solutions tab.

##### How can we verify your issue is addressed?
Once a stack can be built successfully.

##### What is your evaluation on the importance of this issue, and why?
Potential blocker for 12.2.0rc3 release if its code. More investigation into root cause will be needed to properly access.

###### Remove branches (lines) you do not wish to target.
- [ ] Master
- [ ] liberty-12.2

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

**Comment by b3rnard0** [comment] 2016-06-10 18:40
@git-harry @d34dh0r53 @prometheanfire @sigmavirus24 or anyone else, this needs to be verified. Sounded like we have another related Horizon issue as well.

cc: @mancdaz @claco

**Comment by sigmavirus24** [comment] 2016-06-10 21:10
Do the salt states provide any logs of what's actually happening or is there nothing to introspect the template as it's running? The former would be necessary for us to understand why it's not working. If heat couldn't obtain/orchestrate the resources necessary for the template, then I could see why this might be on us because that could be a configuration issue. This seems like it may be a problem with the salt states though and the salt state authors would need to look into it.

**Comment by alextricity25** [comment] 2016-06-13 14:33
This can be debugged by going into the VMs and checking out the logs in /var/log/heat-deployments directory. The software-config scripts should be logged there assuming the heat agents are pre-backed into the image you are using.

**Comment by b3rnard0** [comment] 2016-06-13 16:40
Tasks:

- [ ] Reproduce the issue.
- [ ] Create a PR for fix and/or docs.
- [ ]  What is the gating for this on DEV and/or QE? Add related gating if appropriate. 
- [ ] Reach out to reporter (@rydor) to determine the fix is resolving the issue.

**Comment by Rydor** [comment] 2016-06-13 17:36
While attempting to gather more information based on Alex's suggestions, I notice that the QE labs have regressed since last Friday. I was not able to access the VMs to find additional logs and now I am no longer able to launch a solution via Horizon for QE-IAD3-lab02 nor QE-IAD3-lab03.

@alextricity25 
Please forgive my ignorance, should we be using specific images? You mentioned, "assuming the heat agents are pre-baked into the image you are using". What do you mean by this? We are using a cirros image which does not have a package manager. I am concerned that this may be the cause of the failures we are seeing but I don't understand the overall solution well enough to say.

**Comment by alextricity25** [comment] 2016-06-13 18:09
Hey Ryan,
The solutions require a 12.04 ubuntu image with heat-agents baked in. I'm not sure if testing on 14.04 image was ever done.
The heat templates use a heat resource called a "software-deployment" and "software-config" that require additional agents to be available on the image. 
These resources run scripts on a set of instances that install salt-master/client, register clients, and run salt formulas to deploy the solution.
A 12.04 image with the heat agents can be found here:
http://ab031d5abac8641e820c-98e3b8a8801f7f6b990cf4f6480303c9.r33.cf1.rackcdn.com/ubuntu-precise-heat-elements-2016_05.qcow2

Please give that image a try and let me know your results.

**Comment by b3rnard0** [comment] 2016-06-14 16:28
@alextricity25 are you and the team going to meet on this issue later today? Keep us updated on the outcome and add some updates on here.

**Comment by sigmavirus24** [comment] 2016-06-14 16:50
@b3rnard0 why does this impact onboarding?

**Comment by b3rnard0** [comment] 2016-06-14 16:55
@sigmavirus24 Because the new onboarders are focused on this and several other bugs. They have a specific board the use for tracking approved bug work.

**Comment by alextricity25** [comment] 2016-06-14 17:08
@b3rnard0 Yes we are going to meet and walk through reproducing the issue today. We will definitely keep you updated.

**Comment by alextricity25** [comment] 2016-06-14 19:45
We tried reproducing the bug, but right now we are having issues getting a workable image. The images that I have in my archives might be outdated and right now it doesn't seem like they are injecting my key properly. 
Having said that, maybe we could mark this down to prio-2, since this doesn't have much to do with the rpc-openstack code itself. But rather the image that is being used.
Our next course of action is to use a recently built image with the latest heat-agent code. I'll keep posting updates here to see what this yields.

**Comment by sigmavirus24** [comment] 2016-06-14 19:48
@alextricity25 you might want to connect with @chalupa and @BjoernT to find out what images are currently being used for this.

**Comment by sigmavirus24** [comment] 2016-06-14 19:49
Or @chalupaul .. I don't remember which is which ;)

**Comment by alextricity25** [comment] 2016-06-14 20:03
@sigmavirus24  Will do!

**Comment by BjoernT** [comment] 2016-06-14 20:07
So I used a CentOS 7 image which includes the heat client and it seemed to have been stuck actually trying to install the salt master which is usually a network issues not being able to download the included HOT templates, not coming to a point where it has to trigger the trigger/waitcondition

**Comment by alextricity25** [comment] 2016-06-14 20:14
@BjoernT The solutions require a *ubuntu* image that includes the heat-agents. The templates attempt to install salt with apt. 
See:
https://github.com/rcbops/RPC-Heat-Galera/blob/master/mariadb_stack.yaml#L240-L247

**Comment by BjoernT** [comment] 2016-06-14 20:20
Yeah the customer tested with a Ubuntu image but I think it did not contain a heat client. As I said it was stuck downloading the hot template for salt so it never got to that part. Even SSH key injection over metadata worked for me, a clear indication that something was on the network side. I'm just saying this is mostly the issue. Also we probably need to highlight that we hard coded APT stuff in it or make the hot template agnostic because customer always pick their image they are used to

**Comment by alextricity25** [comment] 2016-06-14 23:24
An update:
Once config_drive was turned on the image I referenced above went through just fine. That seems to have everything necessary to run the heat agents, but the instance is having a hard time hitting the metadata URL: http://<internal_lb_vip>:8000/v1
Maybe this has something to do with the way AIOs are setup? 
I can ping that address just fine from the instance, but can't seem to hit any of the openstack service endpoints. Even with security groups opened up to allow all TCP traffic.
Either we need to find a way for the instances to be able to curl the heat-cfn public endpoint or find a different environment to test this on that has that communication set-up already.

**Comment by alextricity25** [comment] 2016-06-15 03:06
Turns out the communication was because of incorrect checksums. In a nutshell, it's the same scenario as here:
https://github.com/rcbops/rpc-openstack/blob/master/scripts/deploy.sh#L179-L184

As a side note, the deploy.sh script should probably add a rule in for port 8000(the heat metadata service).

**Comment by alextricity25** [comment] 2016-06-16 00:25
I want to run this on a hardware lab to verify this isn't a problem with the rpc-code. Once I verify that we can officially decide if this is bug that belongs here or not.

**Comment by git-harry** [comment] 2016-06-17 15:25
@alextricity25 would you mind adding a comment with the latest regarding this issue. This is currently listed as the only blocker for r12.2.0.

**Comment by alextricity25** [comment] 2016-06-17 16:48
@git-harry. I'm currently working on a hardware lab to reproduce the issue, but am still working on getting my provider networks up in the LEM lab. The heat solutions absolutely require the provider networks with access to the internet. So I'm blocked until I can get this provider network up in the lab. I was told MudPuppy could help but he is on PTO.

Having said that, I think we are good to release r12.2.0. From the testing i've done, i can confidently say that, if anything, it's an issue with the heat-templates or salt formulas. If that's the case then those respective repos will need to be patched, which would in turn cause the heat solutions to work again.

Let me know if you have any questions.

**Comment by alextricity25** [comment] 2016-06-17 22:47
@git-harry @Rydor 
I finally got the provider networks working in our LEM lab(thank you @apsu and edgar for helping me get this set up). 

For the short-run, I was able to run the heat solution for galera successfully, so this bug is not reproducible and can be closed. The heat solutions work as expected. It would also be good to add to the docs that a special image is needed for these solutions

For the long-run, we should consider these points:

*  The UI for the heat solutions show HA networks as an option for "secondary network". This should probably be addressed in the UI code. I can open a separate bug report for that.

* The heat metadata URL is configured to hit the external_lb_vip_address right now. I strongly suggest this is changed to the internal_lb_vip_address for RPC deployments. That way additional ports won't need to be opened on the firewall. I can create a bug report for this as well.

* There is a way we can implement tests for the heat solutions by running certain components of the templates at a time. i.e. test software deployments, and software config scripts. I imagine this will be work that is fairly involved. Maybe we should create a wishlist item for this.

Let me know if anyone has any questions.

**Closed** 2016-06-17 22:48 UTC
Labels: impacts-onboarding, impacts-qe, prio-1, status-blocked, status-doing, status-needs-information

**Comment by git-harry** [comment] 2016-06-20 09:36
@Rydor are you now able to deploy a solution in your environment?

**Comment by b3rnard0** [comment] 2016-06-21 01:34
@git-harry @alextricity25 In your professional opinion, should this issue be a known issue to be included in the r12.2 release notes? cc: @erikmwilson @robb-romans

**Comment by alextricity25** [comment] 2016-06-21 04:06
@b3rnard0. I don't think it should be listed as a known issue since it really isn't an issue at all. The heat solutions work just fine when the environment is configured correctly and the special image is used.
I do think, like @git-harry suggested, that we should have some more clarity in our docs about what is needed to run the heat solutions. I've already added a small note in internal-docs about needing a special image, but some notes in the public-facing docs would also be good. I'll see what I can write up tomorrow.

**Comment by alextricity25** [comment] 2016-06-21 14:50
FYI docs patch has been made:
https://github.com/rackerlabs/docs-rpc/commit/c73ed2149ad9532af05f43d9f77c5e75b20b3d3c
