### ISSUE TITLE
MaaS alerts because of failing plugins

### ISSUE THREAD

**Issue by xeregin** [rcbops/rpc-openstack#1120] opened 2016-06-06 20:54 UTC
##### What version (commit) do you encounter this issue on?
12.2 rc3

##### What type of issue is this (bug, feature, documentation, regression)?
Bug

##### What is the expected behavior?
Horizon Python script running without a stacktrace

##### What is actually happening?
Horizon Python script is running with a stacktrace. This particular issue is caused by having multiple versions of six on the node.
Here is the output:
```
Traceback (most recent call last):
  File "./horizon_check.py", line 22, in <module>
    from maas_common import get_auth_details
  File "/usr/lib/rackspace-monitoring-agent/plugins/maas_common.py", line 51, in <module>
    from cinderclient import client as c_client
  File "/usr/local/lib/python2.7/dist-packages/cinderclient/client.py", line 30, in <module>
    from keystoneclient import discover
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/discover.py", line 24, in <module>
    from keystoneclient.v2_0 import client as v2_client
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v2_0/__init__.py", line 1, in <module>
    from keystoneclient.v2_0.client import Client  # noqa
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v2_0/client.py", line 21, in <module>
    from keystoneclient import httpclient
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/httpclient.py", line 152, in <module>
    class HTTPClient(baseclient.Client, base.BaseAuthPlugin):
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/httpclient.py", line 262, in HTTPClient
    user_agent=USER_AGENT, connect_retries=None, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/debtcollector/renames.py", line 38, in decorator
    @six.wraps(f)
AttributeError: 'module' object has no attribute 'wraps'
```

##### How can we reproduce this issue?
This issue can only be reproduced by running the Horizon Python script (https://github.com/rcbops/rpc-openstack/blob/master/maas/plugins/horizon_check.py) on a system where there is a bad version of six (1.5.2) installed in a directory with higher precedence over the directory where the good version of six (1.10.0) is located.
For instance:
- six 1.5.2 in /usr/lib/python2.7/dist-packages/six.py
- six 1.10.0 in /usr/local/lib/python2.7/dist-packages/six.py

##### How can we verify your issue is addressed?
By testing the fix in a lab where the issue exists or has been reproduced using the above method.

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?
By checking if 2 versions of six exist in environment paths, and backing up and eliminating any incorrect versions.

##### What is your evaluation on the importance of this issue, and why?
Importance: High impact to MaaS
Potential to occur: Low to Moderate

###### Remove branches (lines) you do not wish to target.
- [ ] Master
- [ ] liberty-12.2
- [ ] liberty-12.1
- [ ] kilo

**Comment by d34dh0r53** [comment] 2016-06-06 21:06
Looks like we'll need to create a venv for MaaS.

**Comment by xeregin** [comment] 2016-06-06 21:07
Looks like we'll just need to drink our own soda pop.

**Comment by git-harry** [comment] 2016-06-07 10:37
I have been unable to reproduce this on an AIO and the description does not match with what I see. When I manually run horizon_check.py it successfully returns the desired metric lines. Recent automated testing jobs were also successful in deploying the check:

http://jenkins.propter.net/job/RPC-AIO/6979/consoleFull
http://jenkins.propter.net/job/RPC-AIO/6990/consoleFull

I think the version in '/usr/lib/python2.7/dist-packages' is installed by Apt and the version in '/usr/local/lib/python2.7/dist-packages' is installed by Pip. If I open a Python interpreter and import six, the expected version (1.10.0) is the one imported.

```
# grep __version__ /usr/lib/python2.7/dist-packages/six.py
__version__ = "1.5.2"
# grep __version__ /usr/local/lib/python2.7/dist-packages/six.py
__version__ = "1.10.0"
# python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import six
>>> six.__version__
'1.10.0'
>>> six.__file__
'/usr/local/lib/python2.7/dist-packages/six.pyc'
>>> import sys
>>> for i in sys.path:
...     print i
... 

/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
```

**Comment by xeregin** [comment] 2016-06-08 15:56
This is what we're seeing in our lab:
```
root@697188-infra01:~# grep __version__ /usr/lib/python2.7/dist-packages/six.py
__version__ = "1.5.2"
root@697188-infra01:~# grep __version__ /usr/local/lib/python2.7/dist-packages/
Display all 206 possibilities? (y or n)
root@697188-infra01:~# grep __version__ /usr/local/lib/python2.7/dist-packages/six.py
__version__ = "1.10.0"
root@697188-infra01:~# python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import six
>>> six.__version__
'1.5.2'
>>> six.__file__
'/usr/lib/python2.7/dist-packages/six.pyc'
>>> import sys
>>> for i in sys.path:
...     print i
... 

/usr/lib/python2.7/dist-packages
/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/usr/local/lib/python2.7/dist-packages
/usr/local/lib/python2.7/dist-packages
```
As you can see, the reason is that /usr/local is the last path to be checked.
Is this something that should/could be validated by the deployment playbooks?

**Comment by tbyrom138** [comment] 2016-06-08 16:06
@BjoernT @JCallicoat 
Can we get supports input on this issue?  We're trying to determine if this is a 12.2 prio-1 or prio-2.

**Comment by BjoernT** [comment] 2016-06-08 16:34
We have other pip related issues open concerning MAAS and classifying this prio1

**Comment by xeregin** [comment] 2016-06-08 20:20
So, I've been digging into this a bit with @git-harry and we noticed that there are some additional pth files on the infra01 node that aren't on other nodes. Particularly, easy-install.pth and setuptools.pth were in /usr/local/lib/python2.7/dist-packages/.
Renaming those with a .bak extension apparently modified the path variables to what should be their correct order, and the issue was resolved. The curious part was when the .bak files were renamed back into .pth files, the path variables shifted again to their incorrect arrangement, however the version of six that was imported was still correct.
Overall, very interesting indeed. I am probably going to agree with @git-harry on this by saying that it seems to be an environmental issue, and not necessarily a code one. While it could be corrected by code, after further investigation, I'm not all that sure I would classify it as a priority 1 bug. A proper, long-term fix may take a while (moar virtual environments). I'll leave that decision to others, though.

**Comment by git-harry** [comment] 2016-06-09 08:56
I'm closing this issue. While there was a genuine failure we are both unable to reproduce it and unable to say how it was fixed. This issue was also isolated to a single node on a single deployment. It is possible that converting the MaaS role to use venvs would protect against this issue and there is already an issue to track that work https://github.com/rcbops/rpc-openstack/issues/787

**Closed by git-harry** 2016-06-09 08:56 UTC
Labels: impacts-maas, impacts-qe, prio-1, status-approved, type-bug
