### ISSUE TITLE
Corrupt Galera tables, unable to rejoin cluster

### ISSUE THREAD

**Issue by jpmontez** [rcbops/rpc-openstack#1199] opened 2016-06-27 16:50 UTC
##### What version (commit) do you encounter this issue on?
r12.2.0rc3 and r12.2.0rc4

##### What type of issue is this (bug, feature, documentation, regression)?
Bug

##### What is the expected behavior?
For Galera containers to upgrade, restart, and rejoin their cluster successfully

##### What is actually happening?
One or many Galera containers fail to restart and return this error message:

```
# galera_server_error.log
WSREP_SST: [INFO] Index compaction detected (20160627 12:10:24.245)
WSREP_SST: [INFO] Rebuilding during prepare with 4 threads (20160627 12:10:24.250)
WSREP_SST: [INFO] Compressed qpress files found (20160627 12:10:24.253)
WSREP_SST: [INFO] Decompression with 32 threads (20160627 12:10:24.256)
WSREP_SST: [INFO] Evaluating find /var/lib/mysql//.sst -type f -name '*.qp' -printf '%p\n%h\n' | xargs -n 2 qpress -T32d (20160627 12:10:24.258)
WSREP_SST: [INFO] Removing qpress files after decompression (20160627 12:10:25.923)
WSREP_SST: [INFO] Preparing the backup at /var/lib/mysql//.sst (20160627 12:10:25.940)
WSREP_SST: [INFO] Evaluating innobackupex --no-version-check  --apply-log $rebuildcmd ${DATA} &>${DATA}/innobackup.prepare.log (20160627 12:10:25.942)
WSREP_SST: [ERROR] Cleanup after exit with status:1 (20160627 12:10:27.899)
160627 12:10:27 [ERROR] WSREP: Process completed with error: wsrep_sst_xtrabackup-v2 --role 'joiner' --address '172.30.237.206' --datadir '/var/lib/mysql/' --defaults-file '/etc/mysql/my.cnf' --defaults-group-suffix '' --parent '12494' --binlog '/var/lib/mysql/mariadb-bin' : 1 (Operation not permitted)
```

```
2016-06-27 12:10:27 7fc64b7fe700 InnoDB: uncompressed page, stored checksum in field1 3735928559, calculated checksums for field1: crc32 177807968, innodb 3475755373, none 3735928559, stored checksum in field2 3735928559, calculated checksums for field2: crc32 177807968, innodb 1624572976, none 3735928559, page LSN 0 0, low 4 bytes of LSN at page end 0, page number (if stored to page already) 0, space id (if created with >= MySQL-4.1.1 and stored already) 0
InnoDB: Page may be a freshly allocated page
2016-06-27 12:10:27 7fc64b7fe700  InnoDB: Assertion failure in thread 140489646925568 in file rem0rec.cc line 577
InnoDB: We intentionally generate a memory trap.
InnoDB: Submit a detailed bug report to http://bugs.mysql.com.
InnoDB: If you get repeated assertion failures or crashes, even
InnoDB: immediately after the mysqld startup, there may be
InnoDB: corruption in the InnoDB tablespace. Please refer to
InnoDB: http://dev.mysql.com/doc/refman/5.6/en/forcing-innodb-recovery.html
InnoDB: about forcing recovery.
16:10:27 UTC - xtrabackup got signal 6 ;
This could be because you hit a bug or data is corrupted.
This error can also be caused by malfunctioning hardware.
We will try our best to scrape up some info that will hopefully help
diagnose the problem, but since we have already crashed,
something is definitely wrong and this may fail.

Thread pointer: 0x0
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
```

```
root@697188-infra01_galera_container-17ce0a1a:~# mysqld
160627 12:46:03 [Note] mysqld (mysqld 10.0.25-MariaDB-1~trusty-wsrep) starting as process 29309 ...
root@697188-infra01_galera_container-17ce0a1a:~# service mysql status
 * MariaDB is stopped.
```

##### What were you attempting to do when you encountered this error (give as much detail as possible)?
Trying to ping all hosts and containers before an RC bump

##### How can we reproduce this issue?
Attempt to upgrade-in-place from rc12.2.0rc3 to rc4.

##### How can we verify your issue is addressed?
The issue is present in both QE-IAD3-LAB02 and QE-IAD3-LAB03 in LEM.

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?
N/A

##### What is your evaluation on the importance of this issue, and why?
The Galera table corruption's underlying cause is unknown at the moment. One cluster was untouched before attempting to upgrade-in-place and the other was. If there's a bug with the software, then it has the potential to affect customer data.

###### Remove branches (lines) you do not wish to target.
- [ ] Master
- [ ] liberty-12.2
- [ ] liberty-12.1
- [ ] kilo

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

**Comment by sigmavirus24** [comment] 2016-06-27 18:40
Did you try following the steps listed [here](http://docs.openstack.org/developer/openstack-ansible/liberty/install-guide/ops-galera.html)?

**Comment by jpmontez** [comment] 2016-06-27 18:43
Yup, I've tried the single node recovery steps and those for rebuilding a container. Neither worked.

**Comment by prometheanfire** [comment] 2016-06-27 21:32
Could you try to rebuild the container?

**Comment by d34dh0r53** [comment] 2016-06-27 21:52
@sigmavirus24 and I are building FCFS-IAD3-2 with `r12.1.4` and are going to upgrade to `r12.12.0rc4` tomorrow to see if we can replicate the issue.

**Comment by mancdaz** [comment] 2016-06-28 12:39
I was unable to reproduce in an AIO when following the same upgrade as QE (rc3 > rc4). I also just double checked that there are not any galera/mariadb related changes between those two tags

rpco
```
git log r12.2.0rc3..r12.2.0rc4 --pretty=oneline --no-merges
8a3a6aaa0af5212d37f77aa774f1ea1721531b5c Ensure all hosts have a pip.conf
96ff1501eb5ad9055233a19ecd7b1de506cc2e2c Give maas rabbit user perms on all vhosts
5a5b9dc37796950f284bd62913fdff28fa60ece7 Update openstack-ansible SHA
980066814a4e3ea638119950dfc0a5789617ae13 Remove quotes from elasticsearch_url
9cd97d3e61cd1cdea942d8b2b1dd5fe89a310c55 fix holland backups
8285445ecd7b9b2cfbddf010364cb729e23fe917 Add cryptography to MaaS dependencies
835870f2dcfb3dcbb788b50b4197c21198fa4fa6 Update openstack-ansible SHA
```

osa
```
git log 434bfacb838940bea746db23ff1d7b0f851258a3..273912dab355deb4427240915b4fd8eb280d17f1 --pretty=oneline --no-merges273912dab355deb4427240915b4fd8eb280d17f1 Migrate keystone v2 images to v3 during Liberty upgrade
68d7402e05a87b4e8056f9f435deea441db37c00 Docs: Fix missing instructions for Liberty manual upgrades
b271778e16a83aefb0e704a9aca0ef09f405084c Use correct keystone auth parameters
2087e2698cde37f7447184bbaf115b85db65aa30 Add Nova extensions blacklisting
f4de56ab485772f5b335e68e64aee4ea2117d7a9 Add support for CustomLog format modification
f7ff05e01396a594c735e1fed82669a3e5db7b45 Use default metadata_backlog value from Neutron
cee84889eabf45d361027ae7cdecc90021ec74af Adding missing / to swift rabbit connection string
b3777c507b602ca9d44728e169e58e4811dda9bf Make ansible managed line in swift.conf static
98f2b2fd255952f4438f58de03a2f225d0664f2c Add support for CustomLog format modification
54f8ddfe9663cee93c7d939a541c39c679191735 Add MultiStrOps support to config_template
0bbee00c5fe872e2782d449ca4b6fa24235b5eab [GATE UNBLOCKER] Lock CPU map script to a release
4f60079786fc5594fd17cf86113bb5f400482d73 Update all SHAs for 12.0.15
a2adac22216686c38a2dca6992d41cea9090f992 Create symlink for libvirt save directory
204dd676d6a460f60cfb4bf2a3470da82ba2c9b6 Correct nova admin endpoint version
380c2116ea8dd618663ca3a5d7a7d368b5f4a5f5 Configure Swift dispersion tools to use Keystone v3
a9185101a37cdf21c08fb95dbff1010e24128888 Configure nofile OS limit for memcached server role
f4f93fc5441328082fd2fb5d76dfc73d46270b8f Include reseller admin role correctly
21a4465b8f7f296a3b02e50d8d5d206dff4635bf Updates all SHAs for 12.0.14
```

We also do not see this issue occurring in the gate. I suggest that we continue to try and reproduce in a multinode lab, and if we cannot then we do not consider this a blocking issue.

**Comment by mancdaz** [comment] 2016-06-28 12:48
@jpmontez what steps were you taking to upgrade from rc3 > rc4. Did you simply checkout the new tag and run ```deploy.sh``` ?

**Comment by jpmontez** [comment] 2016-06-28 14:10
Yeah, I checked out the new tag, updated the submodule, then ran `deploy.sh`.

**Comment by jacobwagner** [comment] 2016-06-28 14:57
More info here:

IAD3-LAB02: I saw this issue after the attempted upgrade to rc4 from rc3. I did not trigger the update but the job that ran the update is here

http://jenkins.openstack-ansible.com/job/RPC-OA/173/consoleFull

As you can see the state check failed.

When I attempted the failure recovery methods i did so in the following order
http://docs.openstack.org/developer/openstack-ansible/liberty/install-guide/ops-galera-recovery.html

http://docs.openstack.org/developer/openstack-ansible/liberty/install-guide/ops-galera-recoverysingle.html

http://docs.openstack.org/developer/openstack-ansible/liberty/install-guide/ops-galera-recoverycontainer.html

All 3 methods resulted in the same error that jpmontez filed in this bug. I have attempted this as well

http://dev.mysql.com/doc/refman/5.6/en/forcing-innodb-recovery.html

with a config of 1 and 2 for innodb_force_recovery, both did not work

I then dumped the DB, and retried the create container, it also failed.

I do not know were to go from here to recover from this failure

**Comment by jacobwagner** [comment] 2016-06-28 16:35
Found the bug

https://bugs.launchpad.net/percona-xtrabackup/+bug/1192834

**Comment by jacobwagner** [comment] 2016-06-28 20:07
in OSA

https://bugs.launchpad.net/openstack-ansible/+bug/1590166

**Comment by d34dh0r53** [comment] 2016-06-28 20:32
So after doing some digging I believe this is due to the galera cluster being in a bad state.  I found the following snippet on a galera node which was from several days prior to the upgrade being run:

```
160609 10:59:52 [Note] WSREP: New COMPONENT: primary = no, bootstrap = no, my_idx = 0, memb_num = 1
160609 10:59:52 [Note] WSREP: Flow-control interval: [16, 16]
160609 10:59:52 [Note] WSREP: Received NON-PRIMARY.
160609 10:59:52 [Note] WSREP: Shifting SYNCED -> OPEN (TO: 247643)
160609 10:59:52 [Note] WSREP: New COMPONENT: primary = no, bootstrap = no, my_idx = 0, memb_num = 1
160609 10:59:52 [Note] WSREP: Flow-control interval: [16, 16]
160609 10:59:52 [Note] WSREP: Received NON-PRIMARY.
160609 10:59:52 [Note] WSREP: New cluster view: global state: 586e49e9-2db8-11e6-80ba-b77dcbc8a290:247643, view# -1: non-Primary, number of nodes: 1, my index: 0, protocol version 3
160609 10:59:52 [Note] WSREP: wsrep_notify_cmd is not defined, skipping notification.
160609 10:59:52 [Note] WSREP: New cluster view: global state: 586e49e9-2db8-11e6-80ba-b77dcbc8a290:247643, view# -1: non-Primary, number of nodes: 1, my index: 0, protocol version 3
160609 10:59:52 [Note] WSREP: wsrep_notify_cmd is not defined, skipping notification.
160609 11:01:30 [Note] WSREP: (a2ef6dfc, 'tcp://0.0.0.0:4567') reconnecting to fa90021f (tcp://172.20.237.210:4567), attempt 30
160609 11:01:33 [Note] WSREP: (a2ef6dfc, 'tcp://0.0.0.0:4567') reconnecting to 586d2dc2 (tcp://172.20.236.61:4567), attempt 30
160609 11:03:00 [Note] WSREP: (a2ef6dfc, 'tcp://0.0.0.0:4567') reconnecting to fa90021f (tcp://172.20.237.210:4567), attempt 60
160609 11:03:03 [Note] WSREP: (a2ef6dfc, 'tcp://0.0.0.0:4567') reconnecting to 586d2dc2
.
.
.
160609 14:24:03 [Note] WSREP: (a2ef6dfc, 'tcp://0.0.0.0:4567') reconnecting to 586d2dc2 (tcp://172.20.236.61:4567), attempt 4080
160609 14:25:30 [Note] WSREP: (a2ef6dfc, 'tcp://0.0.0.0:4567') reconnecting to fa90021f (tcp://172.20.237.210:4567), attempt 4110
160609 14:25:33 [Note] WSREP: (a2ef6dfc, 'tcp://0.0.0.0:4567') reconnecting to 586d2dc2 (tcp://172.20.236.61:4567), attempt 4110
160609 14:26:34 [Note] /usr/sbin/mysqld: Normal shutdown
```

This is a similarity to [1590166](https://bugs.launchpad.net/openstack-ansible/+bug/1590166) in that their cluster was also in a bad state prior to an upgrade being run.  I think we need tracking on `xtrabackup-2.3` as well as a new more robust galera check.

**Comment by b3rnard0** [comment] 2016-06-28 22:00
So we need to make a known issue for the release notes on this galera bug.(@robb-romans or @erikmwilson). No idea when this will get fixed in Percona.

**Comment by robb-romans** [comment] 2016-06-28 22:32
Tracked here: https://github.com/rackerlabs/docs-rpc/issues/406

**Comment by robb-romans** [comment] 2016-06-28 22:43
@d34dh0r53 @jacobwagner @b3rnard0 It looks like there is no fix available. Can you please provide more information for the release notes? What do we need to tell customers? Is there a workaround?

Please comment in doc issue here https://github.com/rackerlabs/docs-rpc/issues/417

**Comment by b3rnard0** [comment] 2016-06-29 01:26
@robb-romans You'll have to get the information from @d34dh0r53 and/or @jacobwagner but, yeah, it's looking like there will not be a fix anytime soon.

**Comment by d34dh0r53** [comment] 2016-06-29 15:17
@robb-romans the primary workaround for this is to ensure that your infrastructure is in good health, specifically the galera cluster.  There are probably more but a couple of commands I would document are checking the free disk space of the nodes:

```bash
# Disk Usage
ansible galera_all -m shell -a 'df -h'
# Inode Usage
ansible galera_all -m shell -a 'df -i'
```

Another command that is useful is the MySQL status command.  We often run this command:

```sql
SHOW STATUS LIKE '%wsrep%';
```

Which gives detailed output as to the status of the cluster, lines of note are `wsrep_incoming_addresses` where you should expect to see the ip addresses of each member of the cluster, if you don't something is wrong.  Another line to pay attention to is the `wsrep_local_state_comment`, this should have a status of `Synced`,  finally `wsrep_cluster_status` should be `Primary` on all three nodes.  These commands should be run on all of the nodes to ensure that each node has the correct *view* of the world.  Here is some ansible to quickly check the status of all of the nodes:

```bash
# wsrep_incoming_addresses
ansible galera_all -m shell -a "mysql -e \"show status like 'wsrep_incoming_addresses'\""
# wsrep_local_state_comment
ansible galera_all -m shell -a "mysql -e \"show status like 'wsrep_local_state_comment'\""
# wsrep_cluster_status
ansible galera_all -m shell -a "mysql -e \"show status like 'wsrep_cluster_status'\""
```

**Comment by robb-romans** [comment] 2016-06-29 15:24
@d34dh0r53 Thanks! Should this be put in the upgrade guide here https://staging.developer.rackspace.com/staging.horse/review/docs/private-cloud/rpc/master/rpc-upgrade/rpc-upgrade-v11-v12-prereq/

**Comment by d34dh0r53** [comment] 2016-06-29 15:25
@robb-romans yeah, that is a perfect place for it.

**Comment by robb-romans** [comment] 2016-06-30 14:19
The documentation is published externally here: https://developer.rackspace.com/docs/private-cloud/rpc/v12/rpc-upgrade/rpc-upgrade-v11-v12-prereq/

**Comment by mancdaz** [comment] 2016-07-27 09:05
closing issue, as workaround/pre upgrade procedure has been documented.

**Closed by mancdaz** 2016-07-27 09:05 UTC
Labels: impacts-doc, impacts-qe, prio-wishlist
