### ISSUE TITLE
neutron metadata plugin is very lxc specific

### ISSUE THREAD

**Issue by mancdaz** [rcbops/rpc-openstack#636] opened 2015-11-26 09:09 UTC
It may be unavoidable, I don't know, but we rely very heavily on the deployment being lxc/osa based for this plugin to work [1]. 

Filing this bug to see if there's any way around this to allow rpc-o teams to use the plugin too

[1] https://github.com/rcbops/rpc-openstack/blob/master/maas/plugins/neutron_metadata_local_check.py#L29 && https://github.com/rcbops/rpc-openstack/blob/master/maas/plugins/neutron_metadata_local_check.py#L58

**Comment by andymcc** [comment] 2015-12-11 14:46
I don't think there is a way around this - unless we monitor ALL agents containers from the deployment host.

We need to get onto the container in order to access the network namespace to perform the test - but we don't have sshkey access from the host --> it's containers, only from the deployment host --> all containers/other hosts (in order for ansible to run properly).

That would mean 1 of 2 options:

1. We monitor all agents from the deployment host - I think this is a bad idea because all alerts for these agent containers will be targeted to the deployment host... if that host is under maintenance we will get no alerts - there would be no way to change that.
2. We deploy ssh keys to the hosts - I think this is a bad idea because we are adding a requirement that is otherwise not needed anywhere else, just for the sake of monitoring.

I'd probably mark this as "won't fix" with the above in mind.

**Comment by andymcc** [comment] 2015-12-11 14:49
@mancdaz I think we should probably close this? Or do you think there is other work we can do here.

**Comment by andymcc** [comment] 2015-12-14 13:29
Ok so I believe the issue is that this is a problem for osp. I'm not sure the best course of action then - I can't see another way for us to do this, so we'd have to heavily adjust the script (or create a new script) that allows you to just run the name space queries on a specific host without doing the lxc bits (or any other remote connect).

Depending on the architecture for osp.

**Comment by stevelle** [comment] 2015-12-14 15:17
Because we disabled this check in master and reopened the original issue that caused creation of that check, I think the recommendation should be for OSP to not use this check.

**Comment by git-harry** [comment] 2016-07-26 10:49
This plugin is not currently used. There is a new issue to track a new implementation https://github.com/rcbops/u-suk-dev/issues/239 so I think this one can be closed.

**Closed by git-harry** 2016-07-26 10:49 UTC
Labels: feature-monitoring, impacts-rpcr, prio-wishlist, status-wontfix, type-enhancement
