### ISSUE TITLE
Add monitoring for beaver / filebeat and rsyslog processes

### ISSUE THREAD

**Issue by JCallicoat** [rcbops/rpc-openstack#1236] opened 2016-07-14 00:33 UTC
##### What version (commit) do you encounter this issue on?

N/A
##### What type of issue is this (bug, feature, documentation, regression)?

Feature request
##### What is the expected behavior?

The beaver (or filebeat for r13) and rsyslog processes are monitored to ensure they are running.
##### What is actually happening?

The beaver and/or rsyslog processes sometimes die and logs are not shipped to elasticsearch and/or rsyslog, respectively.
###### Remove branches (lines) you do not wish to target.
- [x] Master
- [x] mitaka-13.1
- [ ] liberty-12.2
- [ ] kilo
##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues)
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc)
- [x] No documentation required for this change

**Comment by tomc603** [comment] 2016-07-20 14:42
I'm interested in gathering feedback on this. Specifically, how can we supervise processes inside containers without having some kind of "agent" within the container. Perhaps we could attempt to connect to the daemons? Doing that may require external dependencies to prove more than TCP connectivity, though.

**Comment by tomc603** [comment] 2016-07-20 19:41
As of now, the solution will probably be to create a generic process check function in maas_common, which can then be called from any other check scripts that may need to verify the existence of a running process.

Once that is done, I will create a check script each for beaver, filebeat, and rsyslog. I'm not entirely sure how we would control which script(s) are run where, but I'll ask around once they're done just to confirm I don't need them to fail safely if the utility isn't present or supposed to run.

**Comment by b3rnard0** [comment] 2016-07-21 16:27
@tomc603 BTW, what size enhancement is this? Can it go in a revision release or is it more appropriate for a minor/major release that will need QE testing, etc.

**Comment by tomc603** [comment] 2016-07-21 16:43
This is a pretty trivial change- Adding a few functions to maas_common, then writing scripts to utilize those functions. I'd say a revision release is good enough for this.

**Comment by tomc603** [comment] 2016-07-21 23:33
I've changed tack slightly, but it may work better. I have a generic `process_check.py` script, which accepts one or more process names (the executable portion of a command line) as parameters.

The script reports a `metric_bool` status for each process specified, with the value of that status being the result of searching the running process list for the process.

The reason behind not adding a check to the maas_common library is that by putting all of the logic into the `process_check.py` script, we can perform multiple checks more easily, keep import sprawl down, and keep the number of attempts to gather a process list to a minimum.

**Comment by tomc603** [comment] 2016-07-22 00:11
I'm going to reach out tomorrow to find out how best to configure a host to execute a check using this script. Based on other maas tests, it's probably going to be a templated section of a config file, but I want to be sure there isn't a better way.

**Comment by tomc603** [comment] 2016-07-22 17:37
Apparently I didn't git push this last night. So that was dumb of me.

**Comment by tomc603** [comment] 2016-08-01 18:56
I have work done to create a template that contains configuration for each service on each host, which might be an acceptable minimal first merge. I'd prefer to have a single configured check for multiple processes.

**Comment by b3rnard0** [comment] 2016-08-02 15:13
@tomc603 Please provide an update on this issue. Thanks!

**Comment by tomc603** [comment] 2016-08-09 21:26
Today's update. The branch is here https://github.com/rcbops/rpc-openstack/tree/issues/1236.

I spoke with Nolan @Apsu and @stevelle to work through what I was missing and what the best approach was to get the templates rendering properly. So, that was another refactor, but well worth the work.

Refactoring the template also allowed me to discover an issue that psutil has when attempting to call `Process.name()` on items yielded by `process_iter()`. An exception was being thrown, and even after catching and `pass`ing it, a list of process names was not returned. A slight refactor on the process name fetching code fixed this, and I can confirm that it Works For Me™.

@cloader89 wanted to take a look at this and see if he can help. I'd like for him to take a crack at creating the other MaaS check templates and testing on an AIO he has built.

**Comment by cloader89** [comment] 2016-08-15 20:21
Update: running tests with the new check templates created.

**Comment by cloader89** [comment] 2016-08-16 20:59
Ran into a small issue involving defining variables for a specific task. I did toy with using with_dict and failed. Still looking for a solution.

**Comment by cloader89** [comment] 2016-08-24 21:27
I am in the process of trying to figure out why maas checks are not being setup while using these changes:

https://github.com/rcbops/rpc-openstack/commit/bced5025cfbc17bd800668bdd21410bde536f328

if anyone has any suggestions, I am open to them,

**Comment by tomc603** [comment] 2016-08-29 18:08
Checks don't seem to be registering in the list of MaaS checks on the portal, so @cloader89 is going to look for feedback from the group at large to see what is required to get the checks to appear.

**Comment by sigmavirus24** [comment] 2016-08-30 15:55
Quick question: How are you determining which instance of these processes is running on the host versus in a container and how are you reporting that to MaaS? MaaS only runs on the hosts because it needs a device to report for which means that it cannot run in containers.

**Comment by tomc603** [comment] 2016-09-01 22:53
I've now added a parameter to check for processes running within a container or on the host itself. Supplying the `-c`/`--container` argument will limit the process search scope to only the given container, so this will require a change to the arguments passed in the MaaS check templates. Omitting the argument will check only the host for the given process(es).

Additionally, the processes supplied as parameters to the check script may be the fully qualified executable path, or the basename of the executable. This should make checks more robust given varying input.

All of this has required the removal of the `psutil` library, which honestly brought its own odd behavior anyway.

**Comment by cloader89** [comment] 2016-09-06 21:37
Update: I fixed an issue with the labeling the alarms. The fix has temporarily stopped all the checks from running. Will need to restructure the logic in process.yml  and the template files to use the said fix.

It was overwriting the processes variable  when setting facts. The fix made a new list that the processes are in.

**Comment by d34dh0r53** [comment] 2016-09-08 12:43
Any updates on this?  You guys need any help?

**Comment by cloader89** [comment] 2016-09-09 01:44
I will update you @d34dh0r53  I have all the moving parts, just need them to work together. I will get with you tomorrow and see if you can help us.  Please take a look at the PR, pushing latest updates now.  We have the set_facts right now, just making it work correctly with the 4 templates.

**Comment by cloader89** [comment] 2016-09-13 20:42
Need reviews. Thanks.

**Comment by cloader89** [comment] 2016-09-21 03:34
Update: Making suggested changes by @alextricity25 and debugging.

What's next: reviews and gate passing

Any blockers: No

**Comment by cloader89** [comment] 2016-09-21 21:22
Update: Made the said changes, and pushed a new version of the code to the PR #1366. Waiting on reviews. 

Need verify-maas to work in the gate.

**Comment by cloader89** [comment] 2016-09-23 21:31
Update: Addressing the changes proposed. Also, need verify-maas to cooperate.

**Comment by cloader89** [comment] 2016-09-28 14:49
Looking into gating issues with @sigmavirus24 and @hughsaunders

**Comment by cloader89** [comment] 2016-09-28 21:08
Looks like the order of playbook running is the issue. I will open an issue tomorrow and fix it.

**Comment by git-harry** [comment] 2016-09-29 16:39
Blocked by https://github.com/rcbops/rpc-openstack/issues/1448

**Comment by git-harry** [comment] 2016-09-30 14:34
#1448 is fixed in master so we should be able to get this card moving again.

**Comment by tomc603** [comment] 2016-10-06 14:15
I addressed the feedback in the reviews, but seem to have introduced an error...potentially with a missing ",". I built an AIO yesterday so I can test my fix and update the PR.

**Comment by sigmavirus24** [comment] 2016-10-06 14:21
@tomc603 I believe I commented on the PR exactly where you introduced that error to make it easier for you to fix.

**Comment by tomc603** [comment] 2016-10-06 15:36
@sigmavirus24 Yeah, I caught that last night. Thanks! The latest push has fixed the missing comma.

**Comment by cloader89** [comment] 2016-10-13 18:39
@JCallicoat can you update which backports you want? I noticed kilo is EOL. Also did you want liberty-12.2 still? 

@git-harry @b3rnard0

**Comment by sigmavirus24** [comment] 2016-10-13 19:09
@cloader89 kilo is not EOL. This should go all the way back IMO

**Comment by alextricity25** [comment] 2016-10-13 19:25
That's my fault. I commented on the Kilo backport thinking Kilo was EOL. Turns out it isn't. Sorry for the confusion!

**Comment by cloader89** [comment] 2016-10-13 20:18
Sorry, wanted to clarify. Thanks @sigmavirus24

**Comment by git-harry** [comment] 2016-10-14 10:17
https://github.com/rcbops/rpc-openstack/issues/1448 only appears to have been fixed in master but based on the build logs appears to affect other branches - http://jenkins.propter.net/job/JJB-RPC-AIO_mitaka-ceph/689/consoleFull

**Comment by cloader89** [comment] 2016-10-17 21:37
Today, I was able to backport all the versions of #1448. Although travis change was not backported. I started the PRs for backports, all needed now is to get them merged.

**Comment by cloader89** [comment] 2016-10-19 14:28
This relies on the backporting of #512

**Comment by tomc603** [comment] 2016-10-19 14:29
There is also feedback on the pull requests to use `git cherry-pick -x` to reference the original commit in the message.

**Comment by cloader89** [comment] 2016-10-19 14:30
I know, I'm going to do that today.

**Comment by git-harry** [comment] 2016-10-19 14:37
Blocked by https://github.com/rcbops/rpc-openstack/issues/1515

**Comment by sigmavirus24** [comment] 2016-10-24 13:22
This is also blocked by r13.1.0 release for the backports (since we need to merge to mitaka-13.1 first and then 13.0 and older).

**Comment by cloader89** [comment] 2016-10-24 21:29
Today, a revert has been initiated on merged PR #1491. As @sigmavirus24 mentioned, it is blocked until r13.1.0 is released.

https://github.com/rcbops/rpc-openstack/pull/1537 this is the revert.

Tomorrow, I am out of the office.

Any blockers: r13.1.0 release.

**Comment by sigmavirus24** [comment] 2016-10-25 12:11
#1537 is merged. I'm going to propose a revert of that and mark it as "dont-merge" until after r13.1.0

**Comment by cloader89** [comment] 2016-11-04 23:59
Backports all passed gating, need reviews.

**Comment by sigmavirus24** [comment] 2016-11-10 19:08
Ran into a problem moving this to done with waffle. Sorry for the confusion about "Pending SHA update"

**Closed** 2016-11-10 19:08 UTC
Labels: impacts-support, prio-2, swimlane-rr, type-enhancement-small
