### ISSUE TITLE
pip install cryptography still failing

### ISSUE THREAD

**Issue by shane-c** [rcbops/rpc-openstack#1260] opened 2016-07-22 23:29 UTC
##### On which version(s) do you encounter this issue?

root@infra01:/opt/rpc-openstack/rpcd/playbooks# git describe --all
r12.2.1

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

pip install cryptography works

##### What is actually happening?

pip install cryptography fails

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

Running site.yml

````
failed: [infra03] => (item=cryptography) => {"cmd": "/usr/local/bin/pip install cryptography", "failed": true, "item": "cryptography"}
msg: stdout: Collecting cryptography
  Downloading cryptography-1.4.tar.gz (399kB)
Collecting idna>=2.0 (from cryptography)
  Downloading idna-2.1-py2.py3-none-any.whl (54kB)
Collecting pyasn1>=0.1.8 (from cryptography)
  Downloading pyasn1-0.1.9-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in /usr/lib/python2.7/dist-packages (from cryptography)
Requirement already satisfied (use --upgrade to upgrade): setuptools>=11.3 in /usr/local/lib/python2.7/dist-packages (from cryptography)
Collecting enum34 (from cryptography)
  Downloading enum34-1.1.6-py2-none-any.whl
Collecting ipaddress (from cryptography)
  Downloading ipaddress-1.0.16-py27-none-any.whl
Collecting cffi>=1.4.1 (from cryptography)
  Downloading cffi-1.7.0-cp27-cp27mu-manylinux1_x86_64.whl (383kB)
Collecting pycparser (from cffi>=1.4.1->cryptography)
  Downloading pycparser-2.14.tar.gz (223kB)
Building wheels for collected packages: cryptography, pycparser
  Running setup.py bdist_wheel for cryptography: started
  Running setup.py bdist_wheel for cryptography: finished with status 'error'
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0XgEPM/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpydYqS5pip-wheel- --python-tag cp27:
  c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
   #include <ffi.h>
                   ^
  compilation terminated.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-0XgEPM/cryptography/setup.py", line 333, in <module>
      **keywords_with_side_effects(sys.argv)
    File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
      _setup_distribution = dist = klass(attrs)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 269, in __init__
      self.fetch_build_eggs(attrs['setup_requires'])
    File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
      replace_conflicting=True,
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 826, in resolve
      dist = best[req.key] = env.best_match(req, ws, installer)
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
      return self.obtain(req, installer)
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
      return installer(requirement)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
      return cmd.easy_install(req)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 664, in easy_install
      return self.install_item(spec, dist.location, tmpdir, deps)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 694, in install_item
      dists = self.install_eggs(spec, download, tmpdir)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 875, in install_eggs
      return self.build_and_install(setup_script, setup_base)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1114, in build_and_install
      self.run_setup(setup_script, setup_base, args)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1102, in run_setup
      raise DistutilsError("Setup script exited with %s" % (v.args[0],))
  distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

  ----------------------------------------
  Running setup.py clean for cryptography
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0XgEPM/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" clean --all:
  c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
   #include <ffi.h>
                   ^
  compilation terminated.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-0XgEPM/cryptography/setup.py", line 333, in <module>
      **keywords_with_side_effects(sys.argv)
    File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
      _setup_distribution = dist = klass(attrs)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 269, in __init__
      self.fetch_build_eggs(attrs['setup_requires'])
    File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
      replace_conflicting=True,
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 826, in resolve
      dist = best[req.key] = env.best_match(req, ws, installer)
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
      return self.obtain(req, installer)
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
      return installer(requirement)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
      return cmd.easy_install(req)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 664, in easy_install
      return self.install_item(spec, dist.location, tmpdir, deps)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 694, in install_item
      dists = self.install_eggs(spec, download, tmpdir)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 875, in install_eggs
      return self.build_and_install(setup_script, setup_base)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1114, in build_and_install
      self.run_setup(setup_script, setup_base, args)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1102, in run_setup
      raise DistutilsError("Setup script exited with %s" % (v.args[0],))
  distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

  ----------------------------------------
  Running setup.py bdist_wheel for pycparser: started
  Running setup.py bdist_wheel for pycparser: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/9b/f4/2e/d03e949a551719a1ffcb659f2c63d8444f4df12e994ce52112
Successfully built pycparser
Failed to build cryptography
Installing collected packages: idna, pyasn1, enum34, ipaddress, pycparser, cffi, cryptography
  Running setup.py install for cryptography: started
    Running setup.py install for cryptography: finished with status 'error'
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0XgEPM/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-059FZa-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/cryptography
    copying src/cryptography/fernet.py -> build/lib.linux-x86_64-2.7/cryptography
    copying src/cryptography/utils.py -> build/lib.linux-x86_64-2.7/cryptography
    copying src/cryptography/__init__.py -> build/lib.linux-x86_64-2.7/cryptography
    copying src/cryptography/exceptions.py -> build/lib.linux-x86_64-2.7/cryptography
    copying src/cryptography/__about__.py -> build/lib.linux-x86_64-2.7/cryptography
    creating build/lib.linux-x86_64-2.7/cryptography/x509
    copying src/cryptography/x509/general_name.py -> build/lib.linux-x86_64-2.7/cryptography/x509
    copying src/cryptography/x509/name.py -> build/lib.linux-x86_64-2.7/cryptography/x509
    copying src/cryptography/x509/base.py -> build/lib.linux-x86_64-2.7/cryptography/x509
    copying src/cryptography/x509/oid.py -> build/lib.linux-x86_64-2.7/cryptography/x509
    copying src/cryptography/x509/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/x509
    copying src/cryptography/x509/extensions.py -> build/lib.linux-x86_64-2.7/cryptography/x509
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat
    copying src/cryptography/hazmat/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/backends
    copying src/cryptography/hazmat/backends/interfaces.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends
    copying src/cryptography/hazmat/backends/multibackend.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends
    copying src/cryptography/hazmat/backends/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings
    copying src/cryptography/hazmat/bindings/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/cmac.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/keywrap.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/hmac.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/hashes.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/serialization.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/padding.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/constant_time.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/x509.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/backend.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/encode_asn1.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/ciphers.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/cmac.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/hmac.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/hashes.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/utils.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/decode_asn1.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/dsa.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/ec.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/rsa.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/commoncrypto
    copying src/cryptography/hazmat/backends/commoncrypto/backend.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/commoncrypto
    copying src/cryptography/hazmat/backends/commoncrypto/ciphers.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/commoncrypto
    copying src/cryptography/hazmat/backends/commoncrypto/hmac.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/commoncrypto
    copying src/cryptography/hazmat/backends/commoncrypto/hashes.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/commoncrypto
    copying src/cryptography/hazmat/backends/commoncrypto/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/commoncrypto
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/_conditional.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/binding.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/openssl
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/commoncrypto
    copying src/cryptography/hazmat/bindings/commoncrypto/binding.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/commoncrypto
    copying src/cryptography/hazmat/bindings/commoncrypto/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/commoncrypto
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/base.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/algorithms.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/modes.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/ciphers
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/hotp.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/totp.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/utils.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/twofactor
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/interfaces
    copying src/cryptography/hazmat/primitives/interfaces/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/interfaces
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/x963kdf.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/hkdf.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/concatkdf.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/pbkdf2.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/kbkdf.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/dh.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/utils.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/dsa.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/padding.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/ec.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/rsa.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    running egg_info
    writing requirements to src/cryptography.egg-info/requires.txt
    writing src/cryptography.egg-info/PKG-INFO
    writing top-level names to src/cryptography.egg-info/top_level.txt
    writing dependency_links to src/cryptography.egg-info/dependency_links.txt
    writing entry points to src/cryptography.egg-info/entry_points.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
    writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
    running build_ext
    generating cffi module 'build/temp.linux-x86_64-2.7/_padding.c'
    creating build/temp.linux-x86_64-2.7
    generating cffi module 'build/temp.linux-x86_64-2.7/_constant_time.c'
    generating cffi module 'build/temp.linux-x86_64-2.7/_openssl.c'
    building '_openssl' extension
    creating build/temp.linux-x86_64-2.7/build
    creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
    build/temp.linux-x86_64-2.7/_openssl.c:429:30: fatal error: openssl/opensslv.h: No such file or directory
     #include <openssl/opensslv.h>
                                  ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------

:stderr: /usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Failed building wheel for cryptography
  Failed cleaning build dir for cryptography
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0XgEPM/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-059FZa-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-0XgEPM/cryptography/
````

##### How can we reproduce this issue?

Run site.yml on a greenfield deployment

##### How can we verify your issue is addressed?

site.yml completes 

##### If you are using or know of a workaround please describe the necessary steps?

Manually install libffi-dev and libssl-dev

##### What is your evaluation on the importance of this issue, and why?

Workaround is simple but it's a manual step

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by sigmavirus24** [comment] 2016-08-02 15:29
This looks like pip-lockdown.yml wasn't run prior to running site.yml (or wasn't run for the hosts that site.yml targets). Is there pip configuration pointing to the repo mirror on those hosts?

**Comment by shane-c** [comment] 2016-08-02 16:19
I didn't run pip-lockdown.yml. Does that playbook need to be manually run? This is the order playbooks were run. 

setup-hosts.yml
setup-infrastructure.yml
setup-openstack.yml
site.yml

No limits were used on any playbooks. I think it is a problem with certain hosts being targeted by pip-lockdown.yml/site.yml, because compute/infra01 nodes don't run into this error, only infra02/infra03/logging/ceph storage nodes. infra02 has the following pip config.

````
root@infra02:~# cat .pip/pip.conf
[global]
no-index = True
pre = True
timeout = 120
trusted-host =
	172.29.24.10

[install]
upgrade = True
allow_all_external = True
find-links =
	http://172.29.24.10:8181/os-releases/12.0.17/
````

**Comment by sigmavirus24** [comment] 2016-08-02 18:44
I'm going to have to let @mancdaz answer whether or not that needs to be run separately. It looks as if he authored the playbook in question. It's surprising that you don't have a wheel of cryptography ready built in your repo mirror. It looks like we downloaded 1.4 from PyPI. I wonder if you could tell us which task this was part of. I wonder if require a newer version than what is built into the mirror.

**Comment by shane-c** [comment] 2016-08-02 18:57
The cryptography wheel is in the repo, but the apt packages libffi-dev and libssl-dev are not on the failing hosts for some reason, so pip install cryptography fails. 
````
root@infra01:~# curl -s http://172.29.24.10:8181/os-releases/12.0.17/ | grep cryptography
<a href="cryptography-1.1.2-cp27-none-linux_x86_64.whl">cryptography-1.1.2-cp27-none-linux_x86_64.whl</a><br />
````
A quick fix might be to add libffi-dev and libssl-dev to the list of packages we install in setup-hosts.yml.

**Comment by sigmavirus24** [comment] 2016-08-02 19:08
That's not how wheels work.

When we create the wheel file above, it will actually not then require those binary dependencies from the operating system in order to operate. Also, if you look closely at the logs you provided, pip *downloads* `cryptography-1.4.tar.gz` but the file in your wheel repo is `cryptography-1.1.2-cp27-non-linux_x86_64.whl`. Those are two completely different versions, files, and distributions.

Something else fishy is going on in your environment.

**Comment by sigmavirus24** [comment] 2016-08-02 19:10
Besides, adding those binary dependencies to every place cryptography *might* be installed will slow down the deployment, which is not the direction we're trying to head in.

**Comment by shane-c** [comment] 2016-08-02 19:14
Ah, I see. This has happened on a number of greenfield deployments, the last two I worked being the latest tagged release r12.2.1. I'm not sure what we could be doing that would produce this issue on multiple deployments.

**Comment by sigmavirus24** [comment] 2016-08-02 19:16
@shane-c Could you tell us what task was being executed when you saw this? Or what playbook even (on a finer grained level than `site.yml` since it just runs *other* playbooks)

**Comment by shane-c** [comment] 2016-08-02 19:28
I didn't grab the full output, sorry. I'm fairly certain it's within setup-maas.yml and specifically the "Install pip packages" task. On the next deployment I'll be sure we grab the full details.

**Comment by mancdaz** [comment] 2016-08-03 08:19
Yes, we added the pip-lockdown playbook in https://github.com/rcbops/rpc-openstack/commit/8a3a6aaa0af5212d37f77aa774f1ea1721531b5c to ensure consistent pip files across all hosts and containers.

We added a step to our deploy.sh and upgrade.sh scripts to ensure this playbook gets run:

https://github.com/rcbops/rpc-openstack/blob/liberty-12.2/scripts/deploy.sh#L163-L166
https://github.com/rcbops/rpc-openstack/blob/liberty-12.2/scripts/upgrade.sh#L49

I'm deploying an AIO with this step removed from the deploy script to see if I can reproduce this bug.

**Comment by mancdaz** [comment] 2016-08-03 09:31
I wasn't able to recreate this on an AIO, but thinking about it that stands to reason as it is the deployment host, and in your environment the deployment host is unaffected.

I do think though that it's likely the cause. I'd be interested to see the pip.conf from your infra03 since that's where you showed the error. If it has the same pip.conf as infra02 that you showed, then I'm confused as to how it is not installing the built cryptography-1.1.2 wheel from the repo, rather than going to pypi (which it would not do if it had the same pip.conf as infra02).

**Comment by sigmavirus24** [comment] 2016-08-03 12:35
@mancdaz would be good to compare the pip.conf files from infra0{2,3} with infra01 since this (maybe?) doesn't happen there.

**Comment by shane-c** [comment] 2016-08-03 16:42
All the pip.conf are the same. Since site.yml is the last playbook we run, I would think pip problems would pop up earlier when running infrastructure/openstack playbooks. I also don't see how the pip.conf file could have been modified after I ran into this error, unless pip-lockdown is run sometime after I installed the two missing packages, which it doesn't sound like it is. Is there a preferred time to run pip-lockdown.yml? My guess is after setup-hosts.yml would be ok, but want to make sure. 

````
root@infra01:/opt/rpc-openstack/openstack-ansible/playbooks# ansible -m shell os-infra_hosts -a "cat /root/.pip/pip.conf"

infra01 | success | rc=0 >>
[global]
no-index = True
pre = True
timeout = 120
trusted-host =
  172.29.24.10

[install]
upgrade = True
allow_all_external = True
find-links =
  http://172.29.24.10:8181/os-releases/12.0.17/

infra02 | success | rc=0 >>
[global]
no-index = True
pre = True
timeout = 120
trusted-host =
  172.29.24.10

[install]
upgrade = True
allow_all_external = True
find-links =
  http://172.29.24.10:8181/os-releases/12.0.17/

infra03 | success | rc=0 >>
[global]
no-index = True
pre = True
timeout = 120
trusted-host =
  172.29.24.10

[install]
upgrade = True
allow_all_external = True
find-links =
  http://172.29.24.10:8181/os-releases/12.0.17/
````

**Comment by shane-c** [comment] 2016-08-03 16:47
Just checked deploy.sh and it is run right after setup-hosts.yml. We'll modify this in our install steps and see if we run into this again.

**Comment by mancdaz** [comment] 2016-08-04 08:10
Thanks @shane-c. I'm going to get a multinode deploy up and running to recreate/test, to see if we can confirm the 'fix' before you run in to it again.

**Comment by mancdaz** [comment] 2016-08-04 09:56
One thing I noted, the ```bootstrap-ansible.sh``` script runs before any kind of lockdown. It installs cryptography 1.4 on the deployment host

```
# pip freeze|egrep 'cryptog|ffi'
cffi==1.7.0
cryptography==1.4
```

This is due to a requirement from ansible 1.9.4 on paramiko. This then collects cffi from that dependency chain.

```
Collecting cryptography>=1.1 (from paramiko->ansible==1.9.4)
  Downloading cryptography-1.4.tar.gz (399kB)
...
Collecting cffi>=1.4.1 (from cryptography>=1.1->paramiko->ansible==1.9.4)
  Downloading cffi-1.7.0-cp27-cp27mu-manylinux1_x86_64.whl (383kB)
```

This might at least explain the difference in cryptography versions on the deployment host versus other hosts.

**Comment by sigmavirus24** [comment] 2016-08-04 11:49
@mancdaz that does make sense as to why infra01 (the typical deployment host) doesn't have this problem. What is the "fix" you're testing though? I really think we should *not* be installing those apt-packages and allowing cryptography to compile itself for those hosts. That *will* degrade the experience for installations or upgrades.

**Comment by mancdaz** [comment] 2016-08-04 13:14
@sigmavirus24 I want to recreate the fail by 'not' running the pip-lockdown play that we do run in deploy.sh. Then I want to ensure that actually running it in the correct place makes this issue go  away - at which point it's a doc/process issue that can be updated.

**Comment by mancdaz** [comment] 2016-08-04 13:16
just to clarify, that would mean that all the hosts get a proper pip.conf and install cryptography and anything else using the wheels from the repo, which is the correct approach

**Comment by mancdaz** [comment] 2016-08-04 15:31
OK so I was able to reproduce this error if I did *not* run ```rpcd/playbooks/pip-lockdown.yml```

As expected though, by not running that playbook I had no ```pip.conf``` at all on my infra0{2,3} hosts (hence the reason cryptography-1.4 is being downloaded from pypi), so I'm still confused as to where your pip.conf on those hosts came from @shane-c.

When I ran pip-lockdown, and then re-ran site.yml (actually setup-maas.yml), all hosts got a correct pip.conf, and were therefore able to install cryptography-1.1.2 using the built wheel from the repo

**Comment by mancdaz** [comment] 2016-08-05 08:43
@shane-c given that the [documentation details using the deploy.sh script](https://github.com/rackerlabs/docs-rpc/blob/master/internal/rpc-install/ch-playbooks-rpc.rst#running-the-rpco-deployment-script), which would ensure that you wouldn't encounter this issue, there's not much else I can do to fix the docs or the code to account for what you experienced.

If you are able to use the ```deploy.sh``` script in your deployments, that would be best since that is what is tested. Other than that, if you can please confirm that you have adjusted your own manual deployment steps to accommodate the requirement of running ```pip-lockdown.yml``` at the correct point, then we can get this issue closed off. Thanks!

**Comment by shane-c** [comment] 2016-08-05 14:54
Thanks @sigmavirus24 and @mancdaz for help with this. We've adjusted our install steps. The problem with using deploy.sh is it will never be a fully automated install for us because we rely on an F5 config for our deployments. If/When deploy.sh can automate an F5 configuration (maybe using the F5 API), running each playbook gives us more control and insight if/when a playbook fails for whatever reason. If the order of playbooks run is modified that needs to be documented/communicated outside of just the code/deploy.sh. I couldn't find any references to running pip-lockdown.yml in the RPC-O docs (README.md) on GitHub or our internal documentation.

**Comment by mancdaz** [comment] 2016-08-08 10:51
Hi @shane-c - can you point me to the internal docs that you use where it documents the broken out steps so I can see where we might need to update it. As I said, the docs I looked at suggest using deploy.sh so if there is a large gap there then we need to close it.

**Closed** 2016-08-09 15:32 UTC
Labels: impacts-support, prio-2, status-needs-information, swimlane-rr, type-bug
