### ISSUE TITLE
J > N Leap Frog Upgrade: Neutron router port migration breaks

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1771] opened 2017-02-01 15:55 UTC
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

See https://bugs.launchpad.net/neutron/+bug/1484290

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

This a reminder when we are working on J to N upgrades that we have an unfixed DB migration issue in neutron and we may have to supplement that with our own migration process.

Details are inside See https://bugs.launchpad.net/neutron/+bug/1484290

##### What is actually happening?

https://bugs.launchpad.net/neutron/+bug/1484290
##### How can we reproduce this issue?

N/A

##### How can we verify your issue is addressed?

See https://bugs.launchpad.net/neutron/+bug/1484290

##### If you are using or know of a workaround please describe the necessary steps?

See https://bugs.launchpad.net/neutron/+bug/1484290

##### What is your evaluation on the importance of this issue, and why?

Prio 2 
----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] newton-14.0

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [x] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [x] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by cloudnull** [comment] 2017-02-01 18:07
++ good issue to track so that we're aware of what can / will happen though at the moment I'm not sure how we'd mitigate it?  All juno environments will have that issue and the root cause was never resolved upstream. We could document this as a risk and see if we can identify the root cause and mitigate it, or catalog the ports and recreate them should any be missing.

I'm definitely open to suggestions?

**Comment by cloudnull** [comment] 2017-04-22 00:09
I am closing this issue as Juno is no longer a concern for leapfrog upgrades.

**Closed by cloudnull** 2017-04-22 00:09 UTC
Labels: prio-2, swimlane-improvements2, type-undecided
