### ISSUE TITLE
Holland broken in Liberty

### ISSUE THREAD

**Issue by JCallicoat** [rcbops/rpc-openstack#1121] opened 2016-06-07 05:36 UTC
##### What version (commit) do you encounter this issue on?

r12.1.0 (two separate environments both on same version)

##### What type of issue is this (bug, feature, documentation, regression)?

Bug

##### What is the expected behavior?

The "holland bk" command works

##### What is actually happening?

So, there are a few issues here.

Firstly, for some reason the rpc_support database users / grants were not created in these environments, even though it appears the rpc_support playbook was run. Since we set `run_once: true` for the `Create rpc_support backup user` task, any subsequent runs will skip the task and the user will never be created. This may be more of an operational issue -- maybe the play was run with some set of tags limiting it or something like that (will follow up on my end with deployments team). But there is no harm in letting the task run every time, so the `run_once` should probably be removed.

----

Secondly, the holland bk command fails to find `innobackupx` unless the full path is given in the config file (/etc/holland/backupsets/rpc_support.conf), even though it's in /usr/bin and that is in the PATH.
```
# holland bk
[...snip...]
Backup failed: Failed to find innobackupex script
```
Setting `innobackupex = /usr/bin/innobackupex` resolves this error.

----

Lastly, after setting `innobackupx` another error pops up
```
# holland bk
[...snip...]
    ! xtrabackup: error: compressed and encrypted backups are incompatible with the
    ! 'tar' streaming format. Use --stream=xbstream instead.
```
Setting `stream = xbstream` allows holland to successfully complete the backup.

----

I suspect that some defaults changed in xtrabackup that now require these options to be set explicitly.

##### How can we reproduce this issue?

Run holland bk from a galera container

##### How can we verify your issue is addressed?

Verify backup is created at /var/backup/holland_backups/rpc_support/ in galera container

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

Support manually create DB user and grants (as needed), manually edit config file template (always needed until bug is fixed).

##### What is your evaluation on the importance of this issue, and why?

Very high. Running without any DB backups is bad.

###### Remove branches (lines) you do not wish to target.
- [x] Master (https://github.com/rcbops/rpc-openstack/pull/1122)
- [x] liberty-12.2 (https://github.com/rcbops/rpc-openstack/pull/1136)
- [x] liberty-12.1 (https://github.com/rcbops/rpc-openstack/pull/1137)
- [x] kilo (https://github.com/rcbops/rpc-openstack/pull/1160)

**Comment by mancdaz** [comment] 2016-06-07 09:08
Hi @JCallicoat - thanks for reporting, and for the extra detail!

The issue with user creation is actually slightly different. ```run_once``` doesn't just run the task once ever and then never again - it evaluates the list of hosts in the play, and will run it only for the first host in the list - each and every time that play is run.

What's actually happening here is that the list of hosts for the rpc_support play is 'all_containers'. But then in main.yml we only call the holland_config play if the containers are in the galera group. A double evaluation happens, meaning the first host in the list (i.e. the one that ```run_once``` chooses) is actually the host, and not one of the galera containers. The second part of the evaluation ("am I in the galera group"?) then happens, the answer is no and that host gets skipped. So the task never gets run.

This issue was introduced in commit 607c284a21d3f128c0d1eba0debaf99e7951c377 to fix this issue https://github.com/rcbops/rpc-openstack/issues/556

The way the OSA playbooks handle this upstream is to move the db grants into a separate playbook task, and then only include that task when the host is the first of the group (in this case galera[0]). e.g.:

https://github.com/openstack/openstack-ansible-os_nova/blob/master/tasks/main.yml#L28-L30

The other parts of your issue can be resolved with simple template changes.

**Comment by mancdaz** [comment] 2016-06-08 08:55
@hughsaunders can we please add a test in the gate to check that a holland backup passes to ensure we don't regress on this again.
@tbyrom138 It's probably worth adding something to the QE tests too, if they are different

**Comment by tbyrom138** [comment] 2016-06-08 13:54
Noted!  Appreciate the heads up @mancdaz.  Nothing different yet as far as our testing; however, QE has already planning out work to creating new tests to increase our test scope. So definitely worth noting.

**Comment by b3rnard0** [comment] 2016-06-09 18:50
@hughsaunders Why was this issue closed if we have open pull requests?

**Comment by mancdaz** [comment] 2016-06-09 19:21
@b3rnard0 my fault for using 'fixes' in the pr. Github closed it automatically

**Comment by git-harry** [comment] 2016-06-10 13:44
All RPCO pull requests have merged. There is an open pull request on jenkins-rpc to enable testing for holland, I'm leaving open the issue while that is completed.

**Comment by git-harry** [comment] 2016-06-14 13:45
https://github.com/rcbops/jenkins-rpc/pull/593 has now merged and so testing is now in place.

**Comment by hughsaunders** [comment] 2016-06-17 08:34
Holland testing was removed as it was failing. It was failing because its testing the latest kilo tag, and we haven't tagged since @mancdaz's fix for holland went into kilo. Holland testing will be re-enabled once we have a new kilo tag. So this issue is blocked on a kilo release.

**Comment by b3rnard0** [comment] 2016-06-23 00:32
The state of this issue is confusing? Is it still blocked and still a prio-1 issue?

**Comment by mancdaz** [comment] 2016-06-23 10:05
@b3rnard0 the issue is fixed in all branches. It's only being held open pending the test for regression being added to the gating.

I have opened https://github.com/rcbops/jenkins-rpc/issues/600 to track the gating work, so am closing this issue off.

**Closed by mancdaz** 2016-06-23 10:05 UTC
Labels: impacts-gating, impacts-support, prio-1, status-blocked, type-bug
