### ISSUE TITLE
OSA Galera Race condition fix for Liberty upgrades

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1271] opened 2016-07-29 20:29 UTC
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

The galera database can fall down during Liberty upgrades and it needs to be manually fixed in order to continue upgrades.
The primary reason for that seems to be that the containers are booted in the wrong order, not maintaining quorum.

##### What is actually happening?

setup-galera.yml fails during container/mysql restart

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

Worst case rm -rf /var/lib/mysql/* two out of three nodes to rebuild the cluster due to the xtrabackup and SST bug. After that I restart setup-galera.yml with -e 'galera_upgrade=true'

##### How can we reproduce this issue?

Issue is being fixed at OSA via https://review.openstack.org/#/c/347195/

##### How can we verify your issue is addressed?

No more forced galera cluster tear downs during Liberty upgrade 

##### If you are using or know of a workaround please describe the necessary steps?

See above 

##### What is your evaluation on the importance of this issue, and why?

Critical

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] liberty-12.2

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [x] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [x] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [x] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by git-harry** [comment] 2016-08-01 07:37
This is a duplicate of https://github.com/rcbops/rpc-openstack/issues/1201

@BjoernT the section in the description, below the line, is used to record the actions taken when resolving the problem. It is intended to be completed by the dev assigned to work on the issue. Please do not fill it in when creating a new issue.

**Closed by git-harry** 2016-08-01 07:37 UTC
