### ISSUE TITLE
os_magnum task errors on 'unsupported parameter for module: checksum'

### ISSUE THREAD

**Issue by shane-c** [rcbops/rpc-openstack#1694] opened 2017-01-20 05:35 UTC
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

git describe --all
r13.1.3

##### What type of issue is this? Please tick the appropriate box.
- [x ] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

os-magnum-install.yml completes with no errors

##### What is actually happening?

TASK: [os_magnum | Attempt venv download] *************************************
failed: [shane-mitaka_magnum_container-fd88d6df] => {"failed": true}
msg: unsupported parameter for module: checksum

FATAL: all hosts have already failed -- aborting

The checksum parameter was added in Ansible 2.0 according to http://docs.ansible.com/ansible/get_url_module.html. r13.1.3 is on ansible 1.9.6. 

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

Running deploy.sh with DEPLOY_MAGNUM:-"yes"

##### How can we reproduce this issue?

Run deploy.sh with DEPLOY_MAGNUM:-"yes" or run os-magnum-install.yml

##### How can we verify your issue is addressed?

os-magnum-install.yml completes with no errors

##### If you are using or know of a workaround please describe the necessary steps?

I commented out the checksum parameter in the Attempt venv download/get_url task, located in /etc/ansible/roles/os_magnum/tasks/install.yml

root@shane-mitaka:/etc/ansible/roles/os_magnum/tasks# grep checksum install.yml
    #checksum: "sha1:{{ lookup('url', magnum_venv_download_url | replace('tgz', 'checksum')) }}"

Rerun deploy.sh or os-magnum-install.yml, it completed without error after adding the comment.

##### What is your evaluation on the importance of this issue, and why?

Low

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.1
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by alextricity25** [comment] 2017-01-20 14:19
cc @chrishultin

**Comment by chrishultin** [comment] 2017-01-20 16:20
This is in the upstream 'openstack-ansible-os_magnum' repo - I'm not sure how we want to go about fixing this.

**Comment by odyssey4me** [comment] 2017-01-20 16:28
The issue is that you're trying to use a version of Ansible that differs from the upstream version. My suggestion is to fork the upstream repo, create a Mitaka branch and make the necessary adjustments in the rcbops fork to support the Mitaka version of Ansible properly. I don't see any other way of doing this that would not compromise the upstream development and maintenance process.

**Comment by chrishultin** [comment] 2017-01-20 20:58
cc @claco @major @mancdaz 
Can any of you fork openstack-ansible-os_magnum?

**Comment by chrishultin** [comment] 2017-01-23 18:09
See https://github.com/rcbops/rpc-openstack/pull/1720

**Comment by chrishultin** [comment] 2017-02-06 17:16
Merged

**Closed by chrishultin** 2017-02-06 17:16 UTC
Labels: prio-3, swimlane-misc, type-bug

**Comment by shane-c** [comment] 2017-02-10 04:38
I'm still seeing this in r13.1.4.

```
root@infra01:/opt/rpc-openstack# git describe --tags
r13.1.4

root@infra01:/opt/rpc-openstack# grep checksum /etc/ansible/roles/os_magnum/tasks/install.yml
    checksum: "sha1:{{ lookup('url', magnum_venv_download_url | replace('tgz', 'checksum')) }}"
```
Errors at the same spot as original post.
