### ISSUE TITLE
maas_excluded_devices not working inside rpcd/playbooks/roles/rpc_maas/tasks/local.yml

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#708] opened 2016-01-06 20:13 UTC
Regardless of the configuration for maas_excluded_devices, all block devices are installed inside MAAS as a separate alarm. I provide a possible workaround since it seems it's a ansible/jinja issue

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by BjoernT** [comment] 2016-01-06 20:17
I collapsed this for kilo 11.0 versions to 

diff --git a/rpcd/playbooks/roles/rpc_maas/tasks/local.yml b/rpcd/playbooks/roles/rpc_maas/tasks/local.yml
index 9003e63..a9d4e9a 100644
--- a/rpcd/playbooks/roles/rpc_maas/tasks/local.yml
+++ b/rpcd/playbooks/roles/rpc_maas/tasks/local.yml
@@ -357,14 +357,13 @@

 - include: local_setup.yml
   vars:
-    devices: "[{% for device in ansible_devices.keys()%}{% if device not in maas_excluded_devices|default([]) %}'{{ device }}',{% endif %}{% endfor %}]"
     check_name: disk_utilisation
     check_details: file={{ check_name }}.py
     check_period: "{{ maas_check_period }}"
     check_timeout: "{{ maas_check_timeout }}"
     # TODO (mattt): refactor this code so we can properly create dynamic alarms
     #               without using jinja
-    alarms: "[{% for device in devices %}{ 'name': 'percentage_disk_utilisation_{{ device }}', 'criteria': ':set consecutiveCount={{ maas_alarm_local_consecutive_count }} if (
+    alarms: "[{% for device in ansible_devices.keys() if (device not in maas_excluded_devices|default([])) and (ansible_devices[device].model != 'VIRTUAL-DISK') %}  { 'name':
   user: root
   when: >
     inventory_hostname in groups['hosts']

I need to recheck if that is still an issue for 11.1.x

**Comment by prometheanfire** [comment] 2016-03-02 20:43
if you could verify the fix let me know

**Comment by BjoernT** [comment] 2016-03-02 20:52
Yes I have to test it again with the latest maas plugins.
It was related to https://github.com/rcbops/rpc-openstack/issues/708 where the excluded device override did not work and both are in the same alarm condition

**Comment by mancdaz** [comment] 2016-06-13 09:29
@BjoernT do you have a PR you'd like to submit for this issue?

**Comment by BjoernT** [comment] 2016-06-13 14:03
Yeah I had before the restructuring of MAAS, let have a quick look since I think we still have the same issue

**Comment by mancdaz** [comment] 2016-08-01 13:23
@BjoernT ping

**Comment by mancdaz** [comment] 2016-08-02 13:37
Having looked more into this, it seems the issue is explicitly referring to the fact that ```maas_excluded_devices``` was being ignored. ```maas_excluded_devices``` was fixed as a part of the following PRs:

kilo: https://github.com/rcbops/rpc-openstack/pull/1256
liberty: https://github.com/rcbops/rpc-openstack/pull/1250
master: https://github.com/rcbops/rpc-openstack/pull/1241

Therefore I am going to close this issue. If there is a different problem here, please open a new bug report with appropriate levels of detail for us to investigate.

**Closed by mancdaz** 2016-08-02 13:37 UTC
Labels: prio-2, status-doing, swimlane-rr, type-bug
