### ISSUE TITLE
RabbitMQ run_queue length race condition leads to false positive alerts

### ISSUE THREAD

**Issue by cfarquhar** [rcbops/rpc-openstack#726] opened 2016-01-13 14:14 UTC
In busy environments, we see frequent false alarms from this check [1].  The theory is that there is a race condition where not all messages have been replicated when the environment is under load.  Is there a better way to check for cluster health?

[1] https://github.com/rcbops/rpc-openstack/blob/master/maas/plugins/rabbitmq_status.py#L160-L165

**Comment by hughsaunders** [comment] 2016-01-15 13:36
Hi @cfarquhar I don't think this is due to a replication problem. I think its more fundamental, according to http://www.erlang.org/doc/man/erlang.html#statistics-1 run_queue is the number of processes waiting to run within the erlang environment - a load metric, nothing to do with the number of messages in a rabbit queue, and will vary according to the load on each host. 

Closing as a duplicate of #626

**Closed by hughsaunders** 2016-01-15 13:36 UTC
