### ISSUE TITLE
os-neutron install fails from Kilo to Liberty

### ISSUE THREAD

**Issue by b3rnard0** [rcbops/rpc-openstack#1228] opened 2016-07-07 18:53 UTC
Tracking of the following OSA bug: 

https://bugs.launchpad.net/openstack-ansible/+bug/1577799

**Comment by git-harry** [comment] 2016-07-14 10:31
Duplicate of https://github.com/rcbops/rpc-openstack/issues/1134

**Closed by git-harry** 2016-07-14 10:31 UTC
Labels: impacts-onboarding, osa-tracking, prio-wishlist, status-duplicate
