### ISSUE TITLE
Add default flavor fail

### ISSUE THREAD

**Issue by Frank-ZhangXin** [rcbops/rpc-openstack#2060] opened 2017-03-20 16:15 UTC
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
'Add default flavor' task should make its goal successfully.
##### What is actually happening?
We have ran into this issue at least twice on lem lab at the end of support role installment. 
Simply, 'Add default flavor' would hang forever and never ends.

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
Deploying RPC-O on lem lab with 10 nodes scale.

##### How can we reproduce this issue?
Test a deployment on physical environment or testing AIO.

##### How can we verify your issue is addressed?
'Add default flavor' won't hang forever and the default flavor should be created indeed.

##### If you are using or know of a workaround please describe the necessary steps?
No workaround so far. Or disable this task.

##### What is your evaluation on the importance of this issue, and why?
prio-1, it's very important to fix because it affect master on RPC-O

##### Some fact worth to be considered
Strange python related log found at this step:
```
container_name: "infra02_utility_container-01045dbc"
physical_hostname: "infra02"
Container confirmed
container_name: "infra02_utility_container-01045dbc"
physical_hostname: "infra02"
Container confirmed
<172.16.40.12> ESTABLISH SSH CONNECTION FOR USER: root
<172.16.40.12> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi
-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=5 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ServerAliveInterval=64 -o ServerAliveCount
Max=1024 -o Compression=no -o TCPKeepAlive=yes -o VerifyHostKeyDNS=no -o ForwardX11=no -o ForwardAgent=yes -T -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r 172.16.40.12 'lxc-attach --nam
e infra02_utility_container-01045dbc -- /bin/sh -c '"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python && sleep 0'"'"''
```

Shade has been confirmed installed on utility container as promise. I once doubt ansible os_nova_flavor module. The script looks good so far: https://github.com/ansible/ansible-modules-core/blob/stable-2.1/cloud/openstack/os_nova_flavor.py

Create default flavor task:
https://github.com/rcbops/rpc-openstack/blob/master/rpcd/playbooks/roles/rpc_support/tasks/create_default_flavors.yml

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [] master

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by alextricity25** [comment] 2017-03-20 16:22
@Frank-ZhangXin Please use the issue template when reporting bugs in RPCO. The questions on the template should be answered to the best of your ability. Thanks!

**Comment by Frank-ZhangXin** [comment] 2017-03-20 16:22
@alextricity25 sure thing, will correct soon.

**Comment by claco** [comment] 2017-03-20 18:40
@alextricity25 @Frank-ZhangXin @mattt416 @hughsaunders Is this role run all the time, and in gating? @jacobwagner is this role run in QE as part of the deploy?

Trying to devine where it's broken for some folks and not others. 

Ultimately, this was a role @BjoernT and group started creating to gradually move their support specific things into. Is this still the case?

Trying to figure out if this is actually a bug, in terms of QE testing and RC for 14.0, or not.

**Comment by BjoernT** [comment] 2017-03-20 19:54
The flavors installed for me and yes it is destined to be removed from rpc-o, I was working on some support venvs stuff in our openstack-ops so I can move it now.
Unfortunately this output posted here contains no actual error, only the preliminary debugging output. Do you still have the log @Frank-ZhangXin ?

**Comment by Frank-ZhangXin** [comment] 2017-03-21 14:40
@BjoernT hey, man, thanks for feedback. The fact is that there's no actual error log, the deployment progress just frozen at 'Add default flavor' step. The only meaningful info during this part is what I paste in report. And I know it looks nothing related and no help.

**Comment by BjoernT** [comment] 2017-03-21 15:16
OK that would indicate either a python problem inside the container or the shade library is not able to talk to the openstack api

**Comment by cloader89** [comment] 2017-03-24 16:15
@Frank-ZhangXin QE did not have this error, so we decided its a non-issue

**Comment by prometheanfire** [comment] 2017-03-28 21:09
So, labs are setting up the SSL profile on the public ssl profiles.  The missing link between the profile and the ssl cert is breaking the nat hairpin cauing public api access from within the lab to fail.

This is not a problem with the f5 config we generate (confirmed with the networking team) but seems to be a problem with how the f5_tmsh.py is setting up the profiles.  I've bugged dennis since it was originally his code, but it's not looking good.

The simple fix for this is to set the `endpoint_type: 'internal'` parameter for the flavor creation.

**Comment by alextricity25** [comment] 2017-03-28 21:36
That seems like a reasonable fix. Thanks @prometheanfire.

**Comment by cloudnull** [comment] 2017-04-22 16:19
A PR has been added to resolve this issue based on the feedback from @prometheanfire.

**Comment by evrardjp** [comment] 2017-04-27 08:11
Fails for me.

**Comment by alextricity25** [comment] 2017-04-27 13:04
@evrardjp Are you running into https://github.com/rcbops/rpc-openstack/issues/2227?

**Comment by evrardjp** [comment] 2017-04-28 12:39
@alextricity25 It should be fixed now. Can we close this?

**Comment by alextricity25** [comment] 2017-04-28 15:07
@evrardjp Once the assignee is confident this is fixed in all appropriate branches, then it should close. cc @cloudnull

**Comment by BjoernT** [comment] 2017-07-13 14:29
Closing since we move the rpc-support role to the openstack-ops module at https://github.com/rsoprivatecloud/openstack-ops and addressed this issue before that, by not using shade

**Closed by BjoernT** 2017-07-13 14:29 UTC
Labels: impacts-newton, swimlane-rr, type-bug
