### ISSUE TITLE
Monitoring for MariaDB status needed

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1164] opened 2016-06-15 18:04 UTC
##### What version (commit) do you encounter this issue on?

All

##### What type of issue is this (bug, feature, documentation, regression)?

Feature

##### What is the expected behavior?

No more "my number of session hit max_connection setting" situations

##### What is actually happening?

MariaDB and it's health is virtually unmonitored

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

We need to monitor important status parameters like

- Current Number of DB sessions in relation to max_connection setting
- Max_used_connections in relation to max_connection setting
- Open_files < open file limit
- Innodb_row_lock_time_avg < 5000 ?
- Innodb_deadlocks = 0
- Aborted_clients < 1/s
- Aborted_connects < 1/s
- Access_denied_errors = 0

##### How can we reproduce this issue?

-

##### How can we verify your issue is addressed?

Above checks are implemented

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?
-

##### What is your evaluation on the importance of this issue, and why?

-

###### Remove branches (lines) you do not wish to target.
- [x] Master
- [x] liberty-12.2

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [x] No documentation required for this change

**Comment by git-harry** [comment] 2016-06-15 19:23
@BjoernT there is an [existing database plugin][1] and [alarms][2] are raised for some of the metrics it generates, are you aware of this? On the face of it, this setup seems to cover some of your request. How do the connection alarms that exist relate to your description of the expected behaviour?

[1]: https://github.com/rcbops/rpc-openstack/blob/master/maas/plugins/galera_check.py
[2]: https://github.com/rcbops/rpc-openstack/blob/master/rpcd/playbooks/roles/rpc_maas/templates/galera_check.yaml.j2

**Comment by sigmavirus24** [comment] 2016-06-20 14:41
In today's bug triage, we discussed that we might need to add some more metrics/alarms based on @BjoernT's original report.

We need more information around:

- thresholds for alarms
- which metrics aren't presently being provided by the current galera plugin
- whether the customer in question even had MaaS enabled

**Comment by BjoernT** [comment] 2016-06-20 23:04
Added thresholds for the last two alarms

**Comment by claco** [comment] 2016-06-21 00:56
Thanks @BjoernT !

**Comment by b3rnard0** [comment] 2016-07-06 16:40
- [ ] Reproduce the issue. (N/A)
- [ ] Create a PR for fix and/or docs.
- [ ] Incorporate feedback from pull request reviews.
- [ ]  What is the gating for this on DEV and/or QE? Add related gating if appropriate. Also make sure current gating passes with this fix.
- [ ] Reach out to reporter to determine if the fix is resolving the issue.
- [ ] What are the upgrade impacts (if any).
- [ ] What are the backports are needed (if any).

**Comment by alextricity25** [comment] 2016-07-15 03:02
@BjoernT 
"Current Number of DB sessions in relation to max_connection setting"
Cloud you provide a little more insight as to what exactly you are wanting to monitor here? It seems very similar to the point you listed after that:
"Max_used_connections in relation to max_connection setting"

Thanks!

**Comment by BjoernT** [comment] 2016-07-15 15:52
Basically current number of sessions , max_used_connections < max_connections limit

**Comment by alextricity25** [comment] 2016-07-15 19:11
@BjoernT that already seems to be implemented in the plugin here[1]. 
Did you have anything else in mind? Or is this alarm fine? If it's fine we can just add alarms for the remaining points you mentioned above.

[1] https://github.com/rcbops/rpc-openstack/blob/master/rpcd/playbooks/roles/rpc_maas/templates/galera_check.yaml.j2#L26-L36

**Comment by BjoernT** [comment] 2016-07-15 19:13
Yes when you look at the description, we need to verify which metrics we are checking, I got more listed like deadlocks etc

**Comment by alextricity25** [comment] 2016-07-17 19:10
@BjoernT @sigmavirus24 
"Aborted_clients < 1/s
Aborted_connects < 1/s"
These checks might be a little harder to implement, since the each check is done, by default, every 60 seconds. MariaDB also doesn't provide this status variable as a rate of change, but as cumulative value as far as I know.
I could do something with the "Uptime" status variable. I could divide the Uptime with the number of aborted clients, then set a threshold. That way we get the average number of aborted clients relative to the uptime. The tricky part is figuring out a good threshold. If we keep the threshold at 1, then just keep in mind that it will take a while for Uptime/aborted_clients to equal 1 and MaaS won't ever pick up the *exact* moment aborted_clients > 1/s.
Thoughts?

**Comment by alextricity25** [comment] 2016-07-18 15:03
F.Y.I - PR is up #1242.

Still trying to figure out what the best threshold for Innodb_row_lock_time_avg could be. I'm doing research on this now.

**Comment by BjoernT** [comment] 2016-07-18 18:36
I would actually capture the rate in a small pickle database and then divide it by the time difference  to get per second growth. Using uptime will ruin the results

**Comment by alextricity25** [comment] 2016-07-18 19:33
@BjoernT It looks like the rate function modifier does what I want[1]:
https://developer.rackspace.com/docs/rackspace-monitoring/v1/developer-guide/#constructs-with-function-modifiers

**Comment by BjoernT** [comment] 2016-07-18 20:16
@alextricity25 Yepp looks good

**Comment by alextricity25** [comment] 2016-07-19 00:08
PR #1242 ready for review and feedback.

**Comment by alextricity25** [comment] 2016-07-27 15:10
PR #1242 ready for another look.

**Comment by alextricity25** [comment] 2016-07-27 21:35
This has merged in master. Now waiting for checks to pass for the liberty-12.2 backport. #1269

**Comment by alextricity25** [comment] 2016-07-28 17:09
Features have been added and backported to liberty12-2. I'm closing this.

**Closed** 2016-07-28 17:09 UTC
Labels: feature-monitoring, impacts-support, prio-3, status-needs-review, swimlane-rr, type-enhancement-small
