### ISSUE TITLE
12.0.10 pip wheel repo missing in rpc-repo.rackspace

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/rpc-openstack#998] opened 2016-04-14 21:14 UTC
##### What version (commit) do you encounter this issue on?

12.1.0rc2
##### What type of issue is this (bug, feature, documentation, regression)?

bug
##### What is the expected behavior?

12.0.10 repo directory has all required packages on repo container
##### What is actually happening?

12.0.10 repo is empty
##### How can we reproduce this issue?

upgrade a non locally built repo cluster, when galera tries to upgrade the pip package install will fail
##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

make sure all osa sha bumps have their respective repositories in rpc-repo.rackspace on tag cut
##### What is your evaluation on the importance of this issue, and why?

prio-1, without this repo all rpc tags that require rpc-repo.rackspace to clone repo will fail to upgrade / deploy
###### Remove branches (lines) you do not wish to target.
- [ ] Master
- [ ] liberty-12.1

```
TASK: [galera_client | Install galera packages] *******************************
changed: [node98_galera_container-c1fa9c22] => (item=libaio1,libc6,libdbd-mysql-perl,libgcc1,libgcrypt11,libmariadbclient-dev,libstdc++6,mariadb-client)

TASK: [galera_client | UnInstall system xtrabackup packages] ******************
changed: [node98_galera_container-c1fa9c22] => (item=percona-xtrabackup,xtrabackup)

TASK: [galera_client | Install galera package] ********************************
changed: [node98_galera_container-c1fa9c22]

TASK: [galera_client | Install pip packages] **********************************
failed: [node98_galera_container-c1fa9c22] => (item=MySQL-python) => {"attempts": 5, "cmd": "/usr/local/bin/pip install --force-reinstall MySQL-python", "failed": true, "item": "MySQL-python"}
msg: Task failed as maximum retries was encountered
failed: [node98_galera_container-c1fa9c22] => (item=python-memcached) => {"attempts": 5, "cmd": "/usr/local/bin/pip install --force-reinstall python-memcached", "failed": true, "item": "python-memcached"}
msg: Task failed as maximum retries was encountered
failed: [node98_galera_container-c1fa9c22] => (item=pycrypto) => {"attempts": 5, "cmd": "/usr/local/bin/pip install --force-reinstall pycrypto", "failed": true, "item": "pycrypto"}
msg: Task failed as maximum retries was encountered

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
repo_build | Create OpenStack global requirements wheels -------------- 489.20s
repo_build | Create role based venv ----------------------------------- 331.27s
repo_build | Create OpenStack-Ansible requirement wheels -------------- 207.12s
repo_build | Create venv archive --------------------------------------- 67.03s
repo_build | Clone all upstream git repositories ----------------------- 59.38s
galera_client | Add galera repo(s) ------------------------------------- 45.11s
galera_client | Install pip packages ----------------------------------- 43.67s
repo_build | Move wheels into place and ensure permissions ------------- 38.06s
repo_build | Create release pool links --------------------------------- 32.10s
repo_build | Create general index links -------------------------------- 31.72s
           to retry, use: --limit @/root/setup-infrastructure.retry

node101                    : ok=42   changed=11   unreachable=0    failed=0
node84_galera_container-7dc45552 : ok=4    changed=1    unreachable=0    failed=0
node84_memcached_container-755d8f50 : ok=7    changed=1    unreachable=0    failed=0
node84_repo_container-705a4061 : ok=55   changed=17   unreachable=0    failed=0
node89_galera_container-fb52200c : ok=4    changed=1    unreachable=0    failed=0
node89_memcached_container-c6bec69c : ok=7    changed=1    unreachable=0    failed=0
node89_repo_container-658ca21f : ok=55   changed=17   unreachable=0    failed=0
node98_galera_container-c1fa9c22 : ok=23   changed=10   unreachable=0    failed=1
node98_memcached_container-2b0a0a17 : ok=7    changed=1    unreachable=0    failed=0
node98_repo_container-5df16494 : ok=100  changed=48   unreachable=0    failed=0
```

```
root@node84_repo_container-705a4061:/var/www/repo/os-releases/12.0.10# ls -al
total 8
drwxr-sr-x  2 nginx www-data 4096 Apr 14 18:28 .
drwxr-sr-x 35 nginx www-data 4096 Apr 14 18:28 ..
```

**Comment by d34dh0r53** [comment] 2016-04-14 22:13
The directory exists now, so you should be good to go.  @jacobwagner or someone else from QE can you please update this with your status?

**Comment by b3rnard0** [comment] 2016-04-14 22:18
@jpmontez BTW, we hope to have r12.1.0rc3 tomorrow morning if you wanted to continue testing with @jacobwagner out.

**Comment by odyssey4me** [comment] 2016-04-15 09:11
In Mitaka we changed what happens here as the process as it stands doesn't make much sense. I don't know if this is something you'd like to propose as a backport for Liberty, but take a peek at the commit message and give it some thought. https://github.com/openstack/openstack-ansible/commit/3cdac57fc817e8e7bfed7a5fecb38baa66fe9e86

For Liberty, given that it's stable, it may be best to just leave things as they are and ensure that the rpc-repo is updated after every OSA tag?

**Comment by git-harry** [comment] 2016-04-15 10:15
We're now doing a repo build instead of a clone, is this still needed on rpc-repo?

**Comment by odyssey4me** [comment] 2016-04-15 12:37
@git-harry Given the issue report, apparently so - but not for the repo bits, only for the pip install bits. It's a bit confusing to me because there is an intentional  set of steps to cater for failure:

1. try and get the stuff from the repo - it tries using both the local and the upstream (rpc-repo) repo
2. if that fails, then ignore the failure and fall back to an isolated install which does not use the repo

Given the steps above, it is confusing that the issue is occurring and it'd be great if it can be replicated and a root cause found.

**Comment by BjoernT** [comment] 2016-06-07 19:26
I thought we got rid of the rpc-release repos on the repo container with Liberty and onwards and pull the pips externally. Where do we get all the pip for RPC-O from now ?

**Comment by git-harry** [comment] 2016-06-08 09:10
@BjoernT in Kilo the repo_build process is run twice, once for OSA and once for RPCO. Liberty has combined them so that when the repo_build playbook is run for OSA it creates a repo that includes the packages required by RPCO. The variable pkg_locations is overridden [1] to make this work.

[1] https://github.com/rcbops/rpc-openstack/blob/master/rpcd/etc/openstack_deploy/user_variables.yml#L73-L78

**Comment by BjoernT** [comment] 2016-06-08 11:58
So conversely all pips are not inside the OSA version tree, no separation anymore?

**Comment by jpmontez** [comment] 2016-11-29 19:38
Closing as this is EOL.

**Closed by jpmontez** 2016-11-29 19:38 UTC
Labels: prio-3, status-needs-information, type-bug
