### ISSUE TITLE
Set Status to Critical if no data is returned on hardware checks

### ISSUE THREAD

**Issue by git-harry** [rcbops/rpc-openstack#1093] opened 2016-05-20 09:04 UTC
##### What version (commit) do you encounter this issue on?
Juno
##### What type of issue is this (bug, feature, documentation, regression)?
Bug
##### What is the expected behavior?
If a check does not return any status at all, it should throw an error.

For checks that use manufacturer's tools (i.e. OpenManage or hp*cli) to return status of hardware, a check that returns no data should default to a critical status as it is most likely an issue that requires further investigation.
##### What is actually happening?
No errors are being reported for hardware (esp Raid Controllers in a down/bad state)
##### How can we reproduce this issue?
Experience failed RAID card on HP hardware
##### How can we verify your issue is addressed?
Failed RAID card generates error
##### What is your evaluation on the importance of this issue, and why?
Given the rate of RAID failures on HP Hardware, this is affecting high-dollar customers who are losing faith in the brand.
----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by git-harry** [comment] 2016-05-20 09:05
@mtsprout I have transferred your issue here from rpc-maas because that repo is no longer maintained. Please review this issue and provide any missing details.

**Comment by mtsprout** [comment] 2016-05-31 20:28
What version (commit) do you encounter this issue on?

Juno

What type of issue is this (bug, feature, documentation, regression)?
Bug

What is the expected behavior?
If a check does not return any status at all, it should throw an error.

For checks that use manufacturer's tools (i.e. OpenManage or hp*cli) to return status of hardware, a check that returns no data should default to a critical status as it is most likely an issue that requires further investigation.

What is actually happening?
No errors are being reported for hardware (esp Raid Controllers in a down/bad state)

How can we reproduce this issue?
Experience failed RAID card on HP hardware

How can we verify your issue is addressed?
Failed RAID card generates error

If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

What is your evaluation on the importance of this issue, and why?
Given the rate of RAID failures on HP Hardware, this is affecting high-dollar customers who are losing faith in the brand.

What branches / milestones do you believe this issue should target?
All, and should be backported to at least Juno, even though it is not supported.  Again, the size of the customers, should be taken into account.

The list below is what is currently supported for backports

Remove branches (lines) you do not wish to target.

 Master
 liberty-12.2
 liberty-12.1
 kilo

**Comment by git-harry** [comment] 2016-06-01 10:34
@mtsprout Juno is not supported by new development. If this bug requires a code change the deployment will need to be upgraded to at least Kilo to be able to consume it.

Please check that the appropriate monitoring check/alarm has been created. There should be a check called 'hp-disk' and an alarm called 'hp_disk_status'. Assuming they exist take a look in '/var/log/rackspace-monitoring-agent.log' for anything related to the check. If the plugin fails, i.e. the return code is 1, it should cause an alarm to be generated. We need to identify if the plugin is failing to return metrics or the metric 'hardware_disk_status' is not being set to 1.

The plugin runs the command 'hpssacli ctrl all show config', what is the output you see when running the command manually on a host with a failed card? What is the output from running hp_monitoring.py manually?

**Comment by mtsprout** [comment] 2016-06-01 13:28
To be clear:  Plugins work fine when the native agent responds.  When it does not respond, there needs to be an error thrown.

An example of this error checking can be found here:  

https://github.com/rjemanuele/virgo_plugins/blob/master/smartd_overall.sh

I will escalate the issue to ensure a juno backport, at least for TD.  Thanks.

**Comment by git-harry** [comment] 2016-06-01 13:51
@mtsprout to be clear, there will be no backport. You are obviously free to raise this internally however development is only supported on Kilo and Liberty.

I may be misunderstanding the issue here, by 'native agent' are you referring to rackspace-monitoring-agent? If the agent has failed no plugins work, that is not specific to the hp_monitoring plugin. A recent update to the agent should address this by enabling agent monitoring, this is being rolled out by support.

If the link is highlight different status lines that can be returned e.g. 'status ok' or 'status err', that should not matter because if the plugin fails the alarm should automatically go critical.

**Comment by mtsprout** [comment] 2016-06-01 13:58
By native agent, I mean hp*cli or openmanage or whatever.  I understand how the individual scripts work; they scrape the output from those utilities.

We have had multiple HP RAID card failures that have not alerted when failing.  We have tried to catch them in the act, but that is difficult at best.

**Comment by alextricity25** [comment] 2016-08-02 21:25
I can take a look at this, but as @git-harry pointed out, it won't be backported to Juno. That branch is EOL.
@claco Do we have some HP gear I can play around with?

**Comment by alextricity25** [comment] 2016-08-03 14:20
Correct me if I'm wrong, but according to the subprocess documentation, when a command returns a non-zero exit code when run with check_output() , it raises a CalledProcessError exception, which we don't catch here[1].

If the command run by subprocess were to return a non-zero exit code, and this exception is raised, would the hp alarm criteria still be evaluated correctly? Or will the entire check fail? I say this because at this point the hp_monitoring.py plugin has thrown an exception.

Would it be better if we catch the exception here and return 0? Something like:
```
    try:
        output = subprocess.check_output(command)
    except CalledProcessError:
        return 0
```
Or we might be able to return the actual return code, to allow for more elaborate checks in the alarm criteria. 

[1] https://github.com/rcbops/rpc-openstack/blob/master/maas/plugins/hp_monitoring.py#L26

**Comment by git-harry** [comment] 2016-08-03 15:06
@alextricity25 an uncaught exception should cause the plugin to fail which should generate an alert in MaaS. That is by design, basically if we're going to do something with the exception, for example retry some command or provide a more useful error message, it makes sense to catch it. Otherwise I'm not sure there is any benefit because the script will already fail in such situations.

**Comment by alextricity25** [comment] 2016-08-03 18:14
I think the solution to this bug report should include, but not limited to, catching that exception, and providing a useful error message like you suggested. Just thinking out loud here ;)
 However, it sounds to me that the problem @mtsprout is describing is with a lack of a proper return code when the RAID card is down. @mtsprout suggested it's because "hpssacli ctrl all show config" isn't returning anything when the RAID controller is down. 
All of the other *_status() methods in the hp_monitoring.py plugin use "hpssacli ctrl all show **status**", not **config**[1]. I wonder if it's suppose to be that way. I'll need access to a healthy HP box to test.

[1] https://github.com/rcbops/rpc-openstack/blob/master/maas/plugins/hp_monitoring.py#L51

**Comment by alextricity25** [comment] 2016-08-03 18:36
Just confirmed that "hpssacli ctrl all show config" is indeed correct. And if everything is normal it will spit this out:
# hpssacli ctrl all show config

Smart Array P840 in Slot 3                (sn: PDNNF0ARH7P0I5)


   Internal Drive Cage at Port 1I, Box 1, OK

   Internal Drive Cage at Port 1I, Box 1, OK

   Internal Drive Cage at Port 2I, Box 2, OK
   array A (SAS, Unused Space: 0  MB)


      **logicaldrive 1 (16.4 TB, RAID 1+0, OK)**

      physicaldrive 1I:1:1 (port 1I:box 1:bay 1, SAS, 3 TB, OK)
      physicaldrive 1I:1:2 (port 1I:box 1:bay 2, SAS, 3 TB, OK)
      physicaldrive 1I:1:3 (port 1I:box 1:bay 3, SAS, 3 TB, OK)
      physicaldrive 1I:1:4 (port 1I:box 1:bay 4, SAS, 3 TB, OK)
      physicaldrive 1I:1:5 (port 1I:box 1:bay 5, SAS, 3 TB, OK)
      physicaldrive 1I:1:6 (port 1I:box 1:bay 6, SAS, 3 TB, OK)
      physicaldrive 1I:1:7 (port 1I:box 1:bay 7, SAS, 3 TB, OK)
      physicaldrive 1I:1:8 (port 1I:box 1:bay 8, SAS, 3 TB, OK)
      physicaldrive 2I:2:1 (port 2I:box 2:bay 1, SAS, 3 TB, OK)
      physicaldrive 2I:2:2 (port 2I:box 2:bay 2, SAS, 3 TB, OK)
      physicaldrive 2I:2:3 (port 2I:box 2:bay 3, SAS, 3 TB, OK)
      physicaldrive 2I:2:4 (port 2I:box 2:bay 4, SAS, 3 TB, OK)

root@672159-test02:~# hpssacli ctrl all show status

Smart Array P840 in Slot 3
   Controller Status: OK
   Cache Status: OK
   Battery/Capacitor Status: OK

**Comment by alextricity25** [comment] 2016-08-03 20:37
UPDATE: I'm still doing some research as to what is the best way for alerting an operator in case of a RAID failure.  OP said the hpssacli command returns nothing in an event of a RAID failure, but is it enough to check for an empty output before setting the status to CRITICAL? Maybe there is a better way of checking for a RAID failure.
I'm also adding some better exception handling so the plugin logs in maas_plugins.log provide more useful information.

**Comment by alextricity25** [comment] 2016-08-03 22:25
I looked over the hp_monitoring.py script a little more closely. Theoretically the checks will fail if the raid controller is down. If the raid controller is down, ``hpssacli ctrl all show config`` should report logicaldrive 1 as DOWN, and the plugin will report a metric value of 0, causing the alarms to go into CRITICAL state. That's assuming the command ``hpssacli`` could even be run if the RAID controller is down.

Even if ``hpssacli ctrl all show config`` returns no output, the plugin will throw an exception[1], causing it to fail and causing the alarms to go into the CRITICAL state.

@mtsprout: Could you provide us with more information on @git-harry's questions earlier?
> Please check that the appropriate monitoring check/alarm has been created. There should be a check called 'hp-disk' and an alarm called 'hp_disk_status'. Assuming they exist take a look in '/var/log/rackspace-monitoring-agent.log' for anything related to the check. If the plugin fails, i.e. the return code is 1, it should cause an alarm to be generated. We need to identify if the plugin is failing to return metrics or the metric 'hardware_disk_status' is not being set to 1.
The plugin runs the command 'hpssacli ctrl all show config', what is the output you see when running the command manually on a host with a failed card? What is the output from running hp_monitoring.py manually?

@mtsprout I realize you probably don't have an HP server with a failed card just lying around...but any more information that you remember would be appreciated.
I'll leave it up to @git-harry to decide what the next course of action is. Should we try to reproduce the issue on some HP gear?

**Comment by git-harry** [comment] 2016-08-04 09:19
@alextricity25 I think reproducing the issue is the only way we're going to be able to tell if we've fixed it.

**Comment by alextricity25** [comment] 2016-08-04 15:57
Per @claco's request, I'm keeping this as blocked until support can give us a little more information about the plugin's behavior in an event of a RAID controller failure. Tagging @TEKNISHEN and @coldcolors for tracking purposes.
 Could you guys keep us in the loop next time a RAID controller failure happens on an HP server? Maybe jot down some notes of the behavior of the plugin and alarms?
It would also be good if you run the following command and record the output (if you are able to run commands on the server):
``hpssacli ctrl all show config``

Thanks!

**Comment by mancdaz** [comment] 2016-08-05 09:36
@alextricity25 There was another controller failure last night. Unfortunately, as discussed, this usually results in an OS lockup and therefore the agent output cannot be captured.  In this case, also as discussed, a 'host down' type alert was generated, which is as good a behaviour as we can expect in this type of scenario.  The only thing that could be captured was the hardware logs, after the system was rebooted...not that these can help much here:

```
###

Event: 26 Added: 08/04/2016 16:02
CRITICAL: Drive Array Subsystem - Drive Array Controller Failure (Slot 3).

Event: 27 Added: 08/04/2016 19:32
CAUTION: POST Messages - Option ROM POST Error: 1719-Slot 3 Drive Array - A controller failure event occurred prior to this power-up. (Previous lock up code = 0x13) Action: Install the latest controller firmware. If the problem persists, replace the controller..

######
```

If this issue is to stay in blocked until we get maas agent or hpssacli output on a raid controller failure, I would suggest it's going to be sitting here for quite a long time.

The closest to testing this will be to 'acquire' some hardware with dual controllers, and induce a failure on the secondary controller where the OS is not installed.

**Comment by b3rnard0** [comment] 2016-08-05 15:45
@BjoernT Please provide some feedback on our current assessment. Thanks.

cc: @git-harry @mancdaz @claco

**Comment by alextricity25** [comment] 2016-08-08 16:32
I'm still waiting for a response on this one.
From what I have gathered, the plugin already checks for a blank output and throws an exception in such a case. In addition, there really isn't anything we could add to this plugin to alert for a RAID controller failing, since it causes an OS-lockup and at this point the monitoring agent is unusable. 
Administrators should be getting some other type of alerts in the scenario of a OS-lockup, such as a host-down alert.

**Comment by git-harry** [comment] 2016-08-09 08:02
@JCallicoat are you able to provide feedback on this issue as to whether or not support has any concerns with it being closed.

**Comment by JCallicoat** [comment] 2016-08-09 08:58
@git-harry In my experience the bug in the controller firmware does cause the OS to lock, but it sounds like @mtsprout may have seen a case where he caught it before lockup. If we could be notified when the server is about to crash rather than after it's already down, I think that would be valuable. The latest available firmware is still buggy, so even targeting this to Kilo or Liberty could still be beneficial. I'd like to hear more info from Craig about this before closing. I'll ping him tomorrow.

**Comment by alextricity25** [comment] 2016-08-10 23:38
@JCallicoat were you able to get a hold of @mtsprout?
If you are thinking that it would be more valuable to add checks that monitor the host for potential hardware issues, then maybe it would be best to open up a new card for that. It could be that those checks are already in place, depending on what your looking for.
This bug report only mentions that the hp cli tools return no data in an event of a RAID controller failure, and there is no alarm triggered. However, we have already confirmed that the hp_monitoring.py plugin throws an exception when any of the hp cli tools return no data and, in turn,  cause an alert.

Let me know what you think. I would love to get this card moving, especially since it's been sitting in our queue for a bit.

**Comment by mtsprout** [comment] 2016-08-12 18:57
If an exception is thrown when no data is returned from hssacli or similar tools, then I consider the issue closed.

**Comment by alextricity25** [comment] 2016-08-15 13:57
Sounds good. Closing per comments above.

**Closed by alextricity25** 2016-08-15 13:57 UTC
Labels: feature-monitoring, impacts-support, prio-2, status-blocked, status-doing, status-needs-information, swimlane-rr, type-bug
