### ISSUE TITLE
MaaS broken on infra hosts due to incorrect Openstack client versions

### ISSUE THREAD

**Issue by wesmattson** [rcbops/rpc-openstack#1148] opened 2016-06-10 21:37 UTC
##### What version (commit) do you encounter this issue on?
r12.1.0
##### What type of issue is this (bug, feature, documentation, regression)?
bug
##### What is the expected behavior?
Correct versions of openstack clients installed, maas works
##### What is actually happening?
This only happens on infra hosts. It seems like the openstack clients are getting installed before the pip config gets laid down. So the latest versions of the openstack clients get installed and some of the client versions (seen with the keystone client mainly) seem to not be compatible with maas.
##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
This issue is seen after maas is setup. All the playbooks go through without error. The issue is after maas gets deployed, there are a number of a checks that fail. The checks fail because maas uses the incorrect version of the openstack clients.
##### How can we reproduce this issue?
Deploy maas. For any of the critical checks, click on the alarm criteria to find out what command the particular check runs on the host. Run that command manually on the host and it will fail. Also check the pip package versions on the infra hosts: pip freeze | grep python-
##### How can we verify your issue is addressed?
Ensure the proper version of openstack clients get installed, or make maas compatible with the latest versions of the openstack clients.
##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?
On the infra hosts only
```
# Check current openstack client package versions
pip freeze | grep python-

Example:
root@infra01:~# pip freeze | grep python-
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
python-apt===0.9.3.5ubuntu2
python-cinderclient==1.7.0
python-daemon==1.6.1
python-glanceclient==2.0.0
python-heatclient==1.2.0
python-keystoneclient==3.1.0
python-memcached==1.57
python-neutronclient==4.2.0
python-novaclient==4.0.0
python-openstackclient==2.4.0
python-swiftclient==3.0.0

# Uninstall
for i in python-cinderclient python-glanceclient python-keystoneclient python-neutronclient python-novaclient python-swiftclient ; do pip uninstall $i ; done

# Reinstall
for i in python-cinderclient python-glanceclient python-keystoneclient python-neutronclient python-novaclient python-swiftclient ; do pip install $i ; done

# Recheck openstack client versions
root@infra01:~# pip freeze | grep python-
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
python-apt===0.9.3.5ubuntu2
python-cinderclient==1.5.0
python-daemon==1.6.1
python-glanceclient==1.2.0
python-heatclient==0.8.0
python-keystoneclient==2.0.0
python-memcached==1.57
python-neutronclient==3.1.0
python-novaclient==2.35.0
python-swiftclient==2.7.0
```
##### What is your evaluation on the importance of this issue, and why?
I think this is fairly important because we need to make sure we have the correct version of the clients installed before anything that relies on them gets installed.
##### What branches / milestones do you believe this issue should target?
12.0
###### Remove branches (lines) you do not wish to target.
- [ ] Master
- [ ] liberty-12.2
- [ ] liberty-12.1
- [ ] liberty-12.0

##### Does your change require documentation?
- [x] No documentation required for this change

**Comment by git-harry** [comment] 2016-06-13 10:32
I believe this to be a duplicate of https://github.com/rcbops/rpc-openstack/issues/1124

**Closed by git-harry** 2016-06-13 10:32 UTC
Labels: status-duplicate
