### ISSUE TITLE
Wrong version of python-keystoneclient installed

### ISSUE THREAD

**Issue by shane-c** [rcbops/rpc-openstack#1261] opened 2016-07-23 00:30 UTC
##### On which version(s) do you encounter this issue?

root@infra01:/opt/rpc-openstack/rpcd/playbooks# git describe --all
r12.2.1

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

On a greenfield deployment python-keystoneclient 1.7.2 is installed

##### What is actually happening?

python-keystoneclient 3.2.0 is installed which breaks certain MaaS checks

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

Running setup-maas.yml, lots of checks go into critical status because our plugins don't work with python-keystoneclient 3.2.0

##### How can we reproduce this issue?

On a greenfield deployment run setup-maas.yml and see critical checks
````
root@infra02:~# pip freeze | grep python-keystone
python-keystoneclient==3.2.0

root@infra02:~# /usr/lib/rackspace-monitoring-agent/plugins/neutron_service_check.py --host infra02_neutron_agents_container-80c7ed9b 172.29.236.10
status error Cannot import keystoneclient

root@infra02:~# pip freeze | grep python-keystone
python-keystoneclient==1.7.2

root@infra02:~# /usr/lib/rackspace-monitoring-agent/plugins/neutron_service_check.py --host infra02_neutron_agents_container-80c7ed9b 172.29.236.10
status okay
metric neutron-metadata-agent_status uint32 1
metric neutron-dhcp-agent_status uint32 1
metric neutron-l3-agent_status uint32 1
metric neutron-linuxbridge-agent_status uint32 1
metric neutron-metering-agent_status uint32 1
````
##### How can we verify your issue is addressed?

python-keystoneclient 1.7.2 is installed instead of 3.2.0

##### If you are using or know of a workaround please describe the necessary steps?

pip uninstall python-keystoneclient
pip install python-keystoneclient==1.7.2

##### What is your evaluation on the importance of this issue, and why?

Meduim

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by ameserole** [comment] 2016-08-08 20:05
@shane-c have you seen this in any more liberty deployments? After some initial testing in an AIO I was not able to reproduce it. I am continuing my though.

`root@messy-rpc:/opt/rpc-openstack/rpcd/playbooks# git describe --all
heads/liberty-12.2
root@messy-rpc:/opt/rpc-openstack/rpcd/playbooks# pip freeze | grep keystone
python-keystoneclient==1.7.2`

**Comment by shane-c** [comment] 2016-08-08 20:39
Pretty sure this can be closed and was caused by not running pip-lockdown.yml after setup-hosts.yml as it's done in deploy.sh.

**Comment by ameserole** [comment] 2016-08-08 20:42
@shane-c Thanks for the info. Im going to close this issue then.

**Closed by ameserole** 2016-08-08 20:42 UTC
Labels: feature-monitoring, impacts-support, prio-2, status-doing, swimlane-rr, type-bug
