### ISSUE TITLE
The nova_cloud_stats.py plugin is reporting wrong number of vcpus

### ISSUE THREAD

**Issue by OchiengEd** [rcbops/rpc-openstack#1107] opened 2016-05-31 18:31 UTC
##### What version (commit) do you encounter this issue on?
All

##### What type of issue is this (bug, feature, documentation, regression)?
Bug

##### What is the expected behavior?
The nova_cloud_stats.py plugin should return the number of vcpus in the environment.

##### What is actually happening?
The plugin returns the number of physical cores available across the hypervisors which does not factor in the cpu allocation ratio. This is causing false positive alerts for high vcpu usage..

##### How can we reproduce this issue?

```
# python /usr/lib/rackspace-monitoring-agent/plugins/nova_cloud_stats.py | egrep 'vcpu|status'
status okay
metric cloud_resource_used_vcpus uint32 222 vcpu
metric cloud_resource_total_vcpus uint32 224 vcpu
# 
```

##### How can we verify your issue is addressed?
Compare the number of physical cores versus total vcpus reported. Total vcpus should be higher unless cpu allocation ratio of 1 to 1 is used.

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?
Disable the check to prevent unnecessary alerting

##### What is your evaluation on the importance of this issue, and why?
Medium. Knowing the amount of vcpu resources available can help in capacity planning before resources actually run out.

##### What branches / milestones do you believe this issue should target?
Kilo
Liberty

###### Remove branches (lines) you do not wish to target.
- [x] Master
- [x] liberty-12.2 (https://github.com/rcbops/rpc-openstack/pull/1239)
- [x] kilo (https://github.com/rcbops/rpc-openstack/pull/1240)

**Comment by mancdaz** [comment] 2016-06-01 08:05
Hi @OchiengEd 

Is the request here that the plugin should factor in the cpu allocation ratio? (e.g 200 cores with allocation ratio of 2 should show 400 vcpu). If so, this was discussed at the time of implementation and deemed outside the scope of this plugin.

**Comment by OchiengEd** [comment] 2016-06-01 12:25
Yes @mancdaz ,

If this is by design like you say and there are no desires to change how this works, perhaps we should stop giving alerts for high vcpu usage once vcpus used reaches 90% of the physical cores. Which in essence implies we will not have any alarms setup to generate alerts for vcpu usage in private cloud environments.

**Comment by BjoernT** [comment] 2016-06-01 14:23
@mancdaz This is sad, the design choice made will render the check useless, it will always alert. All of our new deployments have the check disabled because it alerts after Kilo upgrades. Can we remove the check now ?

**Comment by mancdaz** [comment] 2016-06-02 10:22
@BjoernT @OchiengEd  it's less of a design choice, more of a limitation in what data the nova API can provide - it simply does not factor in allocation ratios when reporting cpu/vcpu resource.

One possible way to make this work as intended would be to add an extra var (or indeed 2 - one for cpu and one for memory) to the rpc_maas role, where we set the overcommit ratios - we can then use this when configuring the alarm. I'd rather keep the plugin itself reporting the real data from the nova API, but we can use the var to multiply those numbers when building the alarm.


eg

```
if (percentage((metric["cloud_resource_used_vcpus"]) * {{ my_multiplier }}), (metric["cloud_resource_total_vcpus"]) * {{ my_multiplier }}) > {{ cloud_resource_critical_vcpus }}) {
                return new AlarmStatus(CRITICAL, "Total cloud vcpus usage exceeds critical threshold of {{ cloud_resource_critical_vcpus }}%");
            }
```

N.B. Sadly, we can't get the values directly from the nova role where they are set for nova.conf because those vars aren't available to this play - hence why I'm suggesting we need separate vars that live inside the rpc_maas role. Yes, it's 2 places to set the same thing if one were to ever change the ratios, but it's a tradeoff.

**Comment by OchiengEd** [comment] 2016-06-02 15:10
@mancdaz While that could help, it is a limited fix; while it will cover a majority of RPC customers, it does not cater to customers who may have the cpu allocation ratio being different per nova aggregate zone.

I'll let @BjoernT  chime in on this and see what he says.

**Comment by mancdaz** [comment] 2016-06-02 15:50
You're right, but without the necessary data being available from the Nova
API it's the best we'd be able to do.

**Comment by mancdaz** [comment] 2016-06-13 10:53
@BjoernT @OchiengEd any further thoughts? Given the fix would cover the majority, is it not worth making that change?

**Comment by BjoernT** [comment] 2016-06-13 13:57
For now I think it is ok to use nova_cpu_allocation_ratio to calculate the vcpu allowances. This is certainly better than what we have now.

**Comment by mancdaz** [comment] 2016-06-14 20:37
@BjoernT @OchiengEd what ratios do you want to monitor by default? OSA sets the ratios as follows, and I don't think we override them in rpc-o anywhere:

```
nova_cpu_allocation_ratio: 2.0
nova_disk_allocation_ratio: 1.0
nova_ram_allocation_ratio: 1.0
```

**Comment by BjoernT** [comment] 2016-06-14 20:38
Yes these are the most important ones for now

**Comment by mancdaz** [comment] 2016-06-14 20:39
@BjoernT I meant the values - does cpu: 2 and mem: 1 work for you?

**Comment by BjoernT** [comment] 2016-06-14 20:56
Those are the default values right ? We override them from time to time so we need to take a look if we want to update the plugin code once the nova config has been altered, setup-maas plays write the current nova_xxx_allocation_ratio values into the nova_cloud_stats.py or the plugin is reading the nova.conf from a nova scheduler container

**Comment by mancdaz** [comment] 2016-06-14 21:10
@BjoernT as discussed above, the rpc_maas role cannot access the vars from the nova role because the roles are independent and we won't always have access to the nova role var namespace when running this role.

I think the best we can do is add vars to the rpc_maas role to match those in the nova role, and use those values as multipliers for the plugin to consume. If you override the nova values from time to time, you'd need to override the matching values in the maas role to get the correct stats from the plugin. It's not ideal, but as we said it should nicely cover the majority of your use cases.

PR forthcoming - please take a look and see if it will work for you

**Comment by mancdaz** [comment] 2016-07-18 12:21
master patch has merged, awaiting kilo and liberty-12.2 backports being approved/merged

**Comment by claco** [comment] 2016-07-18 13:14
As this bug winds down with backports, has anyone filed a bug for this upstream or had the conversation in the mailing list or with the nova folks? I wonder if this is something they'd consider adding? (asking to ask)

**Comment by BjoernT** [comment] 2016-07-18 16:00
@claco  Do  you want the overcommit ratios exposed on the nova api, or what is your idea ?

**Comment by mancdaz** [comment] 2016-07-19 15:45
master patch and backports have all merged now. Closing issue to move it out of the system, and taking the discussion regarding tackling this in nova offline.

**Closed** 2016-07-19 15:45 UTC
Labels: feature-monitoring, prio-2, status-approved, type-bug
