### ISSUE TITLE
nova writes temp snapshot files to the root partition

### ISSUE THREAD

**Issue by h1pp13p373** [rcbops/rpc-openstack#1097] opened 2016-05-22 13:04 UTC
##### What version (commit) do you encounter this issue on?
11.2.9-11-g0504bcc
##### What type of issue is this (bug, feature, documentation, regression)?
seems like a bug to me
##### What is the expected behavior?
I'd expect the snapshot temp file to be saved on the larger partition, /var/lib/nova.  
##### What is actually happening?
Nova is writing the snapshot to /var/lib/libvirt/qemu/save/, and filling up the root partition in some cases.
##### How can we reproduce this issue?
`nova image-create <image uuid> <snapshot name>`
`watch -n2 "ls -alh /var/lib/libvirt/qemu/save/"`
##### How can we verify your issue is addressed?
First bug submission, I am not sure what to put here.
##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?
Symlink /var/lib/libvirt/qemu/save/ to somewhere under /var/lib/nova

##### What is your evaluation on the importance of this issue, and why?
Very important.  Customers snapshotting large instances can fill up the root partition on the compute node with a single snapshot.
##### What branches / milestones do you believe this issue should target?
This specific version is the only place I've seen the behavior.  I don't have an accessible lab to test further.
###### Remove branches (lines) you do not wish to target.
- [x] master
- [x] liberty-12.2
- [x] liberty-12.1

**Comment by odyssey4me** [comment] 2016-05-23 08:28
This ML thread may relate to this issue: http://lists.openstack.org/pipermail/openstack-operators/2016-April/010238.html

**Comment by prometheanfire** [comment] 2016-05-24 15:20
What version of libvirt and qemu are you using?

1.2.2 and 2.0 (libvirt and qemu) are known to cause issues.
  see http://lists.openstack.org/pipermail/openstack-operators/2016-April/010251.html

adding the following is a possible workaround if we use a newer libvirt/qemu

    [workarounds]
    disable_libvirt_livesnapshot=False

Here's the help text for that option, the bad part is that cold snapshots cause an instance outage while the snapshot is running.

    Live snapshots allow the snapshot of the disk to happen without an
    interruption to the guest, using coordination with a guest agent to
    quiesce the filesystem.
    
    When using libvirt 1.2.2 live snapshots fail intermittently under load
    (likely related to concurrent libvirt/qemu operations). This config
    option provides a mechanism to disable live snapshot, in favor of cold
    snapshot, while this is resolved. Cold snapshot causes an instance
    outage while the guest is going through the snapshotting process.
    
    For more information, refer to the bug report:
    
       https://bugs.launchpad.net/nova/+bug/1334398
   
    Possible values:
    
    * True: Live snapshot is disabled when using libvirt
    * False: Live snapshots are always used when snapshotting (as long as
      there is a new enough libvirt and the backend storage supports it)

**Comment by prometheanfire** [comment] 2016-05-24 16:22
Confirmed that even in mitaka it uses `/var/lib/libvirt/qemu/save/`  it also cleans up after itself when done, so we should be able to rmdir it and replace with a simlink as long as nothing is snapshotting at the time.

**Comment by prometheanfire** [comment] 2016-05-24 16:23
This is something that should likely be in OSA (creating the symlink).  Gonna raise it in irc/upstream bug.

**Comment by prometheanfire** [comment] 2016-05-24 16:34
looks like we just can't change the path, libvirt maintainers aren't that nice... http://comments.gmane.org/gmane.comp.emulators.libvirt/53301

**Comment by prometheanfire** [comment] 2016-05-24 19:10
I don't think this will hit kilo as it is an upstream OSA bug, I'm working on getting it into mitaka/liberty though.

https://bugs.launchpad.net/openstack-ansible/+bug/1585325

**Comment by prometheanfire** [comment] 2016-06-01 04:42
master merged, backporting now

kilo is dead though...

**Comment by prometheanfire** [comment] 2016-06-03 03:18
ok, we just need sha bumps now

@git-harry when does that happen next for all maintained branches?

**Comment by git-harry** [comment] 2016-06-03 15:41
@prometheanfire we have a release scheduled for next week, so I will update the SHAs today/Monday

**Comment by prometheanfire** [comment] 2016-06-07 14:24
fix committed

**Closed by prometheanfire** 2016-06-07 14:24 UTC
Labels: osa-tracking, prio-1, status-doing, type-bug
