### ISSUE TITLE
Need to reserve space on swift object node disks to prevent accidental fill up

### ISSUE THREAD

**Issue by timolow** [rcbops/rpc-openstack#653] opened 2015-12-07 19:28 UTC
We need the ability to reserve space on swift obj storage nodes so in the event of the disks filling up, we have the ability to free space to allow cluster expansion/deletes/replication to take place.

Putting Swift into a quota group or creating dot files on the obj nodes of X size might be alternatives since XFS does not have the concept of reserved user space incorporated.

Thanks,

Tim

- [x] master
- [x] liberty-12.2
- [x] liberty-12.1

**Comment by matthewoliver** [comment] 2015-12-15 01:07
When a swift drive fills up, all new objects meant for that disk will be durably written to a handoff node, so you wont loose any durability of your data.

The object-replicators have an option called 'handoffs_first', which when set will try to push and remove handoffs before trying to push its primary partitions. When a disk fills and you add capacity or change the drives weight to drain the objects on it, this option allows it to clear up faster.

We had discussions about better ways to deal with this at the last swift design summit, and we are looking at documenting these best practices and maybe adding some more tools to help (like have a handoff only mode to the replicator so it drains more quickly).

But yes this means keeping an eye (or monitoring disk space) on the cluster is important. but so long as you have enough disk space, a full drive or too isn't the end of the world.

**Comment by andymcc** [comment] 2015-12-15 17:48
@matthewoliver I think the problem is that once you have a full drive, there is no way to reduce usage on that drive? I agree that data integrity is fine, but assuming we have no desire to add additional capacity at that point (lets say we want to clean up old unused objects first) - what I've looked up is that it won't let you remove any objects, because in order to delete an object it has to perform a write, and there is no space to perform said write.

Is there any way around this, aside from monitoring the cluster, which we already do (assuming there was a situation where a user error, or some other issue caused the cluster to fill up quite rapidly.)?

**Comment by andymcc** [comment] 2015-12-15 17:49
As an aside, one of the docs I read (can't find it now) recommended keeping 10% of each drive reserved.

**Comment by timolow** [comment] 2015-12-15 17:59
Correct, tombstone files cannot be created once the drives are full.   The only way to unfreeze the cluster is to randomly delete ring parts from the object folder or decrease reserve space enough to allow deletes to occur.

**Comment by andymcc** [comment] 2016-02-12 15:13
Researched this a bit more, there is a built in reserve_fallocate since grizzly. This works pretty well, it will reserve a certain amount of space on the disk (without using it), preventing PUT requests above the non-reserved portion of the disk.
It allows deletes to still happen though.

I'm handling this as an OS-A bug: https://bugs.launchpad.net/openstack-ansible/+bug/1545018

**Comment by andymcc** [comment] 2016-02-12 15:16
As an example, uploading a 1G file above the threshold returns this:

# swift upload test1 test2.img
put_object(u'test1', u'test2.img', ...) failure and no ability to reset contents for reupload.

But you can still delete other files:
# swift delete test1 test1.img
test1.img

**Comment by BjoernT** [comment] 2016-02-17 16:56
I think we can close this bug and implement fallocate_reserve which was built to prevent such issues like this one to happen. See for docs at https://bugs.launchpad.net/openstack-manuals/+bug/1095507

**Comment by git-harry** [comment] 2016-04-19 10:16
Is there an appropriate default to set for fallocate_reserve?

**Closed** 2016-05-23 09:14 UTC
Labels: impacts-doc, impacts-qe, osa-tracking, prio-2, type-bug
