### ISSUE TITLE
Kibana search broken, httptime missing ?

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1013] opened 2016-04-20 14:43 UTC
##### What version (commit) do you encounter this issue on?

r12.0.0

##### What type of issue is this (bug, feature, documentation, regression)?

Bug

##### What is the expected behavior?

Working kibana

##### What is actually happening?

Either parsing is bad or logstash does not add the httptime field etc.
Elasticsearch bails out with : 
```
[2016-04-20 15:38:59,968][DEBUG][action.search.type       ] [Living Mummy] [logstash-2016.04.20][0], node[H5qa-pyDQAK42vvhDQVYBw], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@40cc2492]
org.elasticsearch.search.SearchParseException: [logstash-2016.04.20][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"facets":{"7":{"date_histogram":{"key_field":"@timestamp","value_field":"httptime","interval":"10s"},"global":true,"facet_filter":{"fquery":{"query":{"filtered":{"query":{"query_string":{"query":"tags:openstack AND httptime:*"}},"filter":{"bool":{"must":[{"range":{"@timestamp":{"from":1461162240274,"to":1461163140274}}}]}}}}}}}},"size":0}]]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:721)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:557)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:529)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:291)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.search.facet.FacetPhaseExecutionException: Facet [7]: (value) field [httptime] not found
        at org.elasticsearch.search.facet.datehistogram.DateHistogramFacetParser.parse(DateHistogramFacetParser.java:197)
        at org.elasticsearch.search.facet.FacetParseElement.parse(FacetParseElement.java:93)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:705)
        ... 9 more
[2016-04-20 15:38:59,969][DEBUG][action.search.type       ] [Living Mummy] All shards failed for phase: [query]
org.elasticsearch.search.SearchParseException: [logstash-2016.04.20][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"facets":{"7":{"date_histogram":{"key_field":"@timestamp","value_field":"httptime","interval":"10s"},"global":true,"facet_filter":{"fquery":{"query":{"filtered":{"query":{"query_string":{"query":"tags:openstack AND httptime:*"}},"filter":{"bool":{"must":[{"range":{"@timestamp":{"from":1461162240274,"to":1461163140274}}}]}}}}}}}},"size":0}]]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:721)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:557)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:529)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:291)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.search.facet.FacetPhaseExecutionException: Facet [7]: (value) field [httptime] not found
        at org.elasticsearch.search.facet.datehistogram.DateHistogramFacetParser.parse(DateHistogramFacetParser.java:197)
        at org.elasticsearch.search.facet.FacetParseElement.parse(FacetParseElement.java:93)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:705)
        ... 9 more
```
##### How can we reproduce this issue?

-

##### How can we verify your issue is addressed?

No errors in the elasticsearch logs

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

Normal

###### Remove branches (lines) you do not wish to target.
- [ ] Master
- [ ] liberty-12.1
- [ ] liberty-12.0
- [ ] kilo

**Comment by hybridpollo** [comment] 2016-05-21 23:27
Confirmed that I encountered the same issue in another 12.0 environment.

```
DISTRIB_ID="RPC"
DISTRIB_RELEASE="r12.0.0"
DISTRIB_CODENAME="wee-5ive"
DISTRIB_DESCRIPTION="Rackspace Private Cloud powered by OpenStack
```

Elasticsearch log entry:

```
[2016-05-22 00:20:56,252][DEBUG][action.search.type       ] [Aggamon] [logstash-2016.05.21][0], node[PA-ZfvViQ_ejgU_QJxomtA], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@4e72e93e]
org.elasticsearch.search.SearchParseException: [logstash-2016.05.21][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"facets":{"7":{"date_histogram":{"key_field":"@timestamp","value_field":"httptime","interval":"10s"},"global":true,"facet_filter":{"fquery":{"query":{"filtered":{"query":{"query_string":{"query":"tags:openstack AND httptime:*"}},"filter":{"bool":{"must":[{"range":{"@timestamp":{"from":1463871956144,"to":1463872856144}}}]}}}}}}}},"size":0}]]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:721)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:557)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:529)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:291)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.search.facet.FacetPhaseExecutionException: Facet [7]: (value) field [httptime] not found
	at org.elasticsearch.search.facet.datehistogram.DateHistogramFacetParser.parse(DateHistogramFacetParser.java:197)
	at org.elasticsearch.search.facet.FacetParseElement.parse(FacetParseElement.java:93)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:705)
	... 9 more
```

**Comment by mancdaz** [comment] 2016-06-01 09:35
@BjoernT or @hybridpollo could you please detail how one might reproduce this issue? Are you performing a particular search, are there specific search terms. A step-by-step 'how did I make this happen' would be really useful.

**Comment by BjoernT** [comment] 2016-06-01 14:39
For me the issue immediately was visible on logon after a new install or upgrade  of RPC-O from Juno to Kilo.

**Comment by mancdaz** [comment] 2016-06-10 11:47
@BjoernT @hybridpollo Just to provide an update - I'm struggling to reproduce this. A freshly installed liberty seems to work fine, showing the httptime field as expected:

https://i.imgur.com/nuAMvNJ.png

That was using 12.2.0rc1. 

A freshly installed kilo also worked fine.

I wonder are you able to check if you see the same issue in 12.2.0rc3, since both of you reported the issue in 12.0.0 and I wonder if it's been fixed now?

**Comment by mancdaz** [comment] 2016-06-13 08:40
@BjoernT @hybridpollo further research indicates that the error you are seeing may be due to corrupted indexes, however I am still unable to reproduce and have built a number of liberty (and kilo) deployments.

I would argue that given that this is not repeatable and is not affecting all customers and deployments, the priority be reduced.

/cc @git-harry

**Comment by git-harry** [comment] 2016-06-13 09:19
Is there a workaround for this? Do we know what percentage of Liberty customers are affected? If this affects greenfield deployments and we can't reproduce with an AIO it might be worth testing this in a hardware lab.

I would be inclined to agree that it is a prio-2, there are certainly issues currently open that I would consider more pressing.

**Comment by BjoernT** [comment] 2016-06-13 14:51
I'm not sure about the corrupted indexes, I removed recent indexes to build them with fresh data but still ran into this problem. I will spot check other Liberty deployments, on some I can not reach ES due to SSH tunnel limitations so we will not now for sure if all deployments are affected

**Comment by git-harry** [comment] 2016-06-13 14:51
@mancdaz discussed in triage and @BjoernT has seen in all Liberty deployments he's been engaged on. Please investigate further with him.

**Comment by mancdaz** [comment] 2016-06-13 15:26
exchanged private email with @BjoernT to try and gain access to some internal environments where this is being seen.

**Comment by mancdaz** [comment] 2016-06-16 10:34
Still awaiting access

**Comment by BjoernT** [comment] 2016-06-16 20:43
So I just checked a new deployment and it is working there. To the problem might be related to an environmental issue which we have to isolate. Giving the fact that it works on at least one a new Liberty, justifies to lower the prio to 2 until I can check more environments

**Comment by mancdaz** [comment] 2016-06-16 21:22
Thanks @BjoernT

**Comment by b3rnard0** [comment] 2016-07-21 14:13
@BjoernT Any new updates? I'm going through the Support upgrades bugs to get those prioritized.

**Comment by BjoernT** [comment] 2016-07-21 14:17
Let me follow up, we have not done any upgrades anymore also this problem is not necessarily a upgrade issue.

**Comment by b3rnard0** [comment] 2016-07-21 14:52
@BjoernT Does this need to be de-prioritized?

**Comment by BjoernT** [comment] 2016-07-21 14:55
@b3rnard0 Possibly if I can't find any recent installation with issues, perhaps I close it even.

**Comment by b3rnard0** [comment] 2016-07-21 15:09
Okay, de-prioritizing for now and if you find something on this, we'll adjust as necessary.

**Comment by git-harry** [comment] 2016-08-01 16:39
Due to the inability to reproduce the issue and no new reports of this issue I'm going to close it.

**Closed by git-harry** 2016-08-01 16:39 UTC
Labels: impacts-support, prio-3, status-needs-information, type-bug
