### ISSUE TITLE
F5 Monitor change for horizion pool and Kilo

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#372] opened 2015-08-25 19:11 UTC
After upgrading to Kilo, the old HTTP monitor for horizon is failing because it generates a HTTP redirect to go to the URL /auth/login/
Please change the F5 generator to accommodate this change
This also has a doc impact to change the URL to monitor inside the HTTP monitor for the horizon SSL pool to /auth/login/ @klevenstein

**Comment by claco** [comment] 2015-08-25 19:18
Is this a dupe, or related to https://github.com/rcbops/rpc-openstack/issues/249 ?

**Comment by nrb** [comment] 2015-08-25 19:20
Sounds like this is an F5 change, so I'm not sure it's a dupe of #249. More related to how we have to move Galera to TCP half open checks so that the pool doesn't go into an error state.

All that said, I'm not sure what the actual change is to the F5 output.

**Comment by claco** [comment] 2015-08-25 19:24
Some form of https://github.com/rcbops/rpc-openstack/blob/master/scripts/f5-config.py#L53 and https://github.com/rcbops/rpc-openstack/blob/master/scripts/f5-config.py#L59

That said, we can document this as a known issue, and/or a post upgrade step. I would not hold release for this.

**Comment by robb-romans** [comment] 2015-08-25 19:29
doc change for prior issue: https://github.com/rpcdocs/rpcdocs/pull/174

**Comment by robb-romans** [comment] 2015-08-25 21:06
@BjoernT @claco  Is the doc fix "Change the URL to monitor inside the HTTP monitor for the Horizon SSL pool to /auth/login/" ? 

Any more info we should provide?

**Comment by nrb** [comment] 2015-08-28 16:10
@busterswt Is this a change you guys need to make to the F5 config, or do you weant us (devs) to?

**Comment by claco** [comment] 2015-09-28 14:38
Closing as this is now covered in the docs post release.

**Closed by claco** 2015-09-28 14:38 UTC
