### ISSUE TITLE
Logstash overrun with messages around heat

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#658] opened 2015-12-08 23:11 UTC
RPC 11 all versions:

      "_source":{"tags":["heat","openstack","oslofmt","logstash-input-tcp"],"@version":1,"@timestamp":"2015-12-08T01:26:15.063Z","host":"xx","file":"/var/log/heat/heat-api.log-20151123.gz","message":"2015-11-22 06:35:47.269 39419 INFO heat.openstack.common.policy [req-c48c0b9e-dac2-4484-b357-cb3d649b51a5 - admin] Can not find policy directory: policy.d","type":"file","logdate":"2015-11-22 06:35:47.269","pid":"39419","loglevel":"INFO","module":"heat.openstack.common.policy","logmessage":"[req-c48c0b9e-dac2-4484-b357-cb3d649b51a5 - admin] Can not find policy directory: policy.d","received_at":"2015-12-07 20:26:15 -0500"}

Currently we seem to create 200G messages per day on a small cluster

**Comment by BjoernT** [comment] 2015-12-08 23:16
I will add more messages if I can dig though this haystack

**Comment by d34dh0r53** [comment] 2015-12-14 17:47
We can either fix this by creating the directory or adding a filter to ignore this message.  The former is the quickest fix but the latter is probably more correct.

**Comment by tomc603** [comment] 2015-12-22 17:37
I've been playing with this for a while now, and I've got some questions. As noted in the OSA version of this bug, this will impact anything that has a deprecated policy.d situation. The messages don't constantly spew out, only when the item in question (glance, heat, etc.) attempt to take an action that would trigger the policy nonsense.

I've had an AIO standing up for about a day and I've watched the logs roll through. If we're looking to reduce the amount of log data then we should switch the default logging from INFO to WARN or higher. Most of the INFO level logs are absolutely useless unless you're using them for auditing purposes. On an installation with an active glance or heat, I could see there being lots of these policy.d messages, but can I get a sense from @BjoernT how many he's seeing compared to other messages? They seem to be a small minority compared to the other noise my stack is generating.

If they really are being spewed out at a high rate, then we've got a bigger problem. These messages are being captured both in /var/log/syslog and in /var/log/heat-api.log. We should probably reduce the messages we're duplicating in syslog log files so we don't cause containers to run out of space. But we should also probably filter these messages at the syslog level, because otherwise they'll get logged twice locally, collected by beaver, shipped over the wire and grok'd by logstash, then dropped. If we're really creating 200G of these events (which seems impossibly high to me), then that's about 8.3GB/h of data shipped over the network we can save.

Thoughts @BjoernT @d34dh0r53 and @sigmavirus24?

**Comment by tomc603** [comment] 2015-12-23 18:05
PR for master in #698

**Comment by sigmavirus24** [comment] 2015-12-28 15:41
Hey @tomc603 sorry for not responding sooner. I was on vacation.

I have been wondering about the log level we've been collecting. I'll try to bug our support team on IRC about this and see what their thoughts are.

**Comment by tomc603** [comment] 2015-12-28 15:43
Awesome. I did submit a super simple patch to filter these messages
specifically, but I think the greater issue of volume is the log level.

**Comment by BjoernT** [comment] 2015-12-29 02:55
We did a doc count and that revealed interesting data, like many _grokparsefailure docs.
I don't think the logging level is the issue because the log file size seemed normal.
```
curl "$ESURL/logstash-2015.12.20/_search?search_type=count&pretty" -d '{ "size": 0, "aggs": { "count_by_file": { "terms": { "field": "tags", "size": 50 } } } }'
{
  "took" : 340436,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 398978613,
    "max_score" : 0.0,
    "hits" : [ ]
  },
  "aggregations" : {
    "count_by_file" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [ {
        "key" : "input",
        "doc_count" : 398978613
      }, {
        "key" : "logstash",
        "doc_count" : 398978613
      }, {
        "key" : "tcp",
        "doc_count" : 398666069
      }, {
        "key" : "openstack",
        "doc_count" : 396461789
      }, {
        "key" : "oslofmt",
        "doc_count" : 395420902
      }, {
        "key" : "nova",
        "doc_count" : 220310243
      }, {
        "key" : "neutron",
        "doc_count" : 102751753
      }, {
        "key" : "apimetrics",
        "doc_count" : 53381811
      }, {
        "key" : "heat",
        "doc_count" : 36302284
      }, {
        "key" : "_grokparsefailure",
        "doc_count" : 27216718
      }, {
        "key" : "cinder",
        "doc_count" : 24337493
      }, {
        "key" : "glance",
        "doc_count" : 11415329
      }, {
        "key" : "infrastructure",
        "doc_count" : 2204280
      }, {
        "key" : "beaver",
        "doc_count" : 1775158
      }, {
        "key" : "apache",
        "doc_count" : 765333
      }, {
        "key" : "keystone",
        "doc_count" : 765044
      }, {
        "key" : "access",
        "doc_count" : 409316
      }, {
        "key" : "error",
        "doc_count" : 392712
      }, {
        "key" : "auth",
        "doc_count" : 392419
      }, {
        "key" : "syslog",
        "doc_count" : 312544
      }, {
        "key" : "horizon",
        "doc_count" : 304089
      }, {
        "key" : "swift",
        "doc_count" : 275554
      }, {
        "key" : "nginx",
        "doc_count" : 36695
      }, {
        "key" : "repo",
        "doc_count" : 36695
      }, {
        "key" : "elasticsearch",
        "doc_count" : 7
      }, {
        "key" : "rabbitmq",
        "doc_count" : 1
      } ]
    }
  }
}
```

**Comment by tomc603** [comment] 2015-12-29 14:17
27 million out of 398 million is higher than I saw in my test environment,
but I'm obviously not running everything possible.

Either way, 398 million hits is quite a lot. It looks like nova and neutron
account for play over 200 million, so we should probably look into what is
going on there.

**Comment by BjoernT** [comment] 2016-01-04 23:19
I was surprised to see outdated messages in a recent logstash index and that caught my interest :
The file /var/log/nova/nova-cert.log-20151109.gz was parsed to we seem to parse rotated archives into ES again, causing all the duplicates ?

"_source":{"tags":["nova","openstack","oslofmt","logstash-input-tcp"],"@version":1,"@timestamp":"2016-01-04T22:53:37.957Z","host":"","file":"/var/log/nova/nova-cert.log-20151109.gz","message":"2015-11-01 23:46:12.275 559 ERROR oslo_messaging._drivers.impl_rabbit [req-85ed2552-187f-4dcb-9031-35568d70d21f - - - - -] AMQP server on :5672 is unreachable: [Errno 111] ECONNREFUSED. Trying again in 1 seconds.","type":"file","logdate":"2015-11-01 23:46:12.275","pid":"559","loglevel":"ERROR","module":"oslo_messaging._drivers.impl_rabbit","logmessage":"[req-85ed2552-187f-4dcb-9031-35568d70d21f - - - - -] AMQP server on :5672 is unreachable: [Errno 111] ECONNREFUSED. Trying again in 1 seconds.","received_at":"2016-01-04 17:53:37 -0500"}
}, {
"_index" : "logstash-2016.01.04",

Seems like this beaver config is too greedy:

/etc/beaver/conf.d# grep ']' *
cinder:[/var/log/cinder/]
glance:[/var/log/glance/]
heat:[/var/log/heat/]
neutron:[/var/log/neutron/]
nova:[/var/log/nova/]

**Comment by tomc603** [comment] 2016-01-05 00:08
I'm like 99% sure I've seen this exact bug already and that there was even a patch for it? Maybe it never made it to the merged state?

**Comment by tomc603** [comment] 2016-01-05 00:09
Found it. This bug is a duplicate of https://github.com/rcbops/rpc-openstack/pull/524. I'm "Ghost" in that thread.

**Comment by BjoernT** [comment] 2016-01-05 14:44
Since we improved other things as part of this issue I would propose to close #524

**Comment by tomc603** [comment] 2016-01-11 19:54
@BjoernT Can I get a sample of a few of the docs in _grokparsefailure? I think the patch to only parse .log files should fix most of this bug, but I'd love to open a new one for the parse failures.

**Comment by BjoernT** [comment] 2016-01-11 20:14
Hotspots seemed to be around apache/keystone apache error logs:
```
{
  "took" : 6,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 2151,
    "max_score" : 3.673508,
    "hits" : [ {
      "_index" : "logstash-2016.01.04",
      "_type" : "file",
      "_id" : "AVIPBP0W29yK7mZNgNi4",
      "_score" : 3.673508,
      "_source":{"tags":["keystone","openstack","apache-error","logstash-input-tcp","_grokparsefailure"],"@version":1,"@timestamp":"2016-01-04T23:42:10.220Z","host":"<ip>.189","file":"/var/log/keystone/keystone-apache-error.log","message":"2016-01-04 18:42:10.142605 2016-01-04 18:42:10.142 3216 INFO keystone.common.wsgi [-] GET /projects?","type":"file","module":"keystone.error.%{module}"}
    }, {
      "_index" : "logstash-2016.01.04",
      "_type" : "file",
      "_id" : "AVIPBP0W29yK7mZNgNjA",
      "_score" : 3.673508,
      "_source":{"tags":["keystone","openstack","apache-error","logstash-input-tcp","_grokparsefailure"],"@version":1,"@timestamp":"2016-01-04T23:42:10.322Z","host":"<ip>.189","file":"/var/log/keystone/keystone-apache-error.log","message":"2016-01-04 18:42:10.255932 2016-01-04 18:42:10.255 3259 INFO keystone.common.wsgi [-] GET /users?domain_id=Default","type":"file","module":"keystone.error.%{module}"}
    }, {
      "_index" : "logstash-2016.01.04",
      "_type" : "file",
      "_id" : "AVIPBP0W29yK7mZNgNjG",
      "_score" : 3.673508,
      "_source":{"tags":["keystone","openstack","apache-error","logstash-input-tcp","_grokparsefailure"],"@version":1,"@timestamp":"2016-01-04T23:42:10.423Z","host":"<ip>.189","file":"/var/log/keystone/keystone-apache-error.log","message":"2016-01-04 18:42:10.396788 2016-01-04 18:42:10.396 3230 INFO keystone.common.wsgi [-] GET /?","type":"file","module":"keystone.error.%{module}"}
    }, {
      "_index" : "logstash-2016.01.04",
      "_type" : "file",
      "_id" : "AVIPBP0W29yK7mZNgNkV",
      "_score" : 3.673508,
      "_source":{"tags":["keystone","openstack","apache-error","logstash-input-tcp","_grokparsefailure"],"@version":1,"@timestamp":"2016-01-04T23:42:11.187Z","host":"<ip>.158","file":"/var/log/keystone/keystone-apache-error.log","message":"2016-01-04 18:42:11.140408 2016-01-04 18:42:11.140 4183 INFO keystone.common.wsgi [-] GET /services?","type":"file","module":"keystone.error.%{module}"}
    }, {
      "_index" : "logstash-2016.01.04",
      "_type" : "file",
      "_id" : "AVIPBQEp29yK7mZNgNkt",
      "_score" : 3.673508,
      "_source":{"tags":["keystone","openstack","apache-error","logstash-input-tcp","_grokparsefailure"],"@version":1,"@timestamp":"2016-01-04T23:42:11.489Z","host":"<ip>.158","file":"/var/log/keystone/keystone-apache-error.log","message":"2016-01-04 18:42:11.487198 2016-01-04 18:42:11.486 4171 INFO keystone.common.wsgi [-] GET /?","type":"file","module":"keystone.error.%{module}"}
    }, {
      "_index" : "logstash-2016.01.04",
      "_type" : "file",
      "_id" : "AVIPBQEp29yK7mZNgNk_",
      "_score" : 3.673508,
      "_source":{"tags":["keystone","openstack","apache-error","logstash-input-tcp","_grokparsefailure"],"@version":1,"@timestamp":"2016-01-04T23:42:11.591Z","host":"<ip>.158","file":"/var/log/keystone/keystone-apache-error.log","message":"2016-01-04 18:42:11.580310 2016-01-04 18:42:11.579 3382 INFO keystone.common.wsgi [-] GET /services?","type":"file","module":"keystone.error.%{module}"}
    }, {
      "_index" : "logstash-2016.01.04",
      "_type" : "file",
      "_id" : "AVIPBQU829yK7mZNgNl6",
      "_score" : 3.673508,
      "_source":{"tags":["heat","openstack","oslofmt","logstash-input-tcp","_grokparsefailure"],"@version":1,"@timestamp":"2016-01-04T23:42:12.677Z","host":"<ip>.186","file":"/var/log/heat/heat-api.log","message":"2016-01-04 18:42:12.558 587 INFO eventlet.wsgi.server [req-e2295ee1-9d5a-4e8a-9e36-f77b657fbf2e - admin] <ip>.43 - - [04/Jan/2016 18:42:12] \"GET /v1/edeffce07f644e3cada6e94ca8149578/build_info HTTP/1.1\" 200 280 0.031700","type":"file","logdate":"2016-01-04 18:42:12.558","pid":"587","loglevel":"INFO","module":"heat.eventlet.wsgi.server","logmessage":"[req-e2295ee1-9d5a-4e8a-9e36-f77b657fbf2e - admin] <ip>.43 - - [04/Jan/2016 18:42:12] GET /v1/edeffce07f644e3cada6e94ca8149578/build_info HTTP/1.1 200 280 0.031700","received_at":"2016-01-04 18:42:12 -0500"}
    }, {
      "_index" : "logstash-2016.01.04",
      "_type" : "file",
      "_id" : "AVIPBQkq29yK7mZNgNmK",
      "_score" : 3.673508,
      "_source":{"tags":["heat","openstack","oslofmt","logstash-input-tcp","_grokparsefailure"],"@version":1,"@timestamp":"2016-01-04T23:42:13.682Z","host":"<ip>.186","file":"/var/log/heat/heat-api.log","message":"2016-01-04 18:42:12.587 587 INFO eventlet.wsgi.server [req-14e79ff8-21fe-4324-90af-743f0de9bd0c - admin] <ip>.43 - - [04/Jan/2016 18:42:12] \"GET /v1/edeffce07f644e3cada6e94ca8149578/build_info HTTP/1.1\" 200 280 0.026076","type":"file","logdate":"2016-01-04 18:42:12.587","pid":"587","loglevel":"INFO","module":"heat.eventlet.wsgi.server","logmessage":"[req-14e79ff8-21fe-4324-90af-743f0de9bd0c - admin] <ip>.43 - - [04/Jan/2016 18:42:12] GET /v1/edeffce07f644e3cada6e94ca8149578/build_info HTTP/1.1 200 280 0.026076","received_at":"2016-01-04 18:42:13 -0500"}
    }, {
      "_index" : "logstash-2016.01.04",
      "_type" : "file",
      "_id" : "AVIPBQ0c29yK7mZNgNmc",
      "_score" : 3.673508,
      "_source":{"tags":["keystone","openstack","apache-error","logstash-input-tcp","_grokparsefailure"],"@version":1,"@timestamp":"2016-01-04T23:42:14.439Z","host":"<ip>.202","file":"/var/log/keystone/keystone-apache-error.log","message":"2016-01-04 18:42:14.388228 2016-01-04 18:42:14.387 27255 INFO keystone.common.wsgi [-] GET /?","type":"file","module":"keystone.error.%{module}"}
    }, {
      "_index" : "logstash-2016.01.04",
      "_type" : "file",
      "_id" : "AVIPBNWJ29yK7mZNgNdR",
      "_score" : 3.673508,
      "_source":{"tags":["heat","openstack","oslofmt","logstash-input-tcp","_grokparsefailure"],"@version":1,"@timestamp":"2016-01-04T23:42:00.292Z","host":"<ip>.180","file":"/var/log/heat/heat-api.log","message":"2016-01-04 18:41:59.239 112970 INFO eventlet.wsgi.server [req-a51ef9ea-df9e-49f0-82d3-3fabc5728dc3 - admin] <ip>.24 - - [04/Jan/2016 18:41:59] \"GET /v1/edeffce07f644e3cada6e94ca8149578/build_info HTTP/1.1\" 200 280 0.027621","type":"file","logdate":"2016-01-04 18:41:59.239","pid":"112970","loglevel":"INFO","module":"heat.eventlet.wsgi.server","logmessage":"[req-a51ef9ea-df9e-49f0-82d3-3fabc5728dc3 - admin] <ip>.24 - - [04/Jan/2016 18:41:59] GET /v1/edeffce07f644e3cada6e94ca8149578/build_info HTTP/1.1 200 280 0.027621","received_at":"2016-01-04 18:42:00 -0500"}
    } ]
  }
}
```

**Comment by BjoernT** [comment] 2016-01-12 21:08
So it seems like these changes helped pretty good:
```
health status index               pri rep docs.count docs.deleted store.size pri.store.size
green  open   logstash-2016.01.08   1   0    2297100            0      1.3gb          1.3gb
green  open   logstash-2016.01.10   1   0    2355466            0      1.3gb          1.3gb
green  open   logstash-2016.01.07   1   0    2149933            0      1.2gb          1.2gb
green  open   logstash-2016.01.05   1   0    2249649            0      1.3gb          1.3gb
green  open   logstash-2016.01.09   1   0    2376483            0      1.3gb          1.3gb
green  open   logstash-2016.01.06   1   0    2190045            0      1.2gb          1.2gb
green  open   logstash-2016.01.12   1   0    2153439            0      1.2gb          1.2gb
green  open   logstash-2016.01.04   1   0      31184            0       20mb           20mb
green  open   logstash-2016.01.11   1   0    2419694            0      1.4gb          1.4gb
```

**Comment by tomc603** [comment] 2016-01-12 22:01
Awesome news @BjoernT!

**Comment by d34dh0r53** [comment] 2016-01-13 16:10
Needs `kilo` backport

**Comment by BjoernT** [comment] 2016-01-13 16:16
Added kilo backport

**Closed** 2016-01-13 20:29 UTC
Labels: kilo-backport-potential, prio-1, type-bug
