### ISSUE TITLE
Swift requirement applied to rpc_maas role even if DEPLOY_SWIFT="no"

### ISSUE THREAD

**Issue by alextricity25** [rcbops/rpc-openstack#1659] opened 2017-01-09 16:21 UTC
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
swift binaries are not installed on the repo server when DEPLOY_SWIFT='no'(in the case of a ceph deployment)
##### What is actually happening?
Swift artifacts are still built into the repo server due to the hard swift requirement used by the rpc_maas role here: https://github.com/rcbops/rpc-openstack/blob/master/rpcd/playbooks/roles/rpc_maas/defaults/main.yml#L486. This will cause the repo_server playbook to fail on deployments without swift since the binaries are not pulled down, but the requirements are still in place.

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
Ceph deployment, or a deployment without swift(DEPLOY_SWIFT='no')

##### How can we reproduce this issue?
Run a deployment without swift i.e. DEPLOY_SWIFT='no'

##### How can we verify your issue is addressed?
Deployments that are run with DEPLOY_SWIFT='no'

##### If you are using or know of a workaround please describe the necessary steps?
set ``repo_build_git_selective`` to "no"
##### What is your evaluation on the importance of this issue, and why?
prio-3, low-hanging fruit. This isn't halting development, nor is it customer impacting.

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [] master

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [x] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [x] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [x] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [x] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

Connects #2027

**Comment by b3rnard0** [comment] 2017-03-13 14:40
Related/duplicate of #2027.

**Closed** 2017-06-13 12:57 UTC
Labels: prio-3, status-duplicate, swimlane-enhancements, type-bug
