### ISSUE TITLE
RPC Solutions Tab rpc_heat js function is undefined

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/rpc-openstack#891] opened 2016-03-10 17:48 UTC
##### What version (commit) do you encounter this issue on?
r12.0.0rc2

##### What type of issue is this (bug, feature, documentation, regression)?
bug, regression

##### What is the expected behavior?
Display custom rpc heat solutions

##### What is actually happening?
It looks like the function rpc_heat is not defined in heat.js

##### How can we reproduce this issue?
Install RPCD horizon_extensions play, log into horizon, click on Solutions tab in RPC drop down
 
##### What is your evaluation on the importance of this issue, and why?
Users will not be able to use the RPC custom heat solutions until this is fixed for our liberty release

##### What branches / milestones do you believe this issue should target?
The list below is what is currently supported for backports, remove branches you do not wish to target.
- [x] Master
- [x] liberty-12.0

![screen shot 2016-03-10 at 11 43 01 am 3](https://cloud.githubusercontent.com/assets/2229998/13678764/fb757b9e-e6b5-11e5-886c-0018ac4d7ba5.png)

**Comment by jacobwagner** [comment] 2016-03-10 18:12
It may be the fact that the angularModuleExtension is not defined that is the real cause of the issue since the rpc_heat function belongs to the horizonApp angular module which inherits from angularModuleExtension

**Comment by claco** [comment] 2016-03-10 18:15
Pulling in a few folks who might have some idears...  @neillc @r1chardj0n3s

**Comment by jacobwagner** [comment] 2016-03-10 18:51
I defined the anjularModuleExtenion variable as an empty array and while it removed the undefined error it did not fix the rpc_heat function issue

**Comment by r1chardj0n3s** [comment] 2016-03-11 05:41
There's a few things going on here.

Firstly, the top-level angular app was renamed to 'horizon.app' (from 'hz'). That's gonna mess with your code a bunch (in heat.js). I'm pretty sure all of the "Redfining the entire horizonApp here" code can just go away. For more info on angularjs plugins in Liberty+ there's a pretty good post here: https://developer.ibm.com/opentech/2015/10/08/add-angularjs-dashboard-plugin-openstack-horizon/

Secondly, you should unbundle angular-bootstrap entirely; liberty onwards includes it as a Horizon requirement (0.11 in Liberty ... and Mitaka, sigh ... but will get better over time).

I couldn't figure out all the moving parts to get a checkout working locally; I need to set up a liberty OSA to point it at and time is limited today unfortunately. I did have access to a lab system for a while but I can't seem to get into it any longer. I'm going to keep working on getting a Liberty OSA going to test against.

**Comment by r1chardj0n3s** [comment] 2016-03-16 05:18
This is fixed with https://github.com/rcbops/horizon-extensions/pull/7 but the fix needs to be confirmed by someone who can set up a proper OSA with it - there's some sort of magic going on to have the extension be included in Horizon that I'm not aware of. Horizon needs a couple of enabled/ directory files, and these weren't in the horizon-extensions repository where I'd normally expect to find them. The fix for this issue includes code in the enabled files.

**Comment by d34dh0r53** [comment] 2016-03-17 14:22
@neillc @r1chardj0n3s The https://github.com/rcbops/horizon-extensions/pull/7 along with #900 fix the problem.  Thanks for the work on this!  I'll work on getting this all merged.

**Comment by prometheanfire** [comment] 2016-03-17 19:41
just need it backported then

**Closed** 2016-03-23 17:23 UTC
Labels: backport-potential-liberty, prio-1, status-doing, type-bug

**Comment by erikmwilson** [comment] 2016-03-23 18:33
@b3rnard0 Have we added any new templates to the Solutions tab since its first release? If so, we should probably proof the screen text.
