### ISSUE TITLE
qemu save directory is not symlinked causing task to fail

### ISSUE THREAD

**Issue by jaime-gutierrez** [rcbops/rpc-openstack#2099] opened 2017-03-30 21:37 UTC
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
I'm assuming the expected behavior is at some point a playbook which deploy.sh executes would create a symlink for the qemu save directory.

The "TASK [os_nova : Check the state of the default qemu save directory]" is expecting there to be a symlink for the qemu save directory which is not being created when running deploy.sh.

##### What is actually happening?
The symlink for the qemu save directory does not get created which causes "TASK [os_nova : Check the state of the default qemu save directory]" to fail.
fatal: [727479-lab04]: FAILED! => {"changed": false, "failed": true, "stat": {"exists": false}}
fatal: [727480-lab05]: FAILED! => {"changed": false, "failed": true, "stat": {"exists": false}}

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
export DEPLOY_MAAS="no"
export DEPLOY_HAPROXY="no"
export DEPLOY_SWIFT=no
scripts/deploy.sh

##### How can we reproduce this issue?
Perform an installation with deploy.sh

export DEPLOY_MAAS="no"
export DEPLOY_HAPROXY="no"
export DEPLOY_SWIFT=no
scripts/deploy.sh

##### How can we verify your issue is addressed?
deploy.sh is able to create the qemu save symlink

##### If you are using or know of a workaround please describe the necessary steps?
on compute hosts, create symlink via ```ln -s /var/lib/nova/save /var/lib/libvirt/qemu/save```

##### What is your evaluation on the importance of this issue, and why?
minor as the workaround is simple
----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] newton-14.0
- [ ] mitaka-13.1
- [ ] liberty-12.2

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by b3rnard0** [comment] 2017-03-31 17:52
@robb-romans or @erikmwilson We will need to have this on the release notes for 14.0.0. The workaround is listed in the issue and you can ask @jaime-gutierrez for more information.

**Comment by robb-romans** [comment] 2017-04-03 02:04
@b3rnard0 @jaime-gutierrez Please follow the process (noted in checklist above) by opening a docs issue or PR at https://github.com/rackerlabs/docs-rpc/

Thank you!

**Comment by alextricity25** [comment] 2017-04-03 14:15
We chatting briefly about this in our standup today.
Because we haven't seen this in our QE tests nor gating jobs, we are not going to say any work is needed for this card in the 14.0.0 milestone. However, I've marked it with the 14.0.1 milestone so we could investigate this further post 14.0.0.

**Comment by robb-romans** [comment] 2017-04-13 18:12
@b3rnard0 due to @alextricity25 note above ^^^ we have **not** added any documentation for this. If this becomes a confirmed issue, please let the Docs team know and open a PR or issue in https://github.com/rackerlabs/docs-rpc/

Thanks.

**Comment by alextricity25** [comment] 2017-04-28 17:16
We haven't seen this in our testing nor has it appeared on deployments. I'm closing this off for now. Please re-open the issue if it appears for you again!

**Closed by alextricity25** 2017-04-28 17:16 UTC
Labels: impacts-doc, impacts-newton, prio-3, status-documentation-ready, swimlane-enhancements, type-bug

**Comment by Alfano93** [comment] 2017-05-15 17:46
I have run into this issue as well. It looks like the link /var/lib/libvirt/qemu/save -> /var/lib/nova/save doesn't get created. This was seen in a customer environment. 

Creating the link with ln -s fixed the issue and playbooks ran without problems.
