### ISSUE TITLE
Juno to Kilo upgrade: lxc-container can not mount /var/run/netns and losing all namespaces

### ISSUE THREAD

**Issue by nrb** [rcbops/rpc-openstack#354] opened 2015-08-20 18:00 UTC
Tracking upstream bug - https://bugs.launchpad.net/openstack-ansible/+bug/1487130

**Comment by odyssey4me** [comment] 2015-08-24 08:16
Does the neutron container work properly after the setup-openstack playbook is run? If so, then is this really an issue worth holding back for. While it is more ideal to have the upgrade run in a manner that's as online as possible, it's my understanding that the upgrades are done in a maintenance window and therefore down time is expected. As long as it works afterwards, this should be something we improve but it shouldn't hold back RPC11's release.

**Comment by nrb** [comment] 2015-08-24 14:08
It works properly after a container restart. @Apsu was looking into this on Friday, we think it might have been some of the temporary cleanup playbooks in the upgrade script.

**Comment by claco** [comment] 2015-08-24 14:20
@odyssey4me Same quesitons were asked the day we experienced it. It has been deemed a release blocker for support.

**Comment by nrb** [comment] 2015-08-24 14:29
In terms of the actual down time - users are told to expect short periods network interruption in the order of seconds while containers, rabbitmq, mariadb, and neutron itself restart. In our environment, though, the ping test to a neutron IP failed for 29 minutes.

**Comment by cloudnull** [comment] 2015-08-24 14:41
Did the issue resolve itself after the 29 minutes or was it only resolved after the neutron server containers were restarted? Do all of the neutron servers and agents need to be restarted?

**Comment by nrb** [comment] 2015-08-24 14:46
It solved itself over the course of the upgrade; those 29 minutes were basically going from the beginning of the script to the actual neutron upgrade steps.

**Comment by cloudnull** [comment] 2015-08-24 14:56
I would imagine that this issue is being caused by the addition to the openstack-lxc template as found here: https://github.com/stackforge/os-ansible-deployment/blob/kilo/playbooks/roles/lxc_container_create/tasks/container_create.yml#L80 

Would it be possible to review the neutron server lxc configs to see if the app aromor profile with has more than one entry. If so the last one in config is the only one loaded and I'd image that the change in the aa profile for the lxc container build process, which reiterates through all containers, is causing the issues and resolves itself when the neutron container becomes "unconfined" here: https://github.com/stackforge/os-ansible-deployment/blob/kilo/playbooks/os-neutron-install.yml#L27

**Comment by cloudnull** [comment] 2015-08-24 15:29
related fix that I believe will solve this issue: https://review.openstack.org/216301

**Comment by nrb** [comment] 2015-08-24 15:35
Thanks @cloudnull

**Comment by claco** [comment] 2015-09-28 14:43
Closing as fix went into upstream OSA prior to r11.0.0 release.

**Closed by claco** 2015-09-28 14:43 UTC
