### ISSUE TITLE
r11.1.4 ceph nodes with 4GB of RAM will OOM, "Unable to fork"

### ISSUE THREAD

**Issue by timolow** [rcbops/rpc-openstack#879] opened 2016-03-02 16:03 UTC
##### What version (commit) do you encounter this issue on?
r11.1.4
##### What type of issue is this (bug, feature, documentation, regression)?
regression/bug

##### What is the expected behavior?
ceph to deploy on OSD nodes with 4GB.

##### What is actually happening?
Ansible injects sysctl values that cause the host machine to OOM and "unable to fork"

r11.1.4 (4194303=4GB)
Mar  1 14:49:24 swift02 ansible-<stdin>: Invoked with name=vm.min_free_kbytes ignoreerrors=True value=4194303 reload=True state=present sysctl_set=False sysctl_file=/etc/sysctl.conf
Mar  1 14:50:01 swift02 cron[3405]: (CRON) error (can't fork)

r11.1.3 (4294967296=4TB)
Mar  1 16:08:07 swift02 ansible-<stdin>: Invoked with name=vm.min_free_kbytes ignoreerrors=True value=4294967296 reload=True state=present sysctl_set=False sysctl_file=/etc/sysctl.conf

##### How can we reproduce this issue?
Pull down r11.1.4 and attempt ceph install on OSDs with 4GB of RAM.

##### How can we verify your issue is addressed?
Adjust sysctl value to X% of Total Ram.

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

Remove or adjust value  vm.min_free_kbytes, value: 4194303 

##### What is your evaluation on the importance of this issue, and why?
Minor, production systems should have more then 4GB of RAM.

##### What branches / milestones do you believe this issue should target?
The list below is what is currently supported for backports, remove branches you do not wish to target.
- [x] Master
- [x] liberty-12.0
- [x] kilo

**Comment by d34dh0r53** [comment] 2016-03-02 16:38
It looks like this is actually a ceph regression: https://github.com/ceph/ceph-ansible/search?utf8=%E2%9C%93&q=vm_min_free_kbytes&type=Code  @timolow can you file this bug with the [`ceph-ansible`](https://github.com/ceph/ceph-ansible) project and link that issue here?

**Comment by d34dh0r53** [comment] 2016-03-02 16:42
It looks like it may have been introduced here: https://github.com/ceph/ceph-ansible/pull/543 @mattt416 can you work with @timolow on this?

**Comment by mattt416** [comment] 2016-03-02 16:58
This issue is def. fixed in ceph-ansible as I know @byronmccollum was hitting it and reported it upstream.  There's an issue with https://github.com/ceph/ansible-ceph-common at the moment (only 1 commit?) so I'll dig into this further once that repo is resolved.

**Comment by d34dh0r53** [comment] 2016-03-04 16:29
Backports please

**Comment by d34dh0r53** [comment] 2016-03-04 20:22
Somehow my push went from my branch directly into kilo, so that has been backported.  I can't seem to find a way to revert what I did either.  It was a straightforward cherry-pick so really no harm done, but mea culpa everyone.

**Comment by timolow** [comment] 2016-04-13 22:06
Issue is in the r12.0.0 release

**Closed** 2016-04-14 09:08 UTC
Labels: prio-1
