### ISSUE TITLE
disable innobackupex --version-check

### ISSUE THREAD

**Issue by ihavegerms** [rcbops/rpc-openstack#536] opened 2015-10-31 03:45 UTC
When rebuilding a failed galera container, the joiner attempts to pull updates from the donor but the donor fails due to what appears to be a permission issue with the percona-version-check in /tmp. After modifying the permissions to mysql:mysql, the transfer succeeds and the container can then join the cluster.

A few others have ran in to this same issue as well. Is it necessary that we keep this enabled? 

- [x] kilo

**Comment by JCallicoat** [comment] 2016-02-02 01:21
Does this need more information? It is still an issue when version checking is enabled for Galera.

**Comment by SATroll** [comment] 2016-02-03 22:26
This is still an issue.

**Comment by claco** [comment] 2016-02-03 22:31
Should we be disabling version check, or should we be changing the location instead? (--tmpdir)

**Comment by BjoernT** [comment] 2016-02-05 16:28
I think this is still a valid issue. If the removal of the version check fixes this issue, it debatable. I seem to recall a percona fix around that. I guess we are open to all ways of fixing this issue

**Comment by prometheanfire** [comment] 2016-04-11 16:35
Are you getting this issue when running a play or running something manually?  Do you hit this when simply rebuilding the container instead of trying to rejoin an existing contianer?

**Comment by BjoernT** [comment] 2016-04-11 18:23
Usually we get this issue after deploying the cluster, at least I did not encounter it during play run. Suddenly replication dies with this error after running galera for few days/weeks

**Comment by prometheanfire** [comment] 2016-04-11 18:24
So why is this check running in the first place?

**Comment by JCallicoat** [comment] 2016-04-14 01:42
It is enabled by default as of xtrabackup 2.1.6.

https://www.percona.com/doc/percona-xtrabackup/2.1/release-notes/2.1/2.1.6.html

I believe we'd need to add the following to one of the mysql config files if we want to disable it.

```
[xtrabackup]
no-version-check=true
```

**Comment by prometheanfire** [comment] 2016-04-14 20:32
if we set this value it'll likely need to go into this file

playbooks/roles/galera_server/templates/cluster.cnf.j2

we may not need to set it based on what @BjoernT for newer versions of galera (they fix this possibly)  so maybe kilo only?

**Comment by prometheanfire** [comment] 2016-04-20 16:21
I think before we submit this bug upstream (because that's where the fix would go) we need to understand why this is happening.  I'm hesitant to disable something when we don't know the root cause.

**Comment by JCallicoat** [comment] 2016-04-22 01:05
Upstream closed as Won't Fix at https://bugs.launchpad.net/openstack-ansible/+bug/1511910 since it's a known upstream bug with the package versions we use.

I think we were looking for an RPC-specific band aid.

For reference, here's an older bug mentioning the same issue and work arounds:

https://bugs.launchpad.net/percona-xtrabackup/+bug/1255451

**Closed** 2016-05-05 19:06 UTC
Labels: prio-1, status-approved
