### ISSUE TITLE
Ansible fails to remove zero weight decommissioned object nodes

### ISSUE THREAD

**Issue by timolow** [rcbops/rpc-openstack#878] opened 2016-03-02 15:32 UTC
##### What version (commit) do you encounter this issue on?
r11.0.1
##### What type of issue is this (bug, feature, documentation, regression)?
bug
##### What is the expected behavior?
When decommissioning a swift object node you must first reduce the weight over time to zero.  Once a object node has a weight set at zero I would remove the host from ansible inventory, delete node from /etc/openstack_deploy/conf.d/swift.yml and run the swift-os-sync playbooks to have ansible/swift-ring-builder remove the decommissioned storage node from the ring.
 
##### What is actually happening?
When performing the steps listed above swift-ring-builder bails with the notion there is nothing to remove/rebalance.

```
changed: [XXXXXX-objectstorage002] => (item=account) => {"changed": true, "cmd": ["/usr/bin/python", "/etc/swift/scripts/swift_rings.py", "-f", "/etc/swift/scripts/account.contents"], "delta": "0:00:00.390482", "end": "2016-01-28 18:44:47.949078", "item": "account", "rc": 0, "start": "2016-01-28 18:44:47.558596", "stderr": "", "stdout": "removing host...\nd14r1z1-10.239.60.140:6002R10.239.62.140:6002/disk11_\"\" marked for removal and will be removed next rebalance.\nremoving host...\nd16r1z0-10.239.60.141:6002R10.239.62.141:6002/disk11_\"\" marked for removal and will be removed next rebalance.\nremoving host...\nd15r1z1-10.239.60.140:6002R10.239.62.140:6002/disk12_\"\" marked for removal and will be removed next rebalance.\nremoving host...\nd17r1z0-10.239.60.141:6002R10.239.62.141:6002/disk12_\"\" marked for removal and will be removed next rebalance.\nrebalancing...\nNo partitions could be reassigned.\nEither none need to be or none can be due to min_part_hours [1].", "warnings": []}
```

##### How can we reproduce this issue?
1) Set node weight from 100 to zero.
2) Run os-swift-sync, wait 1 hour or min_part_hours.
3) Remove node from ansible inventory 
-./inventory-manage.py -f /etc/openstack_deploy/openstack_inventory.json -r XXXX-objectstorage009
4) Remove node from /etc/openstack_deploy/conf.d/swift.yml
5) Run os-swift-sync play.

##### How can we verify your issue is addressed?
When the above steps are true.

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

If you adjust the weight of any of the remaining object nodes after the above steps are performed ansible/swift-ring-builder will remove the zero weight object nodes from the ring.

ex.
1) Set node weight from 100 to zero.
2) Run `os-swift-sync.yml`, wait 1 hour or min_part_hours.
3) Remove node from ansible inventory `./inventory-manage.py -f /etc/openstack_deploy/openstack_inventory.json -r XXXX-objectstorage009`
4) Remove node from `/etc/openstack_deploy/conf.d/swift.yml`
5) Adjust weight of one remaining object node to X
6) Run `os-swift-sync.yml` play. (zero weight nodes have been removed)
7) Wait `min_part_hours`, readjust modified value and re-run plays.

##### What is your evaluation on the importance of this issue, and why?

Medium severity, the problem can be worked around if documented.  Leaving zero weight nodes in a ring when they are decommissioned will make swift telemetry report `<urlopen error [Errno 113] EHOSTUNREACH>` errors.  

In master upstream we need to back port into the community for Liberty/Kilo so we can consume the sha downstream. 

upstream commit https://review.openstack.org/#/c/233096/

##### What branches / milestones do you believe this issue should target?
The list below is what is currently supported for backports, remove branches you do not wish to target.
- [x] Master
- [x] liberty-12.2
- [x] liberty-12.1
- [x] kilo

Edit: Formatting

**Comment by d34dh0r53** [comment] 2016-03-02 15:45
Thanks for the report Tim, we will look into this.

**Comment by andymcc** [comment] 2016-03-07 16:20
To avoid anybody plugging unnecessary effort into this, I will give a (semi)-quick summary.

The most we can do, if a backport does not go through, is document the process - as far as I am aware we do not have this process documented though? @timolow perhaps you can shed light on that - if we can find where the process to reduce weight (during drive removal) is documented, for support, then we can make changes to ensure this is a documented issue that is avoided.

@matthewoliver is looking to backport the upstream fix to liberty and kilo ( https://github.com/openstack/swift/commit/71993d84e88cc1d5f7742182905cace21c7e88cb ) I am skeptical as to whether we will get a backport through for Kilo (and potentially not Liberty either), since it may not be viewed as a critical bug in upstream swift terms - a 0 weight host is pretty much just cosmetic, and you can easily avoid this by removing the device at weight 20 instead of lowering it to weight 0 before removing it. That is to say, even if you have 0 weight hosts that are not removed, they will never receive PUTs/rsyncs, any changes later on will remove these hosts.

There is no ansible fix to be made here, we call the swift-ring-builder directly which is causing this issue. The problem is that the ring-builder sees 0 weight hosts being removed as "no change" so it does not rebalance the ring. If you were to remove another host (e.g. any host with weight > 0) it would remove that host and any 0 weight hosts that are set to be removed, because the rebalance would then happen successfully. (NB it won't remove 0 weight hosts that are intentionally 0 weight and actually exist in the inventory, since they will not have the "remove" flag set via swift-ring-builder)

**Comment by matthewoliver** [comment] 2016-03-10 04:18
There was a patch already in the Openstack Swift master branch that solves this problem. The patch is in the process of being backported to Kilo and Liberty:

  https://review.openstack.org/#/c/290965/
  https://review.openstack.org/#/c/290966/

**Comment by BjoernT** [comment] 2016-03-24 15:13
Can we please get these reviews merged by core reviewers, they seem to be stale since 7 days

**Comment by nrb** [comment] 2016-03-24 15:23
> Can we please get these reviews merged by core reviewers, they seem to be stale since 7 days

I don't know that we have control over Swift core devs.

**Comment by BjoernT** [comment] 2016-03-24 15:33
Yes this is just a reminder to stay put. I assume we can not get this merged into Kilo since the branch is closed. So possibly PRCO carries a patch for kilo....

**Comment by prometheanfire** [comment] 2016-03-24 15:42
kilo's dead, long live mitaka

**Comment by claco** [comment] 2016-03-24 15:44
Added doc-impacts, so if it doesn't happen in Kilo, we get a release note into known issues.

**Comment by prometheanfire** [comment] 2016-04-11 17:08
just poked upstream, they are merging now, we just need sha updates from OSA when that happens

**Comment by prometheanfire** [comment] 2016-04-19 15:50
I'll submit shabumps for this

**Comment by prometheanfire** [comment] 2016-05-02 16:02
and OSA hasn't done SHA bumps for liberty, kilo has it but we need a tag because of the way repo-builds work. @odyssey4me

**Closed** 2016-05-09 08:53 UTC
Labels: backport-potential-kilo, impacts-doc, osa-tracking, prio-1, status-approved, type-bug
