### ISSUE TITLE
Poor default value for network_checks_list inside rpc_maas role

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#742] opened 2016-01-14 19:33 UTC
Apparently we defined the interfaces eth0 to eth3 to be enabled for maas network checks  https://github.com/rcbops/rpc-openstack/blob/kilo/rpcd/playbooks/roles/rpc_maas/defaults/main.yml#L324-L328 but in reality bare metal machines are using now udev names for interfaces like em1. 
All new checks will practically fail due to missing network interfaces and we need to either empty this parameter or add a ansible facts discovery around the interfaces or setup limits for the bonding interfaces only
----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [x] master (#1401)
- [x] mitaka-13.1 (#1473)
- [x] mitaka-13.0 (#1474)
- [x] liberty-12.2 (#1453)
- [x] kilo (#1475)

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [x] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [x] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [x] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by BjoernT** [comment] 2016-01-14 19:34
@byronmccollum

**Comment by hughsaunders** [comment] 2016-01-14 20:05
@BjoernT The default was changed to eth0 only in #719 this is in recognition that network_checks_list is not a suitable default for physical deploys or virtual tests. So network_checks_list will need to be overridden, probably in user_extras_variables for all physical deploys.

**Comment by nrb** [comment] 2016-01-14 20:06
So a completely empty value would be valid? As long as support personnel know to update that, I'm fine.

From what @hughsaunders is saying, support will need to define this, at least in the short term (since 11.1.1 is planned for tomorrow).

**Comment by hughsaunders** [comment] 2016-01-14 20:08
@nrb correct, network_checks_list does need to be defined. Maybe we could put an example in user_extras_variables to save looking up the format in rpc_maas/defaults?

**Comment by nrb** [comment] 2016-01-14 20:14
@hughsaunders To me, that sounds like we need a documentation call out at the least, and if a facts module is desired we can address it post 11.1.1. @d34dh0r53 would probably need to weigh in there.

Putting an example in would help, but I think official docs would be useful, too, so pinging @robb-romans .

**Comment by BjoernT** [comment] 2016-01-14 20:14
even eth0 is a issue, on bare metal it's not existing. That's why I would clear it out for rpc-openstack and use eth0 for aio or so

**Comment by nrb** [comment] 2016-01-14 20:21
@BjoernT Sounds like, to my mind, there really isn't really a reasonable default to hard code; we'd really need a fact used, right? But setting it manually is doable in the short term, if documented?

This is not ideal, I know, just wanting to make sure that's clear.

**Comment by BjoernT** [comment] 2016-01-14 20:24
Yes in the mean time we can fix it manually. Ideally I would prefer to leave it empty and the playbook stop here until the configuration has been done. That way we don't forget it

**Comment by robb-romans** [comment] 2016-01-14 20:29
This what we have in the docs as of today:
https://github.com/rpcdocs/rpcdocs/blob/master/rpc-installation/src/docbkx/ch-operations.xml#L168-L178

**Comment by d34dh0r53** [comment] 2016-01-14 20:30
Thanks @robb-romans, this will not hold up `11.1.1` as it's addressed in docs, but I would like to look at a developer fix going forward.

**Comment by byronmccollum** [comment] 2016-01-14 20:32
Setting `network_checks_list: []` does not work.

This task...

```
- name: Install network throughput checks
  template:
    src: "network_throughput.yaml.j2"
    dest: "/etc/rackspace-monitoring-agent.conf.d/network_throughput-{{ item.0.name }}-{{ inventory_hostname }}.yaml"
    owner: "root"
    group: "root"
    mode: "0644"
  with_together:
    - network_checks_list
    - discover_nic_speed.results
  when:
    - inventory_hostname in groups["{{ item.0.group }}"]
    - "'network_throughput-{{ item.0.name }}' not in maas_excluded_checks"
```

..blows up with the following...

```
TASK: [rpc_maas | Install network throughput checks] ************************** 
fatal: [b5a8eebf-logger1] => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 586, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 815, in _executor_internal
    complex_args=complex_args
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 869, in _executor_internal_inner
    if not utils.check_conditional(cond, self.basedir, inject, fail_on_undefined=self.error_on_undefined_vars):
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/__init__.py", line 254, in check_conditional
    if not check_conditional(x, basedir, inject, fail_on_undefined=fail_on_undefined):
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/__init__.py", line 265, in check_conditional
    conditional = template.template(basedir, conditional, inject, fail_on_undefined=fail_on_undefined)
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/template.py", line 122, in template
    varname = template_from_string(basedir, varname, templatevars, fail_on_undefined)
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/template.py", line 371, in template_from_string
    res = jinja2.utils.concat(rf)
  File "<template>", line 9, in root
  File "/usr/local/lib/python2.7/dist-packages/jinja2/runtime.py", line 489, in _fail_with_undefined_error
    raise self._undefined_exception(hint)
UndefinedError: 'None' has no attribute 'group'
```

Probably need to check the length of `network_checks_list` and add to `when:` criteria...

**Comment by nrb** [comment] 2016-01-14 20:38
So it sounds like there isn't a reasonable default, but it should fail more gracefully.

**Comment by byronmccollum** [comment] 2016-01-14 20:42
Maybe add here:

https://github.com/rcbops/rpc-openstack/blob/master/rpcd/playbooks/roles/rpc_maas/tasks/main.yml#L37-L38

**Comment by byronmccollum** [comment] 2016-01-14 21:06
I'm testing a patch for this...

https://github.com/cloud-training/rpc-heat-ansible/blob/c9b720b683240413579e14d769c13b6d37bfd1fd/playbooks/files/opt/cloud-training/patches/bug-network-checks-list-empty.patch

**Comment by byronmccollum** [comment] 2016-01-14 22:32
Works.

**Comment by git-harry** [comment] 2016-01-15 12:16
https://github.com/rcbops/rpc-openstack/commit/cfd3712e2ebd847f57a6fbdc90e7b636b7f22810 has been added so that the playbook fails if the interfaces listed in network_checks_list do not exist.

**Comment by d34dh0r53** [comment] 2016-01-15 17:43
We've merged @byronmccollum's patch, going to leave this open until a full fix is fleshed out.

**Comment by mancdaz** [comment] 2016-01-18 09:50
@d34dh0r53 @BjoernT what is the expected fully fleshed out fix here? Clearly, there is no good default list of interfaces that will suit all deployments, so the list will need to be tweaked per deployment (as was anticipated when the initial check was set up with some arbitrary interface names for testing).

There were a few attempts at cleanly deciphering all physical interfaces automatically, but nothing satisfactory, so I'm not sure if that's the anticipated long term solution here?

**Comment by BjoernT** [comment] 2016-01-18 14:03
@byronmccollum fix seem to suffice for now. The ask is not to install checks which, are going into critical on all of our deployments because we used bad default values as I said above. The easiest way to do that is to skip this check when unconfigured and we add a note in the deployment chapters.

**Comment by prometheanfire** [comment] 2016-01-18 14:27
if we get the interface prefix (eth enpswhatever etc foo) then we could probably make it a variable that can be controlled via user-extras or the like.

**Comment by mancdaz** [comment] 2016-01-18 15:26
@prometheanfire this is already configurable:

https://github.com/rcbops/rpc-openstack/blob/master/rpcd/playbooks/roles/rpc_maas/defaults/main.yml#L324-L325

The problem is getting a sane default without support having to override it each time. If we know generally the interfaces that would be present in most rpc deployments, we can default to those and they can still be overridden in non standard deployments.

**Comment by nrb** [comment] 2016-01-18 15:32
My main issue with making this a fact-based thing is that, as currently written, there's a dictionary of settings per interface. I don't know if this is something we normally utilize in production, but it would seem to me that if there truly is per-interface configuration, those would need to be manually specified no matter what.

@mancdaz I think with udev-based interface names, that might be hard, as the underlying hardware may not be guaranteed. For AIOs/virtual deployments it's easier, but for hardware where it's not tied to a specific chassis or NIC vendor, it may be per-deployment.

**Comment by mancdaz** [comment] 2016-01-18 15:37
@nrb yep, and the initial assumption of the implementation was indeed that this would need to be overridden per deployment by support. I just meant in those (possibly more rare than not) cases where we deploy on the reference architecture/hardware.

As per @BjoernT, it seems support are happy with things as they stand with the 2 patches that have gone in (fail on non existing interfaces, and allow empty list)

**Comment by prometheanfire** [comment] 2016-01-18 15:38
we could always add the specific udev rule to get naming how we want, however I don't think we should be using eth* anymore.

**Comment by d34dh0r53** [comment] 2016-01-18 22:13
This needs more investigation, we should be able to discover the default interface and use that.

**Comment by nrb** [comment] 2016-01-18 23:16
@d34dh0r53 Do we then make assumptions about what checks get assigned to the interfaces?

**Comment by tomc603** [comment] 2016-02-01 18:49
@d34dh0r53 @BjoernT @mancdaz @Apsu I think we decided last week that we weren't going to attempt to populate defaults? Am I remembering incorrectly? I seem to recall we weren't going to supply defaults, and then the variable could be overridden for actual environments.

**Comment by BjoernT** [comment] 2016-02-01 18:58
@tomc603 Did I miss something ? We absolutely need sane default values for RPC so we don't get the same issues over and over reported, beyond that we already merged it into 11.1.3.

**Comment by nrb** [comment] 2016-02-01 19:09
@BjoernT Would you mind suggesting some? As far as I know, dev doesn't know what would be sane defaults for hardware deploys.

**Comment by BjoernT** [comment] 2016-02-01 19:15
Ignore my comment, I was mixing this bug up with another one. You're right we have not set on default values and I don't think there will be any. I did test with the bridges br-mgmt byt that causes playbook issues because /proc does not always have the speed information present for devices like bridges etc.
We would need to treat bridges differently and grab the speed from the bridge information. I personally would love to use br-mgmt, br-vlan, etc as default values

**Comment by nrb** [comment] 2016-02-01 19:25
No worries. I'd agree with the names for the bridges; those are pretty well established in our product and the upstream project. The "physical" interfaces are more likely to be known on an AIO/virtual environment, but most of my confusion (and it seems others) has been around real hardware NICs.

I believe @tomc603 was referring to agreement that providing defaults for hardware NICs was something we weren't going to do, but rather provide documentation that needs to be done during an actual install. That's done [in this paragraph](https://github.com/rpcdocs/rpcdocs/blob/master/rpc-installation/src/docbkx/ch-operations.xml#L168-L178). Byron provided a patch to make the install fail more gracefully if the variable is undefined, providing a reminder for deployers.

Given all that, I think this particular issue could be closed, and perhaps ones for tweaking the documentation wording (if any are needed) and adding the bridges to monitoring could be opened.

**Comment by tomc603** [comment] 2016-02-01 23:34
Yep. @nrb That's exactly what I was checking. I'd agree that we close this and open docs issues.

**Comment by txgunslinger77** [comment] 2016-03-30 14:43
We (implementation team) just ran into this issue (first time for me) yesterday and were absolutely flummoxed as to why we are hard coding 'eth' anything. Since the advent of 14.04, we stopped using udev naming conventions on all chassis/nics regardless of vendor, and every RPC deployment has been spun up with emX, pXpY or bondX. I do not know what the default should be (bond0 would be great as that covers 99% of deployments we put out), but we don't believe it should reference old naming conventions we haven't used in well over a year, almost two.

**Comment by tomc603** [comment] 2016-03-30 17:53
@txgunslinger77 I think I had exactly that conversation offline, and pointed out that the situation is only made worse by the fact that administrators can rename interfaces to nearly anything they like with a single config entry.

Specifying defaults would make some (but not complete) sense if we had a single hardware spec with a matching BOM on all hosts, and only a single way to utilize interfaces. Basically it makes sense if you're deploying a mogeneous cloud of your own, but probably not for RPC which can be used at RAX or customer data centers.

**Comment by BjoernT** [comment] 2016-03-30 17:59
Yes this is more reason to choose bridges as interfaces which does not work yet. I can work on that since our link speed detection is incomplete

**Comment by tomc603** [comment] 2016-03-31 17:06
As a side note, interfaces have supported aliases for a very long time. If we insist for some reason on hard coding interfaces, it may be easier to rely on an alias which a system administrator configures.

IMO, that's basically equal effort to just specifying interface names in cars files at deploy time, but I figured I'd mention the technical possibility.


--
Tom Cameron

________________________________

**Comment by mancdaz** [comment] 2016-06-13 09:33
@txgunslinger77 in the knowledge that no default is ever going to cover all cases, do you have something that you'd like us to set the default to instead? Would ``bond0`` work for you to cover the large majority of cases?

**Comment by txgunslinger77** [comment] 2016-06-21 14:34
Yes it would, since any deployment we do, whether RAX DC or CDC, we will be
pushing for customers to adopt our reference architecture as closely as
possible, which 95% or more of the time has a bond0. I cannot think of the
last time we did not have bond0, and using that as a default would also
make it independent of the naming convention used for the interfaces.
Whether it's eth0 or em1, if it's part of bond0, it makes no difference the
name of the interfaces comprising the bond (so long as they meet our HA
standard).

**Comment by Frank-ZhangXin** [comment] 2016-09-06 21:15
@git-harry @tomc603 So current goal migrate default interface of network_check_list from eth0 to bond0, right?

**Comment by git-harry** [comment] 2016-09-07 09:30
@Frank-ZhangXin it sounds like it.

@txgunslinger77 to confirm, would the following default, set in https://github.com/rcbops/rpc-openstack/blob/master/rpcd/playbooks/roles/rpc_maas/defaults/main.yml#L360-L361, meet your needs in most cases?
```
network_checks_list:
  - { name: "bond0", group: "hosts", max_speed: "{{ net_max_speed }}", rx_pct_warn: "{{ net_rx_pct_warn }}", rx_pct_crit: "{{ net_rx_pct_crit }}", tx_pct_warn: "{{ net_tx_pct_warn }}", tx_pct_crit: "{{ net_tx_pct_crit }}"}

```

**Comment by BjoernT** [comment] 2016-09-07 14:02
That link still shows eth0.
What I did configure was:

```
network_checks_list:
  - { name: "bond0", group: "hosts", max_speed: "{{ net_max_speed }}", rx_pct_warn: "{{ net_rx_pct_warn }}", rx_pct_crit: "{{ net_rx_pct_crit }}", tx_pct_warn: "{{ net_tx_pct_warn }}", tx_pct_crit: "{{ net_tx_pct_crit }}"}
  - { name: "bond1", group: "hosts", max_speed: "{{ net_max_speed }}", rx_pct_warn: "{{ net_rx_pct_warn }}", rx_pct_crit: "{{ net_rx_pct_crit }}", tx_pct_warn: "{{ net_tx_pct_warn }}", tx_pct_crit: "{{ net_tx_pct_crit }}"}
```

which seem to work

**Comment by Frank-ZhangXin** [comment] 2016-09-09 14:58
Update:
Alternate the default NIC of network_check_list and PR was made.

**Comment by Frank-ZhangXin** [comment] 2016-09-09 20:58
Update:
Got same error consecutively. 
"16:33:27 ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?"
After search I consider it as one tempest unit test, but no idea to fix or improve.

**Comment by prometheanfire** [comment] 2016-09-13 15:15
Upstream openstack infra had to do auto detection for network interfaces, finding the primary default is something we can do by registering the output of this bash as an ansible variable.

    ip -4 r | grep ^default | awk '{print $5}'

if you just want ethernet interfaces you can do something like this, but since we want bonds we'd need to modify it a bit.

    for interface in $(find /sys/class/net/ -maxdepth 1 -type l | rev | cut -d '/' -f 1 | rev); do if [[ $(cat /sys/class/net/"${interface}"/type) -eq 1 ]]; then echo "${interface}" | grep -E '^e.*'; fi; done

**Comment by b3rnard0** [comment] 2016-09-14 14:38
@Frank-ZhangXin Can you please provide an end of day update for this? Thank you!

**Comment by Frank-ZhangXin** [comment] 2016-09-21 15:06
Update: PR passed gate tests and here's the solution: we gather NIC from system through Ansible native module call "ansible_default_ipv4.interface", then replace original static "eth0" with it. So this can be considered as one permanent solution avoid interface messed up.

**Comment by Frank-ZhangXin** [comment] 2016-09-21 15:44
@b3rnard0 @txgunslinger77 Hi, guys. I made one PR to fix this, but not sure what will happen in physical environment on support side. It would be great helpful if you can test on the on-metal server. Thanks!

**Comment by txgunslinger77** [comment] 2016-09-22 18:34
We'll test it, but just so we understand, what happens to bond1?

We have two default network connections - bond0 AND bond1. Bond1 though, does not have an IP, yet is still required for all VM traffic.

Here is what we deploy:
bond0 = host, container, storage networks/vlans (all trunked with host being native)
bond1 = tunnel/overlay, tenant networks

**Comment by claco** [comment] 2016-09-22 18:50
@txgunslinger77 That short answer is nothing. For various reasons in the long comments above, we're un-hard coding the default. This doesn't negate having to configuring things based on the environment (https://github.com/rcbops/rpc-openstack/issues/742#issuecomment-245290040), it just means we stop assuming eth0, when it could be named differently by udev, or in the case of most of our deploys, the bond0.

**Comment by mancdaz** [comment] 2016-09-26 08:04
@Frank-ZhangXin master review has now merged. Please backport where necessary, and update the various sections of the issue description above.

**Comment by Frank-ZhangXin** [comment] 2016-09-28 14:37
@mancdaz will do, thanks for noticing me.

**Comment by sigmavirus24** [comment] 2016-10-07 15:01
Backports for both mitaka branches and kilo are done. I also updated the list of branches with the PR numbers to make it easier to find them.

**Comment by tomc603** [comment] 2016-10-08 04:34
The last backport has merged. I don't think it requires a release note, since it's just changing a default to a more sensible value. But I'm not confident enough to move this issue to Done. If anybody has an opinion one way or the other, let me know.

**Closed** 2016-10-10 14:23 UTC
Labels: feature-monitoring, impacts-doc, prio-2, swimlane-rr, type-bug

**Comment by sigmavirus24** [comment] 2016-10-10 14:27
https://waffle.io/rcbops/u-suk-dev/cards/57fba52f04d67ef8001ed18a is the card for release notes
