### ISSUE TITLE
L>M Upgrade: Cinder volume status metric errors after upgrade

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1487] opened 2016-10-11 15:10 UTC
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

r13.1.0rc1
13.3.4-1-ga489036

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

No maas alerts

##### What is actually happening?

Seems like we removed the ordinary metric cinder_volume_check per https://github.com/rcbops/rpc-openstack/commit/e1dd1a4ab74d8de14d6ffedb7d53b3c6d6d913c0 but did not include a cleanup step in the rpc_maas role so all cinder nodes alarmed after the upgrade.

##### How can we reproduce this issue?

Upgrade L to M

##### How can we verify your issue is addressed?

No alarms after the upgrade

##### If you are using or know of a workaround please describe the necessary steps?

Manually removed the check 

##### What is your evaluation on the importance of this issue, and why?

Prio 2

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.0
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by git-harry** [comment] 2016-10-17 12:33
The MaaS agent automatically cleans up checks/alarms when it is restarted based on the files in /etc/rackspace-monitoring-agent.conf.d. Based on the information this appears to be a duplicate of https://github.com/rcbops/u-suk-dev/issues/481 which has been addressed in r13.1.0rc2.

**Closed by git-harry** 2016-10-17 12:33 UTC
