### ISSUE TITLE
[r12.0.0rc2] — Neutron failing to bind ports when creating instances

### ISSUE THREAD

**Issue by jpmontez** [rcbops/rpc-openstack#897] opened 2016-03-14 22:13 UTC
##### What version (commit) do you encounter this issue on?
r12.0.0rc2

##### What type of issue is this (bug, feature, documentation, regression)?
Bug

##### What is the expected behavior?
To create a successful VM with the `openstack server create` command

##### What is actually happening?
The instance fails to build. An exception is raised in the Nova and Neutron logs.

The logs show that the internal endpoints aren't being used by the Neutron service, but rather the public ones. Because the firewall doesn't allow public API access, connections fail and exceptions are raised.

##### How can we reproduce this issue?
Within a customer lab behind a firewall w/ no public access to the APIs, try and create a server.

##### How can we verify your issue is addressed?
By logging into the QE team's Sydney lab and using the utility container to try and create a basic server.

`openstack server create --flavor 2 --image cirros --nic net-id=XXX test`

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?
Possibly by force overriding the endpoint used by the Keystone adaptor

##### What is your evaluation on the importance of this issue, and why?
If the internal URL isn't respected, many services involving Neutron and Keystone will break.

##### What branches / milestones do you believe this issue should target?
The list below is what is currently supported for backports, remove branches you do not wish to target.
- [ ] Master
- [x] liberty-12.0

```
root@627551-infra01_utility_container-2484aa62:~# openstack server create --flavor 2 --image cirros --nic net-id=5fadf69c-136f-499d-9f3d-9e79f9bea358 --wait test
Error creating server: test
```

Relevant Neutron log:
```
2016-03-15 09:09:11.149 3114 ERROR neutron.notifiers.nova [-] Failed to notify nova on events: [{'tag': u'12c3241e-e54e-457c-976c-ef0e4be6b3b9', 'name': 'network-vif-deleted', 'server_uuid': u'f5176db2-4604-4917-9987-303616088744'}]
2016-03-15 09:09:11.149 3114 ERROR neutron.notifiers.nova Traceback (most recent call last):
2016-03-15 09:09:11.149 3114 ERROR neutron.notifiers.nova   File "/openstack/venvs/neutron-12.0.7/lib/python2.7/site-packages/neutron/notifiers/nova.py", line 247, in send_events
2016-03-15 09:09:11.149 3114 ERROR neutron.notifiers.nova     batched_events)
2016-03-15 09:09:11.149 3114 ERROR neutron.notifiers.nova   File "/openstack/venvs/neutron-12.0.7/lib/python2.7/site-packages/novaclient/v2/contrib/server_external_events.py", line 39, in create
2016-03-15 09:09:11.149 3114 ERROR neutron.notifiers.nova     return_raw=True)
2016-03-15 09:09:11.149 3114 ERROR neutron.notifiers.nova   File "/openstack/venvs/neutron-12.0.7/lib/python2.7/site-packages/novaclient/base.py", line 172, in _create
2016-03-15 09:09:11.149 3114 ERROR neutron.notifiers.nova     _resp, body = self.api.client.post(url, body=body)
2016-03-15 09:09:11.149 3114 ERROR neutron.notifiers.nova   File "/openstack/venvs/neutron-12.0.7/lib/python2.7/site-packages/keystoneclient/adapter.py", line 176, in post
2016-03-15 09:09:11.149 3114 ERROR neutron.notifiers.nova     return self.request(url, 'POST', **kwargs)
2016-03-15 09:09:11.149 3114 ERROR neutron.notifiers.nova   File "/openstack/venvs/neutron-12.0.7/lib/python2.7/site-packages/novaclient/client.py", line 91, in request
2016-03-15 09:09:11.149 3114 ERROR neutron.notifiers.nova     **kwargs)
2016-03-15 09:09:11.149 3114 ERROR neutron.notifiers.nova   File "/openstack/venvs/neutron-12.0.7/lib/python2.7/site-packages/keystoneclient/adapter.py", line 206, in request
2016-03-15 09:09:11.149 3114 ERROR neutron.notifiers.nova     resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
2016-03-15 09:09:11.149 3114 ERROR neutron.notifiers.nova   File "/openstack/venvs/neutron-12.0.7/lib/python2.7/site-packages/keystoneclient/adapter.py", line 95, in request
2016-03-15 09:09:11.149 3114 ERROR neutron.notifiers.nova     return self.session.request(url, method, **kwargs)
2016-03-15 09:09:11.149 3114 ERROR neutron.notifiers.nova   File "/openstack/venvs/neutron-12.0.7/lib/python2.7/site-packages/keystoneclient/utils.py", line 337, in inner
2016-03-15 09:09:11.149 3114 ERROR neutron.notifiers.nova     return func(*args, **kwargs)
2016-03-15 09:09:11.149 3114 ERROR neutron.notifiers.nova   File "/openstack/venvs/neutron-12.0.7/lib/python2.7/site-packages/keystoneclient/session.py", line 390, in request
2016-03-15 09:09:11.149 3114 ERROR neutron.notifiers.nova     resp = send(**kwargs)
2016-03-15 09:09:11.149 3114 ERROR neutron.notifiers.nova   File "/openstack/venvs/neutron-12.0.7/lib/python2.7/site-packages/keystoneclient/session.py", line 434, in _send_request
2016-03-15 09:09:11.149 3114 ERROR neutron.notifiers.nova     raise exceptions.ConnectionRefused(msg)
2016-03-15 09:09:11.149 3114 ERROR neutron.notifiers.nova ConnectFailure: Unable to establish connection to http://119.XXX:8774/v2.1/f193144181954dfc973717808068b3ee/os-server-external-events
```

Note that 119.XX is the public IP address for the environment. The correct, internal IP address begins with 172.20.XX.

**Comment by jacobwagner** [comment] 2016-03-15 20:19
Some more interesting information on this bug

This is a failure in the callback for the /os-server-external-event endpoint in neutron. 

For all new networks created the first instance spun up on that network will fail due to nova making the following request

Nova is booting a guest and asks Neutron to plumb the VIFs. It makes that request and then blocks the boot while waiting for the callback from Neutron. When Neutron has completed, it sends an event of type "network-vif-plugged" with the tag set to the port_id of the relevant VIF for the affected instance. When all of the vif-plugged events have been received, Nova continues the boot process.

from: https://wiki.openstack.org/wiki/Nova/ExternalEventAPI

Once the VIF is created in neutron for the network all future calls to add a guest to that network will no longer make that exteral call and since neutron succeed in creating the vif for the network, all future guest boots on the network will succeed.

```
root@573956-infra01_neutron_agents_container-cef0a68a:~# neutron net-create jake-private --provider:network_type=vxlan --provider:segmentation_id=1000 --router:external=False --shared
Created a new network:
+---------------------------+--------------------------------------+
| Field                     | Value                                |
+---------------------------+--------------------------------------+
| admin_state_up            | True                                 |
| id                        | dc218ead-4453-4e2e-a47f-4d8b7b2a973f |
| mtu                       | 0                                    |
| name                      | jake-private                         |
| port_security_enabled     | True                                 |
| provider:network_type     | vxlan                                |
| provider:physical_network |                                      |
| provider:segmentation_id  | 1000                                 |
| router:external           | False                                |
| shared                    | True                                 |
| status                    | ACTIVE                               |
| subnets                   |                                      |
| tenant_id                 | 554a61b19b4647aabe7e97cde7b014a1     |
+---------------------------+--------------------------------------+
root@573956-infra01_neutron_agents_container-cef0a68a:~# neutron subnet-create jake-private 172.31.1.0/24 --name jake-private-subnet --gateway 172.31.1.1 --dns-nameservers list=true 8.8.8.8 8.8.4.4
Created a new subnet:
+-------------------+------------------------------------------------+
| Field             | Value                                          |
+-------------------+------------------------------------------------+
| allocation_pools  | {"start": "172.31.1.2", "end": "172.31.1.254"} |
| cidr              | 172.31.1.0/24                                  |
| dns_nameservers   | 8.8.8.8                                        |
|                   | 8.8.4.4                                        |
| enable_dhcp       | True                                           |
| gateway_ip        | 172.31.1.1                                     |
| host_routes       |                                                |
| id                | 124efb01-85fb-4835-9ac8-c731b0cc5148           |
| ip_version        | 4                                              |
| ipv6_address_mode |                                                |
| ipv6_ra_mode      |                                                |
| name              | jake-private-subnet                            |
| network_id        | dc218ead-4453-4e2e-a47f-4d8b7b2a973f           |
| subnetpool_id     |                                                |
| tenant_id         | 554a61b19b4647aabe7e97cde7b014a1               |
+-------------------+------------------------------------------------+
```
```
root@573956-infra01_utility_container-9c0cf7e8:~# nova boot --flavor 1 --image cirros --nic net-id=dc218ead-4453-4e2e-a47f-4d8b7b2a973f --security-group e6fcc218-c7cc-4a4f-829d-9100a8bf859b jake-test-3 --poll
+--------------------------------------+-----------------------------------------------+
| Property                             | Value                                         |
+--------------------------------------+-----------------------------------------------+
| OS-DCF:diskConfig                    | MANUAL                                        |
| OS-EXT-AZ:availability_zone          |                                               |
| OS-EXT-SRV-ATTR:host                 | -                                             |
| OS-EXT-SRV-ATTR:hostname             | jake-test-3                                   |
| OS-EXT-SRV-ATTR:hypervisor_hostname  | -                                             |
| OS-EXT-SRV-ATTR:instance_name        | instance-0000016f                             |
| OS-EXT-SRV-ATTR:kernel_id            |                                               |
| OS-EXT-SRV-ATTR:launch_index         | 0                                             |
| OS-EXT-SRV-ATTR:ramdisk_id           |                                               |
| OS-EXT-SRV-ATTR:reservation_id       | r-c9gaqgp4                                    |
| OS-EXT-SRV-ATTR:root_device_name     | -                                             |
| OS-EXT-SRV-ATTR:user_data            | -                                             |
| OS-EXT-STS:power_state               | 0                                             |
| OS-EXT-STS:task_state                | scheduling                                    |
| OS-EXT-STS:vm_state                  | building                                      |
| OS-SRV-USG:launched_at               | -                                             |
| OS-SRV-USG:terminated_at             | -                                             |
| accessIPv4                           |                                               |
| accessIPv6                           |                                               |
| adminPass                            | fJNaaHjQ8mTF                                  |
| config_drive                         |                                               |
| created                              | 2016-03-15T20:11:17Z                          |
| flavor                               | m1.tiny (1)                                   |
| hostId                               |                                               |
| id                                   | 8d0bd5cb-9da3-4092-8790-939a23d45654          |
| image                                | cirros (83fff0fd-cb7f-4f97-8d03-9584df533781) |
| key_name                             | -                                             |
| metadata                             | {}                                            |
| name                                 | jake-test-3                                   |
| os-extended-volumes:volumes_attached | []                                            |
| progress                             | 0                                             |
| security_groups                      | e6fcc218-c7cc-4a4f-829d-9100a8bf859b          |
| status                               | BUILD                                         |
| tenant_id                            | 554a61b19b4647aabe7e97cde7b014a1              |
| updated                              | 2016-03-15T20:11:17Z                          |
| user_id                              | d74c4cfc166a4b92bc5f2b90f0ecf050              |
+--------------------------------------+-----------------------------------------------+

Server building... 0% complete
Error building server
ERROR (InstanceInErrorState): No valid host was found. There are not enough hosts available.
```
```
2016-03-15 16:11:25.254 31070 ERROR neutron.notifiers.nova [-] Failed to notify nova on events: [{'name': 'network-changed', 'server_uuid': u'8d0bd5cb-9da3-4092-8790-939a23d45654'}]
2016-03-15 16:11:25.254 31070 ERROR neutron.notifiers.nova Traceback (most recent call last):
2016-03-15 16:11:25.254 31070 ERROR neutron.notifiers.nova   File "/openstack/venvs/neutron-12.0.7/lib/python2.7/site-packages/neutron/notifiers/nova.py", line 247, in send_events
2016-03-15 16:11:25.254 31070 ERROR neutron.notifiers.nova     batched_events)
2016-03-15 16:11:25.254 31070 ERROR neutron.notifiers.nova   File "/openstack/venvs/neutron-12.0.7/lib/python2.7/site-packages/novaclient/v2/contrib/server_external_events.py", line 39, in create
2016-03-15 16:11:25.254 31070 ERROR neutron.notifiers.nova     return_raw=True)
2016-03-15 16:11:25.254 31070 ERROR neutron.notifiers.nova   File "/openstack/venvs/neutron-12.0.7/lib/python2.7/site-packages/novaclient/base.py", line 172, in _create
2016-03-15 16:11:25.254 31070 ERROR neutron.notifiers.nova     _resp, body = self.api.client.post(url, body=body)
2016-03-15 16:11:25.254 31070 ERROR neutron.notifiers.nova   File "/openstack/venvs/neutron-12.0.7/lib/python2.7/site-packages/keystoneclient/adapter.py", line 176, in post
2016-03-15 16:11:25.254 31070 ERROR neutron.notifiers.nova     return self.request(url, 'POST', **kwargs)
2016-03-15 16:11:25.254 31070 ERROR neutron.notifiers.nova   File "/openstack/venvs/neutron-12.0.7/lib/python2.7/site-packages/novaclient/client.py", line 91, in request
2016-03-15 16:11:25.254 31070 ERROR neutron.notifiers.nova     **kwargs)
2016-03-15 16:11:25.254 31070 ERROR neutron.notifiers.nova   File "/openstack/venvs/neutron-12.0.7/lib/python2.7/site-packages/keystoneclient/adapter.py", line 206, in request
2016-03-15 16:11:25.254 31070 ERROR neutron.notifiers.nova     resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
2016-03-15 16:11:25.254 31070 ERROR neutron.notifiers.nova   File "/openstack/venvs/neutron-12.0.7/lib/python2.7/site-packages/keystoneclient/adapter.py", line 95, in request
2016-03-15 16:11:25.254 31070 ERROR neutron.notifiers.nova     return self.session.request(url, method, **kwargs)
2016-03-15 16:11:25.254 31070 ERROR neutron.notifiers.nova   File "/openstack/venvs/neutron-12.0.7/lib/python2.7/site-packages/keystoneclient/utils.py", line 337, in inner
2016-03-15 16:11:25.254 31070 ERROR neutron.notifiers.nova     return func(*args, **kwargs)
2016-03-15 16:11:25.254 31070 ERROR neutron.notifiers.nova   File "/openstack/venvs/neutron-12.0.7/lib/python2.7/site-packages/keystoneclient/session.py", line 390, in request
2016-03-15 16:11:25.254 31070 ERROR neutron.notifiers.nova     resp = send(**kwargs)
2016-03-15 16:11:25.254 31070 ERROR neutron.notifiers.nova   File "/openstack/venvs/neutron-12.0.7/lib/python2.7/site-packages/keystoneclient/session.py", line 434, in _send_request
2016-03-15 16:11:25.254 31070 ERROR neutron.notifiers.nova     raise exceptions.ConnectionRefused(msg)
2016-03-15 16:11:25.254 31070 ERROR neutron.notifiers.nova ConnectFailure: Unable to establish connection to http://204.232.187.36:8774/v2.1/40b2b559bd4c42ad997d9b42ab3ac885/os-server-external-events
2016-03-15 16:11:25.254 31070 ERROR neutron.notifiers.nova
```
```
root@573956-infra01_utility_container-9c0cf7e8:~# nova boot --flavor 1 --image cirros --nic net-id=dc218ead-4453-4e2e-a47f-4d8b7b2a973f --security-group e6fcc218-c7cc-4a4f-829d-9100a8bf859b jake-test-4 --poll
+--------------------------------------+-----------------------------------------------+
| Property                             | Value                                         |
+--------------------------------------+-----------------------------------------------+
| OS-DCF:diskConfig                    | MANUAL                                        |
| OS-EXT-AZ:availability_zone          |                                               |
| OS-EXT-SRV-ATTR:host                 | -                                             |
| OS-EXT-SRV-ATTR:hostname             | jake-test-4                                   |
| OS-EXT-SRV-ATTR:hypervisor_hostname  | -                                             |
| OS-EXT-SRV-ATTR:instance_name        | instance-00000172                             |
| OS-EXT-SRV-ATTR:kernel_id            |                                               |
| OS-EXT-SRV-ATTR:launch_index         | 0                                             |
| OS-EXT-SRV-ATTR:ramdisk_id           |                                               |
| OS-EXT-SRV-ATTR:reservation_id       | r-6vnsos87                                    |
| OS-EXT-SRV-ATTR:root_device_name     | -                                             |
| OS-EXT-SRV-ATTR:user_data            | -                                             |
| OS-EXT-STS:power_state               | 0                                             |
| OS-EXT-STS:task_state                | scheduling                                    |
| OS-EXT-STS:vm_state                  | building                                      |
| OS-SRV-USG:launched_at               | -                                             |
| OS-SRV-USG:terminated_at             | -                                             |
| accessIPv4                           |                                               |
| accessIPv6                           |                                               |
| adminPass                            | oRzLKjuCK62Q                                  |
| config_drive                         |                                               |
| created                              | 2016-03-15T20:12:21Z                          |
| flavor                               | m1.tiny (1)                                   |
| hostId                               |                                               |
| id                                   | 7aad7070-b265-4597-bf7b-6de5fe49ffed          |
| image                                | cirros (83fff0fd-cb7f-4f97-8d03-9584df533781) |
| key_name                             | -                                             |
| metadata                             | {}                                            |
| name                                 | jake-test-4                                   |
| os-extended-volumes:volumes_attached | []                                            |
| progress                             | 0                                             |
| security_groups                      | e6fcc218-c7cc-4a4f-829d-9100a8bf859b          |
| status                               | BUILD                                         |
| tenant_id                            | 554a61b19b4647aabe7e97cde7b014a1              |
| updated                              | 2016-03-15T20:12:22Z                          |
| user_id                              | d74c4cfc166a4b92bc5f2b90f0ecf050              |
+--------------------------------------+-----------------------------------------------+

Server building... 100% complete
Finished
```

**Comment by nrb** [comment] 2016-03-16 15:22
For reference - this behavior appears be happening on upgrades, too, though my greenfield AIOs seem to work.

Is the `neutron.networksecuritybindings` table populated? When my creations fail, I've noticed this is empty. When I manually add the network entries, creation succeeds.

**Comment by nrb** [comment] 2016-03-16 15:31
On my AIO, I don't see the neutron log failures.

```
root@nolan:/opt/openstack-ansible# lxc-attach -n aio1_neutron_server_container-87e923e9
root@aio1_neutron_server_container-87e923e9:/# cd /var/log/neutron/
root@aio1_neutron_server_container-87e923e9:/var/log/neutron# grep 'Unable to establish' *
root@aio1_neutron_server_container-87e923e9:/var/log/neutron# grep 'Unable to establish' *.log
root@aio1_neutron_server_container-87e923e9:/var/log/neutron# grep 'ConnectFailure'
root@aio1_neutron_server_container-87e923e9:/var/log/neutron# grep 'ConnectFailure' *
```

**Comment by nrb** [comment] 2016-03-16 15:58
Also, on both my greenfield and upgrade installs, the neutron.conf points to the internalURL for nova. However, these are AIOs, too.

**Comment by prometheanfire** [comment] 2016-03-16 16:24
https://github.com/openstack/neutron/blob/stable/liberty/neutron/db/migration/alembic_migrations/versions/35a0f3365720_add_port_security_in_ml2.py#L46-L54

https://bugs.launchpad.net/neutron/+bug/1509312

for refrence

**Comment by nrb** [comment] 2016-03-16 16:33
This change may also relate to greenfields. https://github.com/openstack/openstack-ansible-os_neutron/commit/b58230d1367cbb12b00a2c86c5cbeb8ec10db22b Note that happened in master, hasn't been backported to liberty.

**Comment by prometheanfire** [comment] 2016-03-16 20:24
ok, think we figured it out

The migration occurred before the kilo branch was tagged, you can see that in the history below. Also, during kilo that table was not populated. Any ports/networks created during the time kilo was deployed needs to be re-migrated when the liberty upgrade is done as those tables were not populated, once liberty is deployed those tables are populated properly.

1. kilo had the migration already run
2. kilo did not populate the tables when new ports/networks were created
3. liberty does populate the tables when new ports/networks are created
4. liberty needs to re-migrate those ports/networks to the tables

**Comment by prometheanfire** [comment] 2016-03-16 20:28
we could also just add a post-upgrade action to run the sql query ourselves, this is what I'd do if upstream sucks

**Comment by nrb** [comment] 2016-03-16 21:07
@prometheanfire I think this issue is completely separate, but with a different end result. This one is within a greenfield environment and appears to be related to URL/URI differences. This patch in particular is what should hopefully fix it: https://github.com/openstack/openstack-ansible-os_neutron/commit/b58230d1367cbb12b00a2c86c5cbeb8ec10db22b

**Comment by prometheanfire** [comment] 2016-03-16 21:11
if ours is new then I think we need a new issue

**Comment by nrb** [comment] 2016-03-17 15:18
@prometheanfire agreed - let's use https://bugs.launchpad.net/neutron/+bug/1509312 for it.

**Comment by tomc603** [comment] 2016-03-17 16:43
A potential fix for this has been submitted here [294132](https://review.openstack.org/#/c/294132/). I'm about to test this on my second AIO.

**Comment by nrb** [comment] 2016-03-17 16:48
@tomc603 this issue is separate from the upgrade. Looking at the logs posted, this one has to do with URL permissions, not with the port bindings.

**Comment by tomc603** [comment] 2016-03-17 16:53
Sorry, I mixed up the issue repos. Deleting my comment.

**Comment by d34dh0r53** [comment] 2016-03-17 19:17
I'm not able to recreate this in a fresh `12.0.0rc2` multi-node lab.  @jacobwagner is there any way we can get onto the Sydney environment you're working with?

**Comment by d34dh0r53** [comment] 2016-03-17 20:23
@jpmontez can you let us know if we can get on that lab?

**Comment by d34dh0r53** [comment] 2016-03-17 21:40
So I've manually applied the patches in this bug: https://bugs.launchpad.net/openstack-ansible/liberty/+bug/1552394 and the `openstack server create --flavor 2 --image cirros --nic net-id=5fadf69c-136f-499d-9f3d-9e79f9bea358 --wait test` command completes successfully now:

```
openstack server create --flavor 2 --image cirros --nic net-id=5fadf69c-136f-499d-9f3d-9e79f9bea358 --wait test

+--------------------------------------+----------------------------------------------------------+
| Field                                | Value                                                    |
+--------------------------------------+----------------------------------------------------------+
| OS-DCF:diskConfig                    | MANUAL                                                   |
| OS-EXT-AZ:availability_zone          | nova                                                     |
| OS-EXT-SRV-ATTR:host                 | 627558-compute03                                         |
| OS-EXT-SRV-ATTR:hypervisor_hostname  | 627558-compute03                                         |
| OS-EXT-SRV-ATTR:instance_name        | instance-00000270                                        |
| OS-EXT-STS:power_state               | 1                                                        |
| OS-EXT-STS:task_state                | None                                                     |
| OS-EXT-STS:vm_state                  | active                                                   |
| OS-SRV-USG:launched_at               | 2016-03-17T21:37:38.000000                               |
| OS-SRV-USG:terminated_at             | None                                                     |
| accessIPv4                           |                                                          |
| accessIPv6                           |                                                          |
| addresses                            | private=192.168.74.9                                     |
| adminPass                            | 5p2gMwons5WW                                             |
| config_drive                         |                                                          |
| created                              | 2016-03-17T21:37:23Z                                     |
| flavor                               | m1.small (2)                                             |
| hostId                               | a5626ae6b1d2faa6311492b259f3c600e5aae66113fdba4b658c13a8 |
| id                                   | 80cfbc61-2e00-4057-883b-70de71390640                     |
| image                                | cirros (9405745a-bbb2-4729-8438-b4b17e066532)            |
| key_name                             | None                                                     |
| name                                 | test                                                     |
| os-extended-volumes:volumes_attached | []                                                       |
| progress                             | 0                                                        |
| project_id                           | c8e8f1ea3cbf4c9c83b72a306f84f635                         |
| properties                           |                                                          |
| security_groups                      | [{u'name': u'default'}]                                  |
| status                               | ACTIVE                                                   |
| updated                              | 2016-03-17T21:37:38Z                                     |
| user_id                              | 72be81a2ad004cd79f4fdd00e84e7482                         |
+--------------------------------------+----------------------------------------------------------+
root@627551-infra01_utility_container-2484aa62:~# nova list
+--------------------------------------+------+--------+------------+-------------+----------------------+
| ID                                   | Name | Status | Task State | Power State | Networks             |
+--------------------------------------+------+--------+------------+-------------+----------------------+
| 80cfbc61-2e00-4057-883b-70de71390640 | test | ACTIVE | -          | Running     | private=192.168.74.9 |
| f5176db2-4604-4917-9987-303616088744 | test | ERROR  | -          | NOSTATE     |                      |
| f68b2f68-8fe8-444a-aba1-f8b6bdad19c4 | test | ERROR  | -          | NOSTATE     |                      |
+--------------------------------------+------+--------+------------+-------------+----------------------+
root@627551-infra01_utility_container-2484aa62:~# nova show 80cfbc61-2e00-4057-883b-70de71390640
+--------------------------------------+----------------------------------------------------------+
| Property                             | Value                                                    |
+--------------------------------------+----------------------------------------------------------+
| OS-DCF:diskConfig                    | MANUAL                                                   |
| OS-EXT-AZ:availability_zone          | nova                                                     |
| OS-EXT-SRV-ATTR:host                 | 627558-compute03                                         |
| OS-EXT-SRV-ATTR:hostname             | test                                                     |
| OS-EXT-SRV-ATTR:hypervisor_hostname  | 627558-compute03                                         |
| OS-EXT-SRV-ATTR:instance_name        | instance-00000270                                        |
| OS-EXT-SRV-ATTR:kernel_id            |                                                          |
| OS-EXT-SRV-ATTR:launch_index         | 0                                                        |
| OS-EXT-SRV-ATTR:ramdisk_id           |                                                          |
| OS-EXT-SRV-ATTR:reservation_id       | r-im5kbt77                                               |
| OS-EXT-SRV-ATTR:root_device_name     | /dev/vda                                                 |
| OS-EXT-SRV-ATTR:user_data            | -                                                        |
| OS-EXT-STS:power_state               | 1                                                        |
| OS-EXT-STS:task_state                | -                                                        |
| OS-EXT-STS:vm_state                  | active                                                   |
| OS-SRV-USG:launched_at               | 2016-03-17T21:37:38.000000                               |
| OS-SRV-USG:terminated_at             | -                                                        |
| accessIPv4                           |                                                          |
| accessIPv6                           |                                                          |
| config_drive                         |                                                          |
| created                              | 2016-03-17T21:37:23Z                                     |
| flavor                               | m1.small (2)                                             |
| hostId                               | a5626ae6b1d2faa6311492b259f3c600e5aae66113fdba4b658c13a8 |
| id                                   | 80cfbc61-2e00-4057-883b-70de71390640                     |
| image                                | cirros (9405745a-bbb2-4729-8438-b4b17e066532)            |
| key_name                             | -                                                        |
| metadata                             | {}                                                       |
| name                                 | test                                                     |
| os-extended-volumes:volumes_attached | []                                                       |
| private network                      | 192.168.74.9                                             |
| progress                             | 0                                                        |
| security_groups                      | default                                                  |
| status                               | ACTIVE                                                   |
| tenant_id                            | c8e8f1ea3cbf4c9c83b72a306f84f635                         |
| updated                              | 2016-03-17T21:37:38Z                                     |
| user_id                              | 72be81a2ad004cd79f4fdd00e84e7482                         |
+--------------------------------------+----------------------------------------------------------+
```

@jpmontez @jacobwagner can you please test and verify that I'm not missing anything?

**Comment by jacobwagner** [comment] 2016-03-18 15:29
@d34dh0r53 Did you test this in a lab with a actual external vip. Also the external vips port would have to be disabled for the neutron service to see this. While customers ports would normally be open this is still tech a bug as the clients shouldn't be using the extenral URL for requests.

**Comment by d34dh0r53** [comment] 2016-03-18 18:45
hey @jacobwagner @jpmontez we're reverted the patch that I applied to the Sydney lab and for some reason I cannot recreate this.  Do you have a fresh liberty lab that we can see this in action on?  A vidyo may be necessary.

**Comment by weezer** [comment] 2016-03-19 21:50
So after looking hard for a problem with internal URLs from Neutron in Liberty an OpenStack Ansible community member (LoganV-) found this: https://review.openstack.org/#/c/254900/

Which was an issue in Mitaka and is still an issue in Liberty. This is a cherry-pick from master being backported to Stable/Liberty. This is the cherry-picked commit: https://review.openstack.org/#/c/291810/

This is something that we're going to need to test and to help push into liberty if we're going to get it in.

**Comment by git-harry** [comment] 2016-03-21 17:08
From reading [1] it sounds like this issue is specific to Keystone v3, does that mean we could override the Neutron auth vars and use v2 instead to get this to work?

[1] https://bugs.launchpad.net/neutron/+bug/1478471

**Comment by git-harry** [comment] 2016-03-22 11:45
To follow up on my previous comment, I tested using v2.0 and the same issue exists.

**Comment by d34dh0r53** [comment] 2016-03-22 14:47
So, I've tested [`291810`](https://review.openstack.org/#/c/291810/4) in the IAD lab and it seems to be working.  I did have to add the FQDN to the computes `/etc/hosts` files to mitigate this error:

```
Mar 21 13:53:59 573956-infra01_nova_conductor_container-a1d85844 nova-conductor: 2016-03-21 13:53:54.744 20950 ERROR nova.scheduler.utils [req-71bd6b83-9cae-4d18-86f6-5b1987c8666d d74c4cfc166a4b92bc5f2b90f0ecf050 554a61b19b4647aabe7e97cde7b014a1 - - -] [instance: 6f83462c-9335-44db-9921-482f35a41b89] Error from last host: 573962-compute03.qe-iad3-2.rpc.rackspace.com (node 573962-compute03.qe-iad3-2.rpc.rackspace.com): [u'Traceback (most recent call last):
', u'  File "/openstack/venvs/nova-12.0.8/lib/python2.7/site-packages/nova/compute/manager.py", line 1905, in _do_build_and_run_instance
    filter_properties)
', u'  File "/openstack/venvs/nova-12.0.8/lib/python2.7/site-packages/nova/compute/manager.py", line 2057, in _build_and_run_instance
    instance_uuid=instance.uuid, reason=six.text_type(e))
', u'RescheduledException: Build of instance 6f83462c-9335-44db-9921-482f35a41b89 was re-scheduled: Failed to add bridge: sudo: unable to resolve host 573962-compute03.qe-iad3-2.rpc.rackspace.com

']
```

I had to modify each computes `/etc/hosts` file to include the FQDN after the shortname entry, not sure if this will be a problem on a fresh deploy with this patch included.

**Comment by d34dh0r53** [comment] 2016-03-28 18:06
A couple of more issues with this one, first off we missed a new entry in `neutron.conf.j2` where we need to specify the endpoint type in the `[nova]` section of the conf:

```
# Type of the nova endpoint to use. This endpoint will be looked up in the
# keystone catalog and should be one of public, internal or admin.
# endpoint_type = public
```

The second issue is that the endpoints in `nova service-list` uses the FQDN of the hosts, but our hosts files are only populated with the shortname.

**Comment by d34dh0r53** [comment] 2016-03-28 19:28
@jacobwagner after looking into it some more I think the problem is with the way your QE lab lays down it's hosts files.  In a default ubuntu hosts file the FQDN is specified on the second line of `/etc/hosts`:

```
127.0.0.1       localhost
127.0.1.1       infra1.openstackci.local        infra1

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

As you can see the `localhost` ip of `127.0.1.1` has the FQDN `infra.openstackci.local` set on this fresh instance of ubuntu.  Your hosts files only have the short name:

```
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters
```

And are missing the `127.0.1.1` entry.  I'm not sure how you're laying down the `/etc/hosts` files in the labs but adding that second line should fix the unknown host nova error we`re seeing.

**Comment by jacobwagner** [comment] 2016-03-28 20:46
@d34dh0r53 We dont lay the images down we use KiR. I will look into how they lay down /etc/hosts for localhost

**Comment by d34dh0r53** [comment] 2016-03-28 21:03
@jacobwagner thanks, let me know

**Comment by jacobwagner** [comment] 2016-03-28 21:13
Our sat6 lab shows the 1.1 entry

```
root@node84:/opt/rpc-openstack# cat /etc/hosts
127.0.0.1	localhost
127.0.1.1	node84.sat6.lab	node84
```

And we dont run anything differently here that we do in the release labs, so it has to be either a lem or KiR issue

**Closed** 2016-03-30 08:16 UTC
Labels: prio-1, status-blocked, status-doing
