### ISSUE TITLE
neutron metadata check uses incorrect address

### ISSUE THREAD

**Issue by toxick** [rcbops/rpc-openstack#569] opened 2015-11-10 15:46 UTC
neutron_metadata_local_check.py uses 127.0.0.1:80 for testing metadata proxy when it should be using 169.254.169.254:80:

[ distributed version ]
**# grep ^SERVICE_CHECK ./neutron_metadata_local_check.py**
SERVICE_CHECK = 'ip netns exec %s curl -fvs 127.0.0.1:80'
**# ./neutron_metadata_local_check.py 172.24.240.49**
status error neutron metadata agent proxies fail on host [clip]_neutron_agents_container-7576f37a net_ids: 993b54c7-10aa-43b1-80e7-67a579a02eea

[...fix fix fix...]
**# grep ^SERVICE_CHECK ./neutron_metadata_local_check.py**
SERVICE_CHECK = 'ip netns exec %s curl -fvs 169.254.169.254:80'
**# ./neutron_metadata_local_check.py 172.24.240.49**
status okay
metric neutron-metadata-agent-proxy_status uint32 1

**Comment by git-harry** [comment] 2015-11-17 13:32
I'm unable to reproduce this bug. On my test cluster the proxy is listening on both:

# tail -n4 /var/log/neutron/neutron-ns-metadata-proxy-9097ef9d-d0e9-4980-8926-d7e1a115cc80.log
2015-11-17 13:25:07.177 4613 INFO neutron.wsgi [-] (4613) accepted ('169.254.169.254', 41353)
2015-11-17 13:25:07.208 4613 INFO neutron.wsgi [-] 169.254.169.254 - - [17/Nov/2015 13:25:07] "GET / HTTP/1.1" 404 278 0.029188
2015-11-17 13:26:11.590 4613 INFO neutron.wsgi [-] (4613) accepted ('127.0.0.1', 59397)
2015-11-17 13:26:11.628 4613 INFO neutron.wsgi [-] 127.0.0.1 - - [17/Nov/2015 13:26:11] "GET / HTTP/1.1" 404 278 0.036527

That said I believe 169.254.169.254 is the address used by the nova instances and so it does strike me as more appropriate to be using that IP address. @stevelle, I see you wrote the plugin, can you give any additional details.

**Comment by stevelle** [comment] 2015-11-17 17:44
I tested both 169.254.169.254 and 127.0.0.1 and they worked in my limited testing. That said, 169.254.169.254 is an appropriate target address and I'm +1 on a change to the host here.

**Comment by BjoernT** [comment] 2015-11-30 17:29
The support assumption is that the issue is not fully fixed,  especially once a network is attached and doesn't account for neutron router changes where the instances have static metadata routes in place when they shouldn't. From that perspective I would remove this check from the maas playbooks in all RPC openstack versions until this check work with any Neutron L3 constellation

**Comment by mancdaz** [comment] 2015-12-03 10:47
master is currently failing to deploy since the above commit, after removing the template, because we're still trying to drop it and it doesn't exist:

```
fatal: [master-node3_neutron_agents_container-57911f1f -> master-node3] => input file not found at /opt/rpc-openstack/rpcd/playbooks/roles/rpc_maas/templates/neutron_metadata_agent_proxy_check.yaml.j2 or /opt/rpc-openstack/rpcd/playbooks/neutron_metadata_agent_proxy_check.yaml.j2
fatal: [master-node1_neutron_agents_container-99636152 -> master-node1] => input file not found at /opt/rpc-openstack/rpcd/playbooks/roles/rpc_maas/templates/neutron_metadata_agent_proxy_check.yaml.j2 or /opt/rpc-openstack/rpcd/playbooks/neutron_metadata_agent_proxy_check.yaml.j2
fatal: [master-node2_neutron_agents_container-e6d00835 -> master-node2] => input file not found at /opt/rpc-openstack/rpcd/playbooks/roles/rpc_maas/templates/neutron_metadata_agent_proxy_check.yaml.j2 or /opt/rpc-openstack/rpcd/playbooks/neutron_metadata_agent_proxy_check.yaml.j2
```

**Comment by d34dh0r53** [comment] 2015-12-15 15:11
Closing this, all PRs have merged

**Closed by d34dh0r53** 2015-12-15 15:11 UTC
Labels: kilo-backport-potential, prio-1
