### ISSUE TITLE
Kilo upgrade to Liberty died on repo build process

### ISSUE THREAD

**Issue by b3rnard0** [rcbops/rpc-openstack#1226] opened 2016-07-07 18:49 UTC
Tracking of the following OSA bug:

https://bugs.launchpad.net/openstack-ansible/+bug/1585243

**Comment by git-harry** [comment] 2016-07-14 10:34
Duplicate of https://github.com/rcbops/rpc-openstack/issues/1131

**Closed by git-harry** 2016-07-14 10:34 UTC
Labels: impacts-onboarding, osa-tracking, prio-wishlist, status-duplicate
