### ISSUE TITLE
RPC Logo is not in Horizon

### ISSUE THREAD

**Issue by brainerd123** [rcbops/rpc-openstack#1088] opened 2016-05-18 17:47 UTC
##### What version (commit) do you encounter this issue on?
12.1.1

##### What type of issue is this (bug, feature, documentation, regression)?'

Bug

##### What is the expected behavior?

We should see the RPC Logo in Horizon, not the native Openstack Logo

##### What is actually happening?

We are seeing the native OpenStack logo in Liberty.  We upgraded this environment from 11.1.2 to 12.1.1 and noticed we lost the RPC Logo.

##### How can we reproduce this issue?

https://cloud1.osic.org

##### How can we verify your issue is addressed?

click this link for the OSIC horizon dashboard: https://cloud1.osic.org 

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

Not an urgent matter...more branding

##### What is your evaluation on the importance of this issue, and why?

Not super high priority, but has cosmetic and branding implications

##### What branches / milestones do you believe this issue should target?

12.1.1 RPC
###### The list below is what is currently supported for backports

NA
###### Remove branches (lines) you do not wish to target.

- [x] Master
- [ ] liberty-12.2

**Comment by d34dh0r53** [comment] 2016-05-23 21:06
Were the `rpc_support` plays re-run after the upgrade?

**Comment by d34dh0r53** [comment] 2016-05-23 21:18
Confirmed that the `rpc_support` play was run, we should look into this.

**Comment by BjoernT** [comment] 2016-05-24 20:33
It sense a race condition issue here, if you rerun os-horizon-install that seem to revert the settings, if they are part of rpc-support. Something similar your be how we patch the nova spice console

**Comment by mancdaz** [comment] 2016-06-17 11:19
@evrardjp if you're going to backport this to liberty, then some notes will need to be added to ensure the deployer copies the appropriate settings from ```rpcd/etc/user_variables.yml``` into ```/etc/openstack_deploy/user_variables.yml``` for this to take effect.

**Comment by evrardjp** [comment] 2016-06-17 14:57
Ok, I'll make sure the doc will be included. Thanks for the reminder!

**Comment by b3rnard0** [comment] 2016-06-21 13:23
This being a priority 2 issue, I'm moving this back to the backlog and we can reprioritize in the future.

**Comment by evrardjp** [comment] 2016-09-20 16:00
Move this to need review when WIP is lower.

**Comment by git-harry** [comment] 2016-10-05 14:20
@evrardjp is there any reason to keep this open now you have created https://github.com/rackerlabs/docs-rpc/issues/619

**Comment by git-harry** [comment] 2016-10-10 08:51
Closing because now handled by docs team https://github.com/rackerlabs/docs-rpc/issues/619

**Closed by git-harry** 2016-10-10 08:51 UTC
Labels: prio-2, status-needs-review, swimlane-rr, type-bug
